Repository shaka-project/shaka-player, pull requests merged in 2020-08, with the labels that each got.

#2777 Fix src= playback on WebOS
  lib/player.js
Labels: TV/STB, bug

#2779 Render bold/italics/underline on SimpleTextDisplayer
  lib/text/simple_text_displayer.js
  test/text/simple_text_displayer_unit.js
Labels: enhancement

#2801 PlayReady only has little-endian key IDs on Edge & IE
  lib/media/drm_engine.js
  lib/util/platform.js
Labels: enhancement

#2794 Add note about CEA-608/708
  README.md
Labels: docs

#2790 Check KEYID format in lowercase
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: bug
