Repository shaka-project/shaka-player, pull requests merged in 2021-02, with the labels that each got.

#3060 Add SubStation Alpha (SSA) support
  README.md
  build/types/text
  lib/player.js
  lib/text/lrc_text_parser.js
  lib/text/ssa_text_parser.js
  lib/text/web_vtt_generator.js
  shaka-player.uncompiled.js
  test/text/ssa_text_parser_unit.js
  test/text/web_vtt_generator_unit.js
Labels: waiting for review

#3063 Add SubViewer (SBV) support
  README.md
  build/types/text
  lib/player.js
  lib/text/lrc_text_parser.js
  lib/text/sbv_text_parser.js
  lib/text/ssa_text_parser.js
  lib/text/text_engine.js
  shaka-player.uncompiled.js
  test/text/sbv_text_parser_unit.js
Labels: waiting for update

#3043 fix for TTML localised whitespace preservation #3011
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: bug

#3071 Add support to WebVTT style blocks
  lib/text/mp4_vtt_parser.js
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: enhancement

#3072 Fixed choice of codecs for 4K and higher
  lib/util/multi_map.js
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: bug
