Repository shaka-project/shaka-player, pull requests merged in 2022-02, with the labels that each got.

#3921 test: Switch local Chrome, Edge, Firefox, and Safari launchers to WebDriver-based
  package.json
  test/test/assets/screenshots/msedge-Mac/native-basic-cue.png
  test/test/assets/screenshots/msedge-Mac/native-bitmap-cue.png
  test/test/assets/screenshots/msedge-Mac/native-cue-position.png
  test/test/assets/screenshots/msedge-Mac/native-cue-with-newline.png
  test/test/assets/screenshots/msedge-Mac/native-deeply-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/native-duplicate-cues.png
  test/test/assets/screenshots/msedge-Mac/native-end-time-edge-case.png
  test/test/assets/screenshots/msedge-Mac/native-flat-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/native-nested-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/msedge-Mac/native-region-position.png
  test/test/assets/screenshots/msedge-Mac/native-region-with-display-alignment.png
  test/test/assets/screenshots/msedge-Mac/native-two-basic-cues.png
  test/test/assets/screenshots/msedge-Mac/native-two-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/ui-basic-cue.png
  test/test/assets/screenshots/msedge-Mac/ui-bitmap-cue.png
  test/test/assets/screenshots/msedge-Mac/ui-cue-position.png
  test/test/assets/screenshots/msedge-Mac/ui-cue-with-controls.png
  test/test/assets/screenshots/msedge-Mac/ui-cue-with-newline.png
  test/test/assets/screenshots/msedge-Mac/ui-deeply-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/ui-duplicate-cues.png
  test/test/assets/screenshots/msedge-Mac/ui-end-time-edge-case.png
  test/test/assets/screenshots/msedge-Mac/ui-flat-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/ui-nested-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/ui-nested-cues-with-linebreak.png
  test/test/assets/screenshots/msedge-Mac/ui-region-position.png
  test/test/assets/screenshots/msedge-Mac/ui-region-with-display-alignment.png
  test/test/assets/screenshots/msedge-Mac/ui-two-basic-cues.png
  test/test/assets/screenshots/msedge-Mac/ui-two-nested-cues.png
Labels: component: UI, component: tests

#3930 chore: Update roadmap
  roadmap.md
Labels: type: docs

#3929 test: Added integration test for sequence mode
  test/player_integration.js
  test/test/util/test_scheme.js
Labels: component: HLS, component: tests

#3931 fix: Probe for containerless format support.
  demo/main.js
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
Labels: component: HLS, component: demo page

#3937 ci: Require PRs in conventional commits syntax
  .github/workflows/validate_pr_title.yaml
Labels: type: CI

#3939 ci: Migrate update-issues tool to a central location
  .github/workflows/README.md
  .github/workflows/build_and_test.yaml
  .github/workflows/test_update_issues.yaml
  .github/workflows/tools/update-issues/issues.js
  .github/workflows/tools/update-issues/main.js
  .github/workflows/tools/update-issues/mocks.js
  .github/workflows/tools/update-issues/package-lock.json
  .github/workflows/tools/update-issues/package.json
  .github/workflows/tools/update-issues/reporter.js
  .github/workflows/tools/update-issues/tests.js
  .github/workflows/update_issues.yaml
Labels: type: CI

#3884 fix(HLS): skip whitespace in attributes
  lib/hls/manifest_text_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS

#3944 ci: Fix ffmpeg install failure for Linux+Firefox
  .github/workflows/build_and_test.yaml
Labels: type: CI, platform: Linux, browser: Firefox, component: tests

#3943 test: Fix failing WebDriver installations
  package-lock.json
  package.json
Labels: type: CI, component: tests

#3942 ci: Add workflow for automated release PRs
  .github/workflows/release.yaml
  .npmignore
  .release-please-config.json
  .release-please-manifest.json
  CHANGELOG.md
  lib/player.js
Labels: type: CI

#3951 ci: Synchronize issue labels using a central configuration
  .github/workflows/README.md
  .github/workflows/build_and_test.yaml
  .github/workflows/sync-labels.yaml
Labels: type: CI

#3950 fix: Add explicit release() for FakeEventTarget
  lib/ads/ad_manager.js
  lib/cast/cast_proxy.js
  lib/cast/cast_receiver.js
  lib/net/networking_engine.js
  lib/player.js
  lib/util/fake_event_target.js
  ui/controls.js
  ui/localization.js
Labels: type: bug

#3954 ci: Add missing token parameter to sync-labels workflow
  .github/workflows/sync-labels.yaml
Labels: type: CI

#3956 ci: Fix typo in dry_run parameter for sync-labels
  .github/workflows/sync-labels.yaml
Labels: type: CI

#3953 refactor: Replace callbacks with events
  lib/media/quality_observer.js
  lib/media/region_observer.js
  lib/media/region_timeline.js
  lib/player.js
  test/media/quality_observer_unit.js
  test/media/region_observer_unit.js
  test/media/region_timeline_unit.js
Labels: type: code health

#3955 fix(text): Fix webvtt offset in sequence mode
  externs/shaka/text.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/text/lrc_text_parser.js
  lib/text/mp4_ttml_parser.js
  lib/text/mp4_vtt_parser.js
  lib/text/sbv_text_parser.js
  lib/text/srt_text_parser.js
  lib/text/ssa_text_parser.js
  lib/text/text_engine.js
  lib/text/ttml_text_parser.js
  lib/text/vtt_text_parser.js
  test/media/media_source_engine_unit.js
  test/text/text_engine_unit.js
Labels: type: bug, component: HLS, component: captions/subtitles, component: WebVTT

#3957 fix: Fix memory leak in DASH live streams with inband EventStream
  lib/dash/dash_parser.js
  lib/media/region_observer.js
  lib/media/region_timeline.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/media/region_observer_unit.js
  test/media/region_timeline_unit.js
Labels: type: bug, component: DASH

#3961 ci: Test PRs against release branches, too
  .github/workflows/build_and_test.yaml
Labels: type: CI

#3972 build: Update version parsing to match new release automation
  build/checkversion.py
Labels: type: CI

#3973 build: Update most dev dependencies
  package-lock.json
  package.json
Labels: dependencies

#3977 build: Update eslint
  lib/cea/cea608_data_channel.js
  lib/cea/mp4_cea_parser.js
  lib/text/ttml_text_parser.js
  lib/util/mp4_parser.js
  lib/util/platform.js
  package-lock.json
  package.json
  test/media/presentation_timeline_unit.js
Labels: type: CI, component: build system

#3982 build: Downgrade less
  build/compiler.py
  package-lock.json
  package.json
  ui/less/ad_controls.less
  ui/less/buttons.less
  ui/less/containers.less
  ui/less/range_elements.less
  ui/less/tooltip.less
Labels: type: CI, component: build system

#3993 ci: Simplify PR template
  .github/pull_request_template.md
Labels: type: CI

#3991 build: Upgrade CSS linter
  .csslintrc
  demo/cast_receiver/index.html
  demo/cast_receiver/receiver_app.css
  demo/demo.less
  package-lock.json
  package.json
  ui/less/ad_controls.less
  ui/less/buttons.less
  ui/less/containers.less
  ui/less/overflow_menu.less
  ui/less/tooltip.less
Labels: component: build system

#3992 ci: Fix several release workflow bugs
  .github/workflows/release.yaml
Labels: type: CI

#3994 build: Update jsdoc fork
  package-lock.json
  package.json
Labels: component: build system

#3996 ci: Rename workflows
  .github/workflows/README.md
  .github/workflows/build-and-test.yaml
  .github/workflows/release-please.yaml
  .github/workflows/update-issues.yaml
  .github/workflows/validate-pr-title.yaml
Labels: type: CI

#3995 build: Replace less-plugin-clean-css and htmlhint with forks
  package-lock.json
  package.json
Labels: component: build system

#4002 fix(hls): Fixed buffering issue with live HLS
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/fake_media_source_engine.js
Labels: type: bug, component: HLS
