Repository shaka-project/shaka-player, pull requests merged in 2022-07, with the labels that each got.

#4324 feat: Add fallback to TextDecoder and TextEncoder
  build/conformance.textproto
  demo/index.html
  docs/tutorials/upgrade.md
  lib/util/string_utils.js
  package-lock.json
  package.json
Labels: type: enhancement

#4347 docs: Document maintained branches
  README.md
  maintained-branches.md
Labels: type: docs

#4373 ci: Fix Safari 14 tests
  .github/workflows/build-and-test.yaml
Labels: type: CI, browser: Safari
