Repository shaka-project/shaka-player, pull requests merged in 2022-12, with the labels that each got.

#4727 fix(cast): Use cast platform APIs in MediaCapabilties polyfill
  lib/polyfill/media_capabilities.js
  test/polyfill/media_capabilities_unit.js
Labels: type: bug, priority: P1, platform: Cast

#4770 feat: Support customizing clearBuffers and safeMargin when select variants by label
  AUTHORS
  CONTRIBUTORS
  lib/player.js
Labels: type: enhancement, priority: P3

#4769 feat: Enable variant failover for BAD_HTTP_STATUS and TIMEOUT
  AUTHORS
  CONTRIBUTORS
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P2

#4756 fix(cea): Fix not rendering CEA-608 on encrypted mp4 segments
  externs/shaka/mp4_parser.js
  lib/cea/mp4_cea_parser.js
  lib/util/mp4_box_parsers.js
  lib/util/mp4_parser.js
Labels: type: bug, component: captions/subtitles, priority: P1

#4785 fix(HLS): Single alternative video renditions not working
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#4789 feat: Cache mediaCapabilities.decodingInfo results
  lib/util/stream_utils.js
  test/test/boot.js
Labels: type: enhancement, priority: P2

#4778 perf: Caching mediaSource support for browser engine
  AUTHORS
  CONTRIBUTORS
  build/types/core
  lib/media/media_source_capabilities.js
  lib/media/media_source_engine.js
  lib/media/transmuxer.js
  lib/polyfill/media_capabilities.js
  lib/util/stream_utils.js
  test/polyfill/media_capabilities_unit.js
Labels: type: performance, priority: P1

#4794 docs: Update docs about dev dependencies
  build/install-linux-prereqs.sh
  docs/tutorials/welcome.md
Labels: type: docs

#4781 feat(ui): Add ability to build UI without cast
  build/build.py
  conditional/dummy_cast_proxy.js
Labels: component: UI, component: build system

#4796 fix(cast): Added existence checks for MediaDecodingConfig.{audio|video} in decodingInfo().
  lib/polyfill/media_capabilities.js
Labels: type: bug, priority: P1, platform: Cast

#4795 fix: Manually order key for decodingInfo cache
  lib/util/stream_utils.js
  test/test/boot.js
Labels: type: bug, priority: P1

#4779 feat(HLS): Poll HLS playlists using last segment duration
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P2

#4783 feat: Move forceTransmux from streaming to mediasource config
  demo/config.js
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/player_configuration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_unit.js
Labels: type: code health, priority: P2

#4797 fix: Correct default initDataTransform for legacy Apple Media Keys
  build/types/core
  build/types/fairplay
  lib/util/player_configuration.js
Labels: type: bug, priority: P1, component: FairPlay

#4733 fix: Fix subtitles not added to DOM region
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
Labels: type: bug, component: TTML, component: captions/subtitles, priority: P1

#4760 fix(HLS): Fix missing roles
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#4798 fix(TTML): Fix duplicate cues overlapping segment boundaries
  lib/text/ttml_text_parser.js
  test/text/mp4_ttml_parser_unit.js
  test/text/ttml_text_parser_unit.js
Labels: type: bug, component: TTML, priority: P1

#4801 fix(TTML): Add font-family mapping
  lib/text/ttml_text_parser.js
Labels: type: bug, component: TTML, component: UI, priority: P2

#4803 fix(HLS): Fix detection of Media Playlist for audio and video only in MP4
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#4810 fix(chapters): removed duplicate chapters by id
  AUTHORS
  CONTRIBUTORS
  lib/player.js
Labels: type: bug, priority: P2

#4814 test: Catch and print info from unhandled global exceptions
  test/test/boot.js
Labels: priority: P2, component: tests

#4812 test: Fix StreamingEngine tests on Tizen
  test/player_integration.js
  test/test/util/test_scheme.js
Labels: component: tests, platform: Tizen

#4824 fix(HLS): Fix AV sync over ad boundaries
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  test/test/util/manifest_parser_util.js
Labels: type: bug, component: HLS

#4816 docs: Fix AdsLoadedEvent and its description
  lib/ads/ad_manager.js
Labels: type: docs

#4840 fix: Fix duplicate updates in StreamingEngine
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#4841 fix: Treat regions uniquely
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
Labels: type: bug, component: UI, component: captions/subtitles
