Repository shaka-project/shaka-player, pull requests merged in 2022-01, with the labels that each got.

#3833 Github Actions
  .github/workflows/README.md
  .github/workflows/build_and_test.yaml
  test/media/segment_index_unit.js
Labels: component: tests

#3841 Github Actions macOS Integration Tests
  .github/workflows/build_and_test.yaml
  test/media/streaming_engine_integration.js
Labels: platform: macOS, component: tests

#3847 test: Add mac/Safari, mac/Edge to GitHub Actions workflow
  .github/workflows/build_and_test.yaml
Labels: type: CI, component: tests

#3849 fix(tests): Fix failing test on GitHub Actions.
  test/media/streaming_engine_integration.js
Labels: component: tests

#3883 test: Hide passing tests in GitHub actions runs.
  .github/workflows/build_and_test.yaml
  build/test.py
  karma.conf.js
Labels: component: tests

#3889 ci: New workflow to update issues
  .github/workflows/README.md
  .github/workflows/build_and_test.yaml
  .github/workflows/tools/update-issues/issues.js
  .github/workflows/tools/update-issues/main.js
  .github/workflows/tools/update-issues/package-lock.json
  .github/workflows/tools/update-issues/package.json
  .github/workflows/update_issues.yaml
Labels: type: CI

#3900 ci: Add tests for new update-issues tool
  .github/workflows/README.md
  .github/workflows/test_update_issues.yaml
  .github/workflows/tools/update-issues/main.js
  .github/workflows/tools/update-issues/mocks.js
  .github/workflows/tools/update-issues/package-lock.json
  .github/workflows/tools/update-issues/package.json
  .github/workflows/tools/update-issues/reporter.js
  .github/workflows/tools/update-issues/tests.js
Labels: type: CI

#3915 test: Fix flake in screenshot tests around native captions
  test/ui/text_displayer_layout_unit.js
Labels: component: UI, component: captions/subtitles, browser: Safari, component: tests

#3916 test: Make screenshot comparisons more tolerant
  karma.conf.js
  package.json
  test/test/util/util.js
  test/ui/text_displayer_layout_unit.js
Labels: component: UI, component: captions/subtitles, component: tests

#3914 test: Review screenshots by test or by platform
  test/test/assets/screenshots/review.html
Labels: component: UI, component: captions/subtitles, component: tests
