Repository shaka-project/shaka-player, pull requests merged in 2022-03, with the labels that each got.

#4018 ci: Revert to upstream release-please-action
  .github/workflows/release-please.yaml
Labels: type: CI

#4043 ci: Test Docker build
  .github/workflows/build-and-test.yaml
  build/docker/Dockerfile
Labels: type: CI

#3765 fix(dash): Account for bandwidth before filtering text stream
  AUTHORS
  CONTRIBUTORS
  lib/util/periods.js
  test/util/periods_unit.js
Labels: component: captions/subtitles, component: DASH

#4060 build: Stop using deprecated tool to generate closure deps
  build/gendeps.py
  package-lock.json
  package.json
Labels: component: build system

#4034 feat(hls): Read EXT-X-PROGRAM-DATE-TIME
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/hls/manifest_text_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_index.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
  lib/util/xml_utils.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/test/util/manifest_parser_util.js
Labels: type: enhancement, component: HLS

#4068 fix: Fix playRangeEnd for certain content
  lib/media/presentation_timeline.js
  test/player_integration.js
  test/player_unit.js
  test/test/util/manifest_generator.js
Labels: type: bug

#4079 test: Update Xbox One native text screenshots
  test/test/assets/screenshots/xboxone/native-basic-cue.png
  test/test/assets/screenshots/xboxone/native-cue-position.png
  test/test/assets/screenshots/xboxone/native-cue-with-newline.png
  test/test/assets/screenshots/xboxone/native-deeply-nested-cues.png
  test/test/assets/screenshots/xboxone/native-duplicate-cues.png
  test/test/assets/screenshots/xboxone/native-end-time-edge-case.png
  test/test/assets/screenshots/xboxone/native-flat-cue-bg.png
  test/test/assets/screenshots/xboxone/native-nested-cue-bg.png
  test/test/assets/screenshots/xboxone/native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/xboxone/native-region-position.png
  test/test/assets/screenshots/xboxone/native-region-with-display-alignment.png
  test/test/assets/screenshots/xboxone/native-two-basic-cues.png
  test/test/assets/screenshots/xboxone/native-two-nested-cues.png
Labels: component: tests

#4080 fix(hls): Support playing media playlists directly
  demo/common/asset.js
  demo/common/assets.js
  demo/common/message_ids.js
  demo/custom.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/error.js
  lib/util/mime_utils.js
  lib/util/player_configuration.js
  test/demo/demo_unit.js
  test/hls/hls_parser_unit.js
Labels: component: HLS

#4090 chore(HLS): Refactor unused bandwidth parameter
  lib/hls/hls_parser.js
Labels: type: code health, component: HLS
