Repository shaka-project/shaka-player, pull requests merged in 2022-10, with the labels that each got.

#4050 feat: LCEVC integration
  AUTHORS
  CONTRIBUTORS
  build/types/complete
  build/types/lcevc
  demo/common/assets.js
  demo/common/message_ids.js
  demo/config.js
  demo/index.html
  demo/locales/en.json
  demo/locales/source.json
  docs/design/lcevc-architecture.png
  docs/design/lcevc-demo.png
  docs/design/lcevc-integration.md
  externs/lcevc.js
  externs/shaka/player.js
  lib/cast/cast_utils.js
  lib/lcevc/lcevc_dil.js
  lib/media/media_source_engine.js
  lib/player.js
  lib/util/dom_utils.js
  lib/util/player_configuration.js
  package-lock.json
  package.json
  test/player_unit.js
  test/test/util/fake_media_source_engine.js
  ui/less/containers.less
  ui/ui.js
Labels: type: enhancement, priority: P3

#4539 ci: Fix reporting status from lab tests to PRs
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#4528 fix: Fix A/V sync in unaligned HLS VOD streams
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  test/media/media_source_engine_unit.js
Labels: type: bug, component: HLS, priority: P1

#4537 fix: Fix hang when seeking to the last segment
  AUTHORS
  CONTRIBUTORS
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#4478 fix: Fix in-band key rotation on Xbox One
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/player_configuration.js
  lib/util/pssh.js
  test/media/drm_engine_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
Labels: type: bug, component: EME, priority: P1, platform: Xbox, component: PlayReady

#4519 fix: Missing AES-128 key of last HLS segment
  AUTHORS
  CONTRIBUTORS
  lib/media/segment_index.js
  test/media/segment_index_unit.js
Labels: type: bug, component: HLS, priority: P1

#4541 ci: Fix reporting status from lab tests to PRs
  .github/workflows/custom-actions/set-commit-status/action.yaml
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#4523 fix: Respect existing app usage of Cast SDK
  AUTHORS
  CONTRIBUTORS
  lib/cast/cast_sender.js
Labels: type: bug, priority: P2, platform: Cast

#4546 test: Update Chrome-Mac native screenshots
  lib/util/platform.js
  test/test/assets/screenshots/chrome-Mac/native-basic-cue.png
  test/test/assets/screenshots/chrome-Mac/native-bitmap-cue.png
  test/test/assets/screenshots/chrome-Mac/native-cue-position.png
  test/test/assets/screenshots/chrome-Mac/native-cue-with-newline.png
  test/test/assets/screenshots/chrome-Mac/native-deeply-nested-cues.png
  test/test/assets/screenshots/chrome-Mac/native-duplicate-cues.png
  test/test/assets/screenshots/chrome-Mac/native-end-time-edge-case.png
  test/test/assets/screenshots/chrome-Mac/native-flat-cue-bg.png
  test/test/assets/screenshots/chrome-Mac/native-nested-cue-bg.png
  test/test/assets/screenshots/chrome-Mac/native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/chrome-Mac/native-region-position.png
  test/test/assets/screenshots/chrome-Mac/native-region-with-display-alignment.png
  test/test/assets/screenshots/chrome-Mac/native-two-basic-cues.png
  test/test/assets/screenshots/chrome-Mac/native-two-nested-cues.png
  test/ui/text_displayer_layout_unit.js
Labels: component: tests

#4543 fix: Fix errors with TS segments on Chromecast
  lib/media/media_source_engine.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
Labels: type: bug, component: HLS, priority: P1, platform: Cast

#4553 fix: Fix choppy HLS startup
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#4552 feat: Adds ChannelCount as a filter to the Player Select Audio Track Method
  AUTHORS
  CONTRIBUTORS
  lib/player.js
Labels: type: enhancement, priority: P2

#4511 feat(HLS): Lazy-load HLS media playlists
  lib/hls/hls_parser.js
  lib/media/presentation_timeline.js
  lib/player.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, type: performance, priority: P1

#4409 feat: Parse ID3 metadata
  build/types/core
  externs/mux.js
  externs/shaka/ads.js
  externs/shaka/player.js
  lib/ads/server_side_ad_manager.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/media/transmuxer.js
  lib/player.js
  lib/util/id3_utils.js
  lib/util/ts_parser.js
  test/media/media_source_engine_integration.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/assets/id3-metadata.aac
  test/test/assets/id3-metadata.ts
  test/test/util/id3_generator.js
  test/test/util/stream_generator.js
  test/test/util/test_scheme.js
  test/util/id3_utils_unit.js
  test/util/ts_parser_unit.js
Labels: type: enhancement, priority: P1

#4565 fix: Fixed LCEVC decode breaking dependencies issue and read me addition
  README.md
  externs/lcevc.js
  externs/shaka/player.js
  package.json
Labels: type: bug, priority: P2

#4564 feat: Allow playback of HLS Media Playlist with AAC by default
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P1

#4573 fix(hls): Fix single-variant HLS streams
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#4566 fix(offline): Add storage muxer init timeout
  lib/offline/indexeddb/storage_mechanism.js
  lib/util/error.js
  test/offline/storage_integration.js
Labels: type: bug, priority: P2, component: offline

#4576 test: Fix failed test on Tizen
  build/conformance.textproto
  test/media/streaming_engine_unit.js
Labels: type: bug

#4578 feat: Allow to customize HLS Live behavior
  .github/workflows/build-and-test.yaml
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: HLS, priority: P2

#4587 ci: Add EdgeLinux and EdgeMac, update screenshots
  build/shaka-lab.yaml
  test/test/assets/screenshots/msedge-Linux/native-basic-cue.png
  test/test/assets/screenshots/msedge-Linux/native-bitmap-cue.png
  test/test/assets/screenshots/msedge-Linux/native-cue-position.png
  test/test/assets/screenshots/msedge-Linux/native-cue-with-newline.png
  test/test/assets/screenshots/msedge-Linux/native-deeply-nested-cues.png
  test/test/assets/screenshots/msedge-Linux/native-duplicate-cues.png
  test/test/assets/screenshots/msedge-Linux/native-end-time-edge-case.png
  test/test/assets/screenshots/msedge-Linux/native-flat-cue-bg.png
  test/test/assets/screenshots/msedge-Linux/native-nested-cue-bg.png
  test/test/assets/screenshots/msedge-Linux/native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/msedge-Linux/native-region-position.png
  test/test/assets/screenshots/msedge-Linux/native-region-with-display-alignment.png
  test/test/assets/screenshots/msedge-Linux/native-two-basic-cues.png
  test/test/assets/screenshots/msedge-Linux/native-two-nested-cues.png
  test/test/assets/screenshots/msedge-Linux/ui-basic-cue.png
  test/test/assets/screenshots/msedge-Linux/ui-bitmap-cue.png
  test/test/assets/screenshots/msedge-Linux/ui-cue-position.png
  test/test/assets/screenshots/msedge-Linux/ui-cue-with-controls.png
  test/test/assets/screenshots/msedge-Linux/ui-cue-with-newline.png
  test/test/assets/screenshots/msedge-Linux/ui-deeply-nested-cues.png
  test/test/assets/screenshots/msedge-Linux/ui-duplicate-cues.png
  test/test/assets/screenshots/msedge-Linux/ui-end-time-edge-case.png
  test/test/assets/screenshots/msedge-Linux/ui-flat-cue-bg.png
  test/test/assets/screenshots/msedge-Linux/ui-nested-cue-bg.png
  test/test/assets/screenshots/msedge-Linux/ui-nested-cues-with-linebreak.png
  test/test/assets/screenshots/msedge-Linux/ui-region-position.png
  test/test/assets/screenshots/msedge-Linux/ui-region-with-display-alignment.png
  test/test/assets/screenshots/msedge-Linux/ui-two-basic-cues.png
  test/test/assets/screenshots/msedge-Linux/ui-two-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/native-basic-cue.png
  test/test/assets/screenshots/msedge-Mac/native-bitmap-cue.png
  test/test/assets/screenshots/msedge-Mac/native-cue-position.png
  test/test/assets/screenshots/msedge-Mac/native-cue-with-newline.png
  test/test/assets/screenshots/msedge-Mac/native-deeply-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/native-duplicate-cues.png
  test/test/assets/screenshots/msedge-Mac/native-end-time-edge-case.png
  test/test/assets/screenshots/msedge-Mac/native-flat-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/native-nested-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/msedge-Mac/native-region-position.png
  test/test/assets/screenshots/msedge-Mac/native-region-with-display-alignment.png
  test/test/assets/screenshots/msedge-Mac/native-two-basic-cues.png
  test/test/assets/screenshots/msedge-Mac/native-two-nested-cues.png
Labels: component: UI, type: CI

#4585 feat(HLS): allow customize live segments delay
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: HLS, priority: P2

#4581 fix(playhead): safeguard getStallsDetected as stallDetector can be null
  AUTHORS
  CONTRIBUTORS
  lib/media/playhead.js
Labels: type: bug, priority: P2

#4588 ci: Update workflow syntax
  .github/workflows/build-and-test.yaml
  .github/workflows/compute-incremental-coverage.py
  .github/workflows/selenium-lab-tests.yaml
Labels: priority: P1, type: CI

#4586 fix: Fix HLS live stream subtitle offsets
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P1, component: WebVTT

#4584 feat: Add external thumbnails with sprites support
  externs/shaka/player.js
  lib/media/segment_reference.js
  lib/player.js
  test/player_integration.js
  test/test/assets/thumbnails-sprites.vtt
Labels: type: enhancement, priority: P2

#4583 fix(hls): Fix raw format detection when the main playlist hasn't type
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#4594 ci: Re-run PR tests when leaving draft mode
  .github/workflows/build-and-test.yaml
Labels: type: CI

#4591 feat: Allow playback of HLS Media Playlist with RAW formats by default and support ID3
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P1

#4601 fix(HLS): Fix lazy-loading of TS content
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#4590 fix(HLS): Return 0-0 seek range until fully loaded
  lib/player.js
Labels: type: bug, component: HLS, priority: P2

#4560 feat: Improved LCEVC integration
  demo/common/assets.js
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  demo/search.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P2

#4598 fix: Make XML parsing secure
  build/conformance.textproto
  lib/media/drm_engine.js
  lib/text/ttml_text_parser.js
  lib/util/xml_utils.js
  test/util/xml_utils_unit.js
Labels: type: bug, priority: P1

#4606 fix: fix support clear and encrypted periods
  lib/media/drm_engine.js
Labels: type: bug, priority: P2, component: DASH

#4612 feat: TS parser improvements
  lib/util/ts_parser.js
  test/util/ts_parser_unit.js
Labels: priority: P2

#4609 fix: Fix ID3 parsing in TS segments
  lib/util/ts_parser.js
  test/util/ts_parser_unit.js
Labels: type: bug, priority: P1

#4603 ci: Update actions/checkout version
  .github/workflows/build-and-test.yaml
  .github/workflows/demo-version-index.yaml
  .github/workflows/nightly-demo.yaml
  .github/workflows/release-please.yaml
  .github/workflows/report-incremental-coverage.yaml
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#4615 fix(HLS): Add a guard on closeSegmentIndex
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#4617 chore: remove useless log about ID3
  lib/ads/ad_manager.js
Labels: priority: P3

#4607 feat: Add config for sequenceMode in DASH
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P2, component: DASH

#4624 ci: Disable Tizen
  build/shaka-lab.yaml
Labels: type: CI, platform: Tizen

#4629 fix: Fix multi-period DASH with descriptive audio
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P1

#4630 fix: Force using mcap polyfill on EOS browsers
  lib/polyfill/media_capabilities.js
Labels: type: bug, priority: P2

#4616 fix: DAI ID3 metadata parsing
  lib/util/ts_parser.js
  test/util/ts_parser_unit.js
Labels: type: bug, priority: P1

#4632 feat: Add AAC transmuxer
  demo/common/assets.js
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  docs/tutorials/faq.md
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/media/transmuxer.js
  lib/player.js
  lib/util/mime_utils.js
  lib/util/player_configuration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_unit.js
  test/media/transmuxer_integration.js
  test/player_unit.js
Labels: type: enhancement, component: HLS, priority: P1

#4627 feat: Allow clearKey configuration in base64 or hex
  externs/shaka/player.js
  lib/media/drm_engine.js
Labels: type: enhancement, priority: P2, component: ClearKey

#4518 fix(ads): Fix IMA crash when autoplay is rejected
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2
