Repository shaka-project/shaka-player, pull requests merged in 2022-11, with the labels that each got.

#4635 fix: Allow overriding special handling of 404s
  lib/media/streaming_engine.js
  lib/player.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/player_unit.js
Labels: type: bug, priority: P2

#4640 fix: Fix metadata assert when the ID3 is future (coming in a previous segment)
  lib/player.js
Labels: type: bug, priority: P1

#4644 fix(cast): Reduce size of Cast update messages
  lib/cast/cast_proxy.js
  lib/cast/cast_receiver.js
  lib/cast/cast_sender.js
  lib/cast/cast_utils.js
  test/cast/cast_receiver_integration.js
  test/cast/cast_receiver_unit.js
  test/cast/cast_utils_unit.js
Labels: type: bug, priority: P2, platform: Cast

#4642 fix: Simplify transmuxer to allow more mimetypes in the future
  lib/media/transmuxer.js
  lib/util/mime_utils.js
  test/media/media_source_engine_unit.js
Labels: type: bug, priority: P3

#4639 fix: Fix dispatch ID3 metadata when transmuxing AAC
  lib/media/media_source_engine.js
  lib/media/transmuxer.js
  test/media/media_source_engine_integration.js
  test/media/transmuxer_integration.js
  test/test/util/simple_fakes.js
Labels: type: bug, priority: P2

#4643 fix: embed cc not shown when seeking back
  AUTHORS
  CONTRIBUTORS
  externs/mux.js
  lib/media/media_source_engine.js
  lib/media/transmuxer.js
  test/media/media_source_engine_integration.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P2

#4648 fix: Fix HLS lazy-loading exception during update
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P1

#4645 fix: Fix HLS lazy-loading exception on switch
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P1

#4646 fix: Fix HLS lazy-loading with DRM
  externs/shaka/manifest_parser.js
  lib/hls/hls_parser.js
  lib/offline/storage.js
  lib/player.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/test/util/dash_parser_util.js
Labels: type: bug, component: HLS, priority: P1

#4575 fix: Content reload starttime with HLS on iOS
  lib/media/playhead.js
  lib/player.js
  test/media/playhead_unit.js
  test/test/util/simple_fakes.js
Labels: type: bug, component: HLS, priority: P2, platform: iOS

#4653 fix: focus on first element when back to the settings menu
  ui/settings_menu.js
Labels: type: bug, type: accessibility, priority: P2

#4656 fix(HLS): Infer missing codecs from config
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#4657 fix: Fix detection of ac4, dts, and dolby h265
  lib/util/manifest_parser_utils.js
Labels: type: bug, priority: P2

#4663 fix(HLS): Fix detection of WebVTT subtitles in HLS by extension
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#4568 feat(HLS): Support for HLS key rotation
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P1

#4655 feat(HLS): Add support for EXT-X-SESSION-KEY tag
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P1

#4669 fix(ui): Fix exception on screen rotation if fullscreen is not supported
  ui/controls.js
Labels: type: bug, component: UI

#4660 feat: Support HTML-escaped cues in VTT
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, priority: P3, component: WebVTT

#4682 fix: WebVTT line not correctly positioned in UITextDisplayer (#4567)
  AUTHORS
  CONTRIBUTORS
  lib/text/ui_text_displayer.js
  test/test/assets/screenshots/chrome-Android/native-line-alignment.png
  test/test/assets/screenshots/chrome-Android/ui-line-alignment.png
  test/test/assets/screenshots/chrome-Linux/native-line-alignment.png
  test/test/assets/screenshots/chrome-Linux/ui-line-alignment.png
  test/test/assets/screenshots/chrome-Mac/native-line-alignment.png
  test/test/assets/screenshots/chrome-Mac/ui-line-alignment.png
  test/test/assets/screenshots/chrome-Windows/native-line-alignment.png
  test/test/assets/screenshots/chrome-Windows/ui-line-alignment.png
  test/test/assets/screenshots/firefox-Linux/native-line-alignment.png
  test/test/assets/screenshots/firefox-Linux/ui-line-alignment.png
  test/test/assets/screenshots/firefox-Mac/native-line-alignment.png
  test/test/assets/screenshots/firefox-Mac/ui-line-alignment.png
  test/test/assets/screenshots/firefox-Windows/native-line-alignment.png
  test/test/assets/screenshots/firefox-Windows/ui-line-alignment.png
  test/test/assets/screenshots/msedge-Linux/native-line-alignment.png
  test/test/assets/screenshots/msedge-Linux/ui-line-alignment.png
  test/test/assets/screenshots/msedge-Mac/native-line-alignment.png
  test/test/assets/screenshots/msedge-Mac/ui-line-alignment.png
  test/test/assets/screenshots/msedge-Windows/native-line-alignment.png
  test/test/assets/screenshots/msedge-Windows/ui-line-alignment.png
  test/test/assets/screenshots/review.html
  test/test/assets/screenshots/safari-Mac/native-line-alignment.png
  test/test/assets/screenshots/safari-Mac/ui-line-alignment.png
  test/test/assets/screenshots/xboxone/native-line-alignment.png
  test/test/assets/screenshots/xboxone/ui-line-alignment.png
  test/ui/text_displayer_layout_unit.js
Labels: type: bug, priority: P2, component: WebVTT

#4685 test: Fix platform detection for Xbox
  lib/util/platform.js
Labels: priority: P3, type: CI, platform: Xbox

#4683 fix(cea): Fix not rendering CEA-608 Closed Captions
  build/types/cea
  lib/cea/dummy_cea_parser.js
  lib/cea/i_cea_parser.js
  lib/cea/mp4_cea_parser.js
  lib/media/closed_caption_parser.js
  lib/media/media_source_engine.js
  lib/player.js
  lib/util/mp4_box_parsers.js
  test/cast/cast_utils_unit.js
  test/media/closed_caption_parser_unit.js
  test/media/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
Labels: type: bug, component: captions/subtitles, priority: P1

#4687 fix(hls): Fix type error in lazy-loading
  .github/workflows/build-and-test.yaml
  lib/player.js
  package-lock.json
  package.json
  third_party/closure-uri/uri.js
Labels: type: bug, component: HLS

#4690 fix(ui): Check event cancelable before event.preventDefault
  ui/controls.js
Labels: type: bug, component: UI

#4694 test: Fix Xbox DRM tests
  test/media/drm_engine_unit.js
Labels: component: tests

#4695 test: Fix XML parser security tests on Xbox
  test/util/xml_utils_unit.js
Labels: component: tests

#4696 fix: Fix timestamp offset for ID3 on DAI-HLS
  lib/media/media_source_engine.js
Labels: type: bug

#4707 fix: Polyfill missing AbortController on Tizen
  build/build.py
  build/conformance.textproto
  build/types/polyfill
  lib/polyfill/abort_controller.js
  shaka-player.uncompiled.js
Labels: type: bug, priority: P1, platform: WebOS, platform: Tizen

#4711 fix: Fix usage of WebCrypto in old browsers
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1, platform: WebOS

#4715 fix(HLS): fix lazy load with multiple raw audio tracks
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#4718 fix: Fix bufferBehind setting broken by image segments
  lib/dash/segment_template.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P1, component: DASH

#4712 fix(HLS): Fix lowLatencyPresentationDelay when using autoLowLatencyMode
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#4708 feat: Caching and other efficiency improvements for mcap polyfill
  AUTHORS
  CONTRIBUTORS
  lib/polyfill/media_capabilities.js
  lib/util/stream_utils.js
  test/polyfill/media_capabilities_unit.js
Labels: type: enhancement, priority: P2

#4716 fix(HLS): Fix support legacy AVC1 codec used in HLS
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, component: HLS, priority: P1

#4735 test: Expand CEA test expectations
  test/media/media_source_engine_integration.js
  test/test/util/util.js
Labels: priority: P1, component: tests

#4739 test: Finish TS StreamGenerator
  test/media/media_source_engine_integration.js
  test/test/util/stream_generator.js
  test/test/util/test_scheme.js
Labels: priority: P1, component: tests

#4743 fix: Fix DRM workaround for Tizen and Xbox with hvc1/hev1 boxes
  lib/media/content_workarounds.js
Labels: type: bug, priority: P2, platform: Tizen

#4697 feat(cea): Add CEA parser for TS
  README.md
  build/types/cea
  externs/mux.js
  externs/shaka/player.js
  lib/cea/cea608_data_channel.js
  lib/cea/cea_decoder.js
  lib/cea/ts_cea_parser.js
  lib/media/closed_caption_parser.js
  lib/media/media_source_engine.js
  lib/media/transmuxer.js
  lib/text/text_engine.js
  lib/util/ts_parser.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/transmuxer_integration.js
Labels: type: enhancement, component: captions/subtitles, priority: P3

#4757 fix(cea): Fix MAX_ROWS in CEA-708 window
  lib/cea/cea708_window.js
Labels: type: bug, component: captions/subtitles, priority: P2

#4768 docs: Clarify description of drmTimeSeconds.
  externs/shaka/player.js
Labels: type: docs

#4763 feat: Add preferredAudioLabel to PlayerConfiguration
  AUTHORS
  CONTRIBUTORS
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  docs/tutorials/config.md
  externs/shaka/player.js
  lib/media/adaptation_set_criteria.js
  lib/player.js
  lib/util/player_configuration.js
  test/player_unit.js
  test/test/util/manifest_generator.js
Labels: type: enhancement, priority: P3
