Repository shaka-project/shaka-player, pull requests merged in 2022-08, with the labels that each got.

#4391 fix: Fix VP9 codec checks on Mac Firefox
  lib/util/stream_utils.js
Labels: type: code health, browser: Firefox

#4377 fix: Fix key ID byteswapping for PlayReady on PS4
  lib/media/drm_engine.js
Labels: type: bug, component: PlayReady, platform: Playstation 4

#4396 fix: Fix MediaCapabilities polyfill on Tizen and WebOS
  lib/polyfill/media_capabilities.js
Labels: type: bug, component: EME, platform: WebOS, platform: Tizen

#4384 fix: Fix UI captions icon state
  ui/text_selection.js
Labels: type: bug, component: UI

#4403 fix: Fix TextDecoder fallback and browser support check
  karma.conf.js
  lib/player.js
  lib/util/string_utils.js
  test/util/string_utils_unit.js
Labels: type: bug

#4386 feat(hls): Support AES-128 in HLS
  demo/common/assets.js
  externs/shaka/manifest.js
  lib/hls/hls_parser.js
  lib/media/segment_index.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/net/networking_engine.js
  lib/util/error.js
  test/hls/hls_parser_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/simple_fakes.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, component: HLS

#4390 test: Upload coverage report for PR and nightly tests
  .github/workflows/build-and-test.yaml
  .github/workflows/selenium-lab-tests.yaml
  karma.conf.js
Labels: type: CI

#4404 feat: Automatic ABR quality restrictions based on size
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/abr_manager.js
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement

#4416 fix(UI): Ad position and ad counter are too close to each other
  ui/less/ad_controls.less
Labels: type: bug, component: UI, component: ads

#4428 chore(HLS): Retired unused error code
  lib/hls/hls_parser.js
  lib/util/error.js
Labels: type: code health, component: HLS

#4417 feat(demo): Demo visualizer for buffered ranges.
  demo/common/message_ids.js
  demo/demo.less
  demo/index.html
  demo/locales/en.json
  demo/locales/source.json
  demo/main.js
  demo/visualizer.js
  demo/visualizer_button.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/fake_event.js
Labels: type: enhancement, component: demo page

#4435 fix: return width and height in the stats when we are using src=
  lib/player.js
  test/player_src_equals_integration.js
Labels: type: bug

#4452 test: Fix Tizen src= test
  test/player_src_equals_integration.js
  test/test/assets/small.mp4
Labels: component: tests

#4453 fix: Fix bitmap-based cue size
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles

#4451 feat: Add limited support for HLS "identity" key format
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
  test/player_integration.js
  test/test/util/manifest_generator.js
  test/test/util/test_scheme.js
Labels: type: enhancement, component: HLS

#4454 test: Split Selenium grid tests into multiple jobs
  .github/workflows/selenium-lab-tests.yaml
Labels: component: tests

#4462 test: Disable XboxOne
  build/shaka-lab.yaml
Labels: component: tests
