Repository shaka-project/shaka-player, pull requests merged in 2022-05, with the labels that each got.

#4184 feat: Add Id to chapters
  externs/shaka/player.js
  lib/player.js
Labels: type: enhancement

#4189 feat: Temporarily disable the active variant from NETWORK HTTP_ERROR
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/media/adaptation_set_unit.js
  test/media/streaming_engine_unit.js
  test/player_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
  test/util/stream_utils_unit.js
Labels: type: enhancement

#4194 fix: Do not report MANIFEST RESTRICTIONS_CANNOT_BE_MET error twice
  lib/player.js
Labels: type: bug

#4203 fix(hls): Fix av1 codec selection in HLS.
  lib/util/manifest_parser_utils.js
  test/hls/manifest_text_parser_unit.js
Labels: type: bug, component: HLS

#4205 test: Trigger RESTRICTIONS_CANNOT_BE_MET once from onKeyStatus error
  test/player_unit.js
Labels: component: tests

#4208 feat(hls): Add support for EXT-X-GAP
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/error.js
Labels: type: enhancement, component: HLS

#4213 docs: Add note to upgrade guide about manifest.hls.useFullSegmentsForStartTime
  docs/tutorials/upgrade.md
Labels: type: docs

#4216 fix: Fix exception with streaming.startAtSegmentBoundary
  lib/player.js
  test/player_unit.js
  test/test/util/simple_fakes.js
Labels: type: bug

#4217 fix: Fix VTT cue timing in HLS
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, component: HLS, component: WebVTT

#4228 fix: Wait for chapters track to be loaded
  lib/player.js
  lib/util/error.js
  test/player_integration.js
  test/player_src_equals_integration.js
  test/test/util/simple_fakes.js
Labels: type: bug

#4206 fix: PERIOD_FLATTENING_FAILED error when periods have different base sample types.
  lib/dash/dash_parser.js
  lib/util/mime_utils.js
  lib/util/periods.js
  lib/util/stream_utils.js
  test/util/mime_utils_unit.js
  test/util/periods_unit.js
Labels: type: bug, component: DASH

#4231 fix: Re-add initDataTransform config
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/util/player_configuration.js
Labels: type: bug

#4246 feat(UI): Added keyboardSeekDistance config to UI
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI

#4248 fix: Don't send drmsessionupdate after unload
  lib/media/drm_engine.js
Labels: type: bug

#4241 fix: Fix audio mime type in multiplexed HLS stream
  lib/util/mime_utils.js
Labels: type: bug, component: HLS

#4257 feat: Add support to text-shadow in VTT parser
  externs/shaka/text.js
  lib/text/cue.js
  lib/text/ui_text_displayer.js
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, component: captions/subtitles, component: WebVTT
