Repository shaka-project/shaka-player, pull requests merged in 2022-09, with the labels that each got.

#4472 ci: Auto-deflake nightly selenium tests
  .github/workflows/deflake.yaml
Labels: type: CI

#4483 fix: Fix HLS dynamic to static transition
  externs/shaka/manifest_parser.js
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/offline/storage.js
  lib/player.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/media/media_source_engine_unit.js
  test/test/util/dash_parser_util.js
Labels: type: bug, component: HLS

#4389 feat: Parse and surface "prft" boxes as events
  externs/shaka/player.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/util/fake_event.js
  lib/util/player_configuration.js
  test/demo/demo_unit.js
  test/media/streaming_engine_unit.js
Labels: type: enhancement

#4493 fix: Filter unsupported H.264 streams in Xbox
  lib/util/stream_utils.js
Labels: type: bug, platform: Xbox

#4498 docs: Add support for documenting top-level enums
  docs/jsdoc-template/publish.js
  docs/jsdoc-template/tmpl/container.tmpl
  docs/jsdoc.conf.json
Labels: type: docs

#3421 feat: New autoShowText config to change initial text visibility behavior
  build/types/core
  demo/common/message_ids.js
  demo/config.js
  demo/demo.less
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/config/auto_show_text.js
  lib/player.js
  lib/util/player_configuration.js
  test/player_integration.js
Labels: type: enhancement, component: captions/subtitles

#4488 feat(ads): Ignore ad events with no associated ad
  externs/ima.js
  lib/ads/client_side_ad_manager.js
Labels: type: enhancement, component: ads

#4485 fix: allow the playback on platforms when low latency APIs are not supported
  lib/media/streaming_engine.js
Labels: type: bug, platform: WebOS, platform: Tizen

#4506 fix: allow build without text
  build/types/core
  build/types/text
Labels: type: bug

#4501 test: Add additional test for ads
  test/ads/ad_manager_unit.js
Labels: type: code health, component: ads

#4471 feat: enable uninstalling PatchedMediaKeysApple
  AUTHORS
  CONTRIBUTORS
  docs/tutorials/fairplay.md
  lib/polyfill/patchedmediakeys_apple.js
  test/polyfill/patchedmediakeys_apple_unit.js
Labels: type: enhancement, component: FairPlay

#4513 feat(ads): Add getTitle to CS and SS ads
  externs/ima.js
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
Labels: type: enhancement, component: ads, priority: P4

#4514 chore(ads): move resize logic to CS manager
  lib/ads/client_side_ad_manager.js
  ui/controls.js
Labels: type: code health, component: ads, priority: P2

#4510 fix: check for negative rows before moving
  lib/cea/cea608_memory.js
  test/cea/cea608_memory_unit.js
Labels: type: bug, component: captions/subtitles, priority: P1

#4496 fix(ttml): Default TTML background color to transparent if unspecified
  lib/text/ttml_text_parser.js
  test/test/util/ttml_utils.js
  test/text/ttml_text_parser_unit.js
Labels: type: bug, component: TTML, priority: P1

#4515 feat: Automatic ABR quality restrictions based on screen size
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#4520 test: Fix playback timeouts on ChromeMac
  test/media/streaming_engine_integration.js
  test/offline/offline_integration.js
Labels: component: tests

#4526 feat(ads): Add getDescription to CS and SS ads
  externs/ima.js
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
Labels: type: enhancement, component: ads, priority: P4

#4529 test: Expand test cases for HLS track roles
  test/hls/hls_parser_unit.js
Labels: component: tests

#4527 feat: Allow add extra features to MediaSource.addSourceBuffer
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/player.js
  lib/util/player_configuration.js
  test/cast/cast_utils_unit.js
  test/media/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
  test/player_unit.js
  test/test/util/fake_media_source_engine.js
Labels: type: enhancement, priority: P2

#4497 feat: Add external thumbnails support
  lib/cast/cast_utils.js
  lib/player.js
  lib/util/error.js
  test/player_integration.js
  test/test/assets/thumbnails-sprites.vtt
  test/test/assets/thumbnails.vtt
Labels: type: enhancement, priority: P2
