Repository shaka-project/shaka-player, pull requests merged in 2023-11, with the labels that each got.

#5842 fix(dash): fix race condition in segment template
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#5844 feat(DASH): Add support for minimum values in service descriptions
  demo/config.js
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/player.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#5846 fix: Fix nalu parsing and improve performance in the transmuxer
  externs/shaka/codecs.js
  lib/media/media_source_engine.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/ts_parser.js
  lib/util/uint8array_utils.js
  test/util/ts_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#5848 fix(offline): Fix server certificate error when trying to store content
  lib/offline/storage.js
Labels: type: bug, component: EME, priority: P1, component: offline

#5762 feat(DASH): Add initial support for "urn:mpeg:dash:ssr:2023"
  externs/shaka/abr_manager.js
  externs/shaka/manifest.js
  externs/shaka/offline.js
  lib/abr/simple_abr_manager.js
  lib/dash/dash_parser.js
  lib/dash/mpd_utils.js
  lib/dash/segment_template.js
  lib/hls/hls_parser.js
  lib/media/presentation_timeline.js
  lib/mss/mss_parser.js
  lib/net/networking_engine.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  lib/util/stream_utils.js
  test/abr/simple_abr_manager_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/mpd_utils_unit.js
  test/media/adaptation_set_unit.js
  test/net/networking_engine_unit.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
  test/test/util/offline_utils.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P3, component: DASH

#5855 fix: AD_STARTED fires before ad started with AWS Media Tailor
  lib/ads/media_tailor_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#5853 feat: Add config to ignore duplicate init data
  demo/config.js
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#5852 feat: Add support for WPE based browsers in RDK set-top boxes
  README.md
  lib/player.js
  lib/polyfill/mediasource.js
Labels: type: enhancement, platform: TV/STB, priority: P4

#5859 fix: Fix variant filtering by preferredAudioChannelCount
  lib/offline/storage.js
  lib/player.js
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P1

#5862 feat(Demo): Add CBCS content to demo
  demo/common/assets.js
Labels: type: enhancement, component: demo page, priority: P3

#5850 feat: Add video progress events
  lib/player.js
  lib/util/fake_event.js
Labels: type: enhancement, priority: P2

#5856 feat(HLS): Add support for mjpg I-Frames playlist
  README.md
  demo/common/assets.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/player.js
  lib/util/stream_utils.js
  test/hls/hls_parser_unit.js
  ui/seek_bar.js
Labels: type: enhancement, component: HLS, priority: P3

#5866 feat(demo): Add icon for new demo asset
  demo/common/assets.js
Labels: component: demo page

#5863 feat(UI): Add chapter titles and dividers on the seek bar
  demo/common/assets.js
  demo/search.js
  docs/tutorials/ui-customization.md
  lib/player.js
  ui/externs/ui.js
  ui/less/range_elements.less
  ui/localization.js
  ui/seek_bar.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P4

#5872 feat(Demo): Add new 3D movie stream from Apple
  demo/common/assets.js
  demo/main.js
  demo/search.js
  lib/media/media_source_engine.js
Labels: type: enhancement, component: demo page, priority: P4

#5871 fix(HLS): Fix decryption of AES-128
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P1

#5710 feat(DASH): Add support for Content Steering
  README.md
  build/types/core
  externs/shaka/manifest_parser.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/net/networking_engine.js
  lib/offline/offline_manifest_parser.js
  lib/player.js
  lib/util/content_steering_manager.js
  test/dash/dash_parser_manifest_unit.js
  test/offline/storage_integration.js
  test/test/util/test_scheme.js
  test/util/content_steering_manager_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#5869 fix: Fix missing audio streams
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P1

#5875 fix: Fix selectAudioLanguage using channelsCount param
  lib/media/adaptation_set_criteria.js
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P1

#5868 feat(UI): Show the channel count in the audio selector
  ui/audio_language_selection.js
  ui/externs/ui.js
  ui/language_utils.js
  ui/locales/en.json
  ui/locales/es-419.json
  ui/locales/es.json
  ui/locales/source.json
  ui/text_selection.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#5879 fix(ABR): Fix HLS playback after internet connection is restored
  lib/abr/simple_abr_manager.js
Labels: type: bug, component: HLS, priority: P1

#5877 feat(HLS): Add new config for allow LL-HLS byterange optimization
  demo/config.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: HLS, priority: P3

#5878 fix(HLS): Fix bad detection in some MediaPlaylist
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#5876 fix(HLS): Fix LL-HLS with byterange optimization using segments mode
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2

#5864 refactor(HLS): Refactor URLs management in HLS
  lib/hls/hls_classes.js
  lib/hls/hls_parser.js
  lib/hls/hls_utils.js
  lib/hls/manifest_text_parser.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/hls/manifest_text_parser_unit.js
  test/test/util/manifest_parser_util.js
Labels: component: HLS, priority: P3

#5884 feat(DASH): Add support for Content Steering in AdaptationSet BaseURL
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#5881 feat(HLS): Add support for Content Steering
  lib/hls/hls_parser.js
  lib/util/content_steering_manager.js
  test/hls/hls_parser_unit.js
  test/test/util/fake_networking_engine.js
Labels: type: enhancement, component: HLS, priority: P3

#5887 fix: Fix mangled property in compiled mode in Content Steering
  lib/util/content_steering_manager.js
Labels: type: bug, priority: P2

#5893 fix: CEA decoder should return early if packet is not large enough
  lib/cea/cea_decoder.js
  test/cea/cea_decoder_unit.js
Labels: type: bug, component: captions/subtitles, priority: P1

#5895 fix: Add Orange platform to requiresEncryptionInfoInAllInitSegments
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, priority: P2

#5892 fix: Allow get seekRange on manifestparsed event in some cases
  lib/player.js
Labels: type: bug, priority: P2

#5888 feat(Demo): Add Content Steering assets
  demo/common/assets.js
  demo/search.js
Labels: type: enhancement, component: demo page, priority: P3

#5886 feat(HLS): Improve the stream info when EXT-X-MEDIA has not uri
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5885 docs: Update docs for v4.6 release
  docs/tutorials/upgrade.md
  maintained-branches.md
  roadmap.md
Labels: type: docs

#5899 fix(DASH): SegmentTemplate@media not updated after change in manifest
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#5904 fix: Fix language comparison in addTextTrackAsync
  lib/player.js
Labels: type: bug, priority: P2

#5900 feat: Add support for Common Media Server Data (CMSD)
  build/types/core
  demo/common/assets.js
  demo/config.js
  externs/shaka/abr_manager.js
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/player.js
  lib/util/cmsd_manager.js
  lib/util/player_configuration.js
  test/util/cmsd_manager_unit.js
Labels: type: enhancement, priority: P3

#5910 fix(DASH): Fix false redirect detection
  lib/dash/dash_parser.js
Labels: type: bug, priority: P2, component: DASH

#5909 chore(DASH): Simplify content steering management in DASH
  lib/dash/dash_parser.js
Labels: priority: P3, component: DASH

#5908 fix: Unmask errors on LL
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#5916 fix(HLS): Recognize CEA subtitles when CLOSED-CAPTIONS attribute is missing
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P1

#5921 fix: Only append to the buffer init segments when the segment is independent
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P2

#5914 feat(DASH): Add support for location in Content Steering
  lib/dash/dash_parser.js
  lib/util/content_steering_manager.js
  test/dash/dash_parser_live_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#5920 fix: Fix init segment comparison
  lib/media/segment_reference.js
Labels: type: bug, priority: P2

#5922 chore(LCEVC): Update lcevc_dec.js dependency
  docs/tutorials/lcevc.md
  package-lock.json
  package.json
Labels: priority: P1

#5924 feat: expose CEA708 window position in the cue's region
  lib/cea/cea708_service.js
  lib/cea/cea708_window.js
  test/cea/cea708_service_unit.js
  test/cea/cea708_window_unit.js
  test/cea/cea_decoder_unit.js
  test/test/util/cea_utils.js
Labels: type: enhancement, component: captions/subtitles, priority: P2

#5926 feat: Set baseDelay to 100 by default for low latency streaming
  docs/tutorials/config.md
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#5927 feat(Demo): Use MediaSession action handler in the demo
  demo/main.js
  externs/mediasession.js
Labels: type: enhancement, component: demo page, priority: P3

#5928 feat(UI): Hide language and resolution overflow menu button if there's only one choice
  ui/audio_language_selection.js
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#5929 fix(UI): Correctly display video time and duration for VOD
  ui/presentation_time.js
Labels: type: bug, component: UI, priority: P2

#5925 fix(CEA): Fix positioning in CEA-608
  lib/cea/cea608_memory.js
  test/cea/cea608_memory_unit.js
  test/cea/cea_decoder_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#5933 fix: Fix transmuxer when sample has no video data
  lib/transmuxer/ts_transmuxer.js
  lib/util/error.js
Labels: type: bug, component: HLS, priority: P1

#5934 feat(Demo): Add field for chapters URL when adding custom content
  demo/common/asset.js
  demo/custom.js
  demo/main.js
Labels: type: enhancement, component: demo page, priority: P3

#5936 fix(Demo): Pressing "Edit" button unstores custom asset, but does not update "stored" button
  demo/custom.js
Labels: type: bug, component: demo page, priority: P3

#5937 feat: Avoid streams which cannot fit into the browser's MediaSource quota
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3

#5938 feat: Add config to allow Media Source recoveries
  build/misspellings.txt
  demo/config.js
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#5942 feat(UI): Add more keyboard shortcuts
  ui/controls.js
Labels: type: enhancement, component: UI, type: accessibility, priority: P3

#5941 fix: Properly size region anchor from LINE units
  CONTRIBUTORS
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P1

#5951 fix(HLS): Fix m4s extension detection
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#5949 fix: Fix reset Media Source when using mixed codecs in different containers
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#5948 feat: add preferred video label
  demo/config.js
  docs/tutorials/config.md
  externs/shaka/player.js
  lib/media/adaptation_set_criteria.js
  lib/player.js
  lib/util/player_configuration.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: enhancement, priority: P3

#5955 feat: Improve npm package size
  .npmignore
Labels: type: enhancement, priority: P3

#5953 feat(Demo): Add field for text URL when adding custom content
  demo/common/asset.js
  demo/custom.js
  demo/main.js
Labels: type: enhancement, component: demo page, priority: P3

#5952 fix: Fix ESDS box parser
  lib/util/mp4_box_parsers.js
  test/test/assets/audio-xhe-aac.mp4
  test/util/mp4_box_parsers_unit.js
Labels: type: bug, priority: P1

#5957 chore: Added missing license headers.
  externs/lcevc.js
  externs/shaka/codecs.js
  externs/shaka/transmuxer.js
Labels: type: process
