Repository shaka-project/shaka-player, pull requests merged in 2023-09, with the labels that each got.

#5559 fix: Fix PES parsing
  lib/util/ts_parser.js
Labels: type: bug, priority: P1

#5578 fix(HLS): Allow audio groups on audio-only content
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#5575 fix: Fix TS transmuxer when the main content is muxed
  externs/shaka/transmuxer.js
  lib/media/media_source_engine.js
  lib/transmuxer/ts_transmuxer.js
Labels: type: bug, component: HLS, priority: P1

#5582 fix: Remove debugging code on Simple Text
  lib/text/simple_text_displayer.js
Labels: type: bug, priority: P1

#5595 fix: Fix transmuxed audio timestamps
  lib/transmuxer/ts_transmuxer.js
Labels: type: bug, priority: P1

#5602 feat: Add manifestupdated event
  externs/shaka/manifest_parser.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/offline/storage.js
  lib/player.js
  lib/util/fake_event.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
Labels: type: enhancement, priority: P3

#5603 fix: com.apple.fps should work with the default initDataTransform when using legacy Apple Media Keys
  lib/util/player_configuration.js
Labels: type: bug, priority: P2, component: FairPlay

#5601 fix: fix preferred track selection on Safari
  lib/player.js
  lib/util/stream_utils.js
Labels: type: bug, priority: P2

#5600 fix(Demo): Allow com.apple.fps.1_0 in the custom DRM System field
  demo/custom.js
Labels: component: demo page, priority: P2

#5598 fix(HLS): Get the correct video codec for TS segments
  lib/hls/hls_parser.js
  lib/util/ts_parser.js
Labels: type: bug, component: HLS, priority: P2

#5608 ci: Publish NPM tags explicitly
  .github/workflows/release-please.yaml
Labels: type: CI

#5610 feat(CEA): Parse CEA from TS with H.265
  lib/cea/ts_cea_parser.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/ts_parser.js
Labels: type: enhancement, component: HLS, component: captions/subtitles, priority: P3

#5615 fix: Improve TsParse to avoid parsing errors
  lib/transmuxer/ts_transmuxer.js
  lib/util/ts_parser.js
Labels: type: bug, priority: P2

#5571 feat: Add TS transmuxer for muxed content
  README.md
  build/types/transmuxer
  demo/index.html
  demo/service_worker.js
  docs/tutorials/faq.md
  externs/mux.js
  karma.conf.js
  lib/dependencies/all.js
  lib/media/media_source_engine.js
  lib/transmuxer/mpeg_ts_transmuxer.js
  lib/transmuxer/muxjs_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/mp4_generator.js
  package-lock.json
  package.json
  shaka-player.uncompiled.js
  support.html
  test/test/assets/hls-ts-muxed-ac3-h264/media.m3u8
  test/test/assets/hls-ts-muxed-ac3-h264/s_00000.ts
  test/test/assets/hls-ts-muxed-ac3-h264/s_00001.ts
  test/test/assets/hls-ts-muxed-ac3-h264/s_00002.ts
  test/test/assets/hls-ts-muxed-ac3-h264/s_00003.ts
  test/test/assets/hls-ts-muxed-ac3-h264/s_00004.ts
  test/test/assets/hls-ts-muxed-ac3-h264/s_00005.ts
  test/test/assets/hls-ts-muxed-ec3-h264/ChID_voices_1280x720p_25fps_h264_6ch_256kbps_ddp_sub_0000.ts
  test/test/assets/hls-ts-muxed-ec3-h264/ChID_voices_1280x720p_25fps_h264_6ch_256kbps_ddp_sub_0001.ts
  test/test/assets/hls-ts-muxed-ec3-h264/ChID_voices_1280x720p_25fps_h264_6ch_256kbps_ddp_sub_0002.ts
  test/test/assets/hls-ts-muxed-ec3-h264/ChID_voices_1280x720p_25fps_h264_6ch_256kbps_ddp_sub_0003.ts
  test/test/assets/hls-ts-muxed-ec3-h264/prog_index.m3u8
  test/test/assets/hls-ts-muxed-mp3-h264/index.m3u8
  test/test/assets/hls-ts-muxed-mp3-h264/seg-1-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-2-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-3-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-4-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-5-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-6-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-7-v1-a1.ts
  test/test/assets/hls-ts-muxed-mp3-h264/seg-8-v1-a1.ts
  test/transmuxer/muxjs_transmuxer_integration.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, component: HLS, priority: P3

#5616 feat(HLS): Get the correct video info for TS segments with H.265
  lib/hls/hls_parser.js
  lib/util/exp_golomb.js
  lib/util/ts_parser.js
Labels: type: enhancement, component: HLS, priority: P3

#5619 fix(DASH): Fix race condition error while switching audio tracks
  lib/dash/segment_template.js
Labels: type: bug, priority: P2, component: DASH

#5641 fix(WebVTT): Fix wrong writing-mode in nested cues
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P2, component: WebVTT

#5633 feat(WebVTT): Add support to text-combine-upright
  externs/css_style_declaration.js
  lib/text/cue.js
  lib/text/ui_text_displayer.js
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, component: captions/subtitles, priority: P3, component: WebVTT

#5631 feat(ABR): Allow some downscale when use restrictToElementSize or restrictToScreenSize
  lib/abr/simple_abr_manager.js
Labels: type: enhancement, priority: P2

#5632 fix(WebVTT): Fix support for line:0 vertical alignment
  lib/text/ui_text_displayer.js
  test/test/assets/screenshots/chrome-Android/webvtt-ui-line-0.png
  test/test/assets/screenshots/chrome-Linux/webvtt-ui-line-0.png
  test/test/assets/screenshots/chrome-Mac/webvtt-ui-line-0.png
  test/test/assets/screenshots/chrome-Windows/webvtt-ui-line-0.png
  test/test/assets/screenshots/firefox-Linux/webvtt-ui-line-0.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-line-0.png
  test/test/assets/screenshots/firefox-Windows/webvtt-ui-line-0.png
  test/test/assets/screenshots/msedge-Linux/webvtt-ui-line-0.png
  test/test/assets/screenshots/msedge-Mac/webvtt-ui-line-0.png
  test/test/assets/screenshots/msedge-Windows/webvtt-ui-line-0.png
  test/test/assets/screenshots/safari-Mac/text-displayer-native-basic-cue.png
  test/test/assets/screenshots/safari-Mac/webvtt-ui-line-0.png
  test/text/web_vtt_layout_integration.js
Labels: type: bug, priority: P2, component: WebVTT

#5642 feat(WebVTT): Add support to ruby, rt, rp html tags
  lib/text/cue.js
  lib/text/ui_text_displayer.js
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, priority: P3, component: WebVTT

#5643 fix(HLS): Show WebVTT subtitles with X-TIMESTAMP-MAP in segments mode
  externs/shaka/text.js
  lib/media/media_source_engine.js
  lib/text/lrc_text_parser.js
  lib/text/mp4_ttml_parser.js
  lib/text/mp4_vtt_parser.js
  lib/text/sbv_text_parser.js
  lib/text/srt_text_parser.js
  lib/text/ssa_text_parser.js
  lib/text/text_engine.js
  lib/text/ttml_text_parser.js
  lib/text/vtt_text_parser.js
  test/text/text_engine_unit.js
Labels: type: bug, component: HLS, priority: P2, component: WebVTT

#5645 feat(TTML): Add support to tts:ruby
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: type: enhancement, component: TTML, priority: P3

#5630 fix: Compute correctly the positionAlign in UITextDisplayer
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P2

#5621 feat(DASH): Allow the playback of DASH with $time$ and large timescale value
  lib/dash/mpd_utils.js
  lib/dash/segment_template.js
Labels: type: enhancement, priority: P3, component: DASH

#5644 feat(TTML): Add support to tts:textCombine
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: type: enhancement, component: TTML, priority: P3

#5647 docs: Add Nagra to FairPlay tutorial
  docs/tutorials/fairplay.md
Labels: type: docs, priority: P2, component: FairPlay

#5655 chore(DASH): Create makeNetworkRequest_ method
  lib/dash/dash_parser.js
Labels: priority: P2, component: DASH

#5653 chore: Rename hlsAes128Key to aes128Key
  externs/shaka/manifest.js
  lib/hls/hls_parser.js
  lib/media/segment_index.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_unit.js
  test/media/segment_index_unit.js
  test/media/segment_prefetch_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/streaming_engine_util.js
Labels: priority: P2

#5654 chore: Rename HLS_AES_128_* to AES_128_*
  lib/hls/hls_parser.js
  lib/util/error.js
Labels: priority: P2

#5620 feat(DASH): Add new config to prevent mixing of audio representations from different adaptation sets
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/manifest.js
  externs/shaka/offline.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/adaptation_set.js
  lib/mss/mss_parser.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
  test/media/adaptation_set_criteria_unit.js
  test/media/adaptation_set_unit.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
  test/test/util/offline_utils.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P3, component: DASH

#5658 fix(HLS): Fix audio and video out of sync
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#5657 perf: Optimization to resolve uris
  lib/util/manifest_parser_utils.js
Labels: type: performance, priority: P1

#5650 feat(UI): Add remote button with RemotePlayback API
  build/types/ui
  docs/tutorials/ui-customization.md
  externs/media_remote.js
  shaka-player.uncompiled.js
  ui/remote_button.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#5611 feat: Add H.265 TS transmuxer
  README.md
  build/types/transmuxer
  karma.conf.js
  lib/transmuxer/h265.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/platform.js
  shaka-player.uncompiled.js
  test/test/assets/hls-ts-muxed-aac-h265/0.ts
  test/test/assets/hls-ts-muxed-aac-h265/1.ts
  test/test/assets/hls-ts-muxed-aac-h265/media.m3u8
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, component: HLS, priority: P3

#5662 revert: "fix(WebVTT): Fix wrong writing-mode in nested cues (#5641)"
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P1, component: WebVTT

#5656 feat(DASH): Add support for AES-128
  demo/common/asset.js
  demo/common/assets.js
  demo/common/message_ids.js
  demo/locales/en.json
  demo/locales/source.json
  demo/main.js
  karma.conf.js
  lib/dash/content_protection.js
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/util/error.js
  test/dash/dash_parser_integration.js
  test/test/assets/dash-aes-128/Fragments(video=0,format=mpd-time-csf)
  test/test/assets/dash-aes-128/Fragments(video=20000000,format=mpd-time-csf)
  test/test/assets/dash-aes-128/Fragments(video=40000000,format=mpd-time-csf)
  test/test/assets/dash-aes-128/Fragments(video=60000000,format=mpd-time-csf)
  test/test/assets/dash-aes-128/Fragments(video=i,format=mpd-time-csf)
  test/test/assets/dash-aes-128/dash.mpd
  test/test/assets/dash-aes-128/license
Labels: type: enhancement, priority: P3, component: DASH

#5674 fix: Fix creation of new Stream object for each manifest request in DASH Live when using CEA
  lib/dash/dash_parser.js
Labels: type: bug, component: captions/subtitles, priority: P1

#5665 chore(demo): Removed demo localization system
  build/check.py
  demo/asset_card.js
  demo/cast_receiver/index.html
  demo/close_button.js
  demo/common/asset.js
  demo/common/assets.js
  demo/common/message_ids.js
  demo/config.js
  demo/custom.js
  demo/front.js
  demo/index.html
  demo/input.js
  demo/input_container.js
  demo/locales/en.json
  demo/locales/source.json
  demo/main.js
  demo/search.js
  demo/tooltip.js
  demo/visualizer.js
  demo/visualizer_button.js
  test/demo/demo_unit.js
Labels: type: enhancement, type: code health, component: demo page

#5677 fix(HLS): Support AES-128 in init segment according the RFC
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#5673 fix: Fix some properties on the shaka.text.Cue that are mangled
  lib/text/cue.js
Labels: type: bug, component: captions/subtitles, priority: P1

#5676 test: Add H.265 in TS test
  karma.conf.js
  test/test/assets/hls-ts-h265/0.ts
  test/test/assets/hls-ts-h265/hevc.m3u8
  test/test/assets/hls-ts-h265/index.m3u8
  test/transmuxer/transmuxer_integration.js
Labels: component: tests

#5678 feat(HLS): Take into account the parsing time for manifest schedule update
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P2

#5675 test: Fix Dolby tests in Edge
  test/transmuxer/transmuxer_integration.js
Labels: priority: P1, component: tests

#5681 fix: Allow PID change in TsParser
  lib/util/ts_parser.js
  test/util/ts_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#5686 fix: Fix transmuxing of muxed content
  lib/transmuxer/ts_transmuxer.js
Labels: type: bug, component: HLS, priority: P1

#5687 fix(HLS): Fix presentation delay for small live playlists (eg: 3-4 segments)
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P1

#5679 feat(Ads): Add support for AWS Elemental MediaTailor
  README.md
  build/types/ads
  demo/common/asset.js
  demo/common/assets.js
  demo/main.js
  externs/mediatailor.js
  externs/shaka/ads.js
  lib/ads/ad_manager.js
  lib/ads/media_tailor_ad.js
  lib/ads/media_tailor_ad_manager.js
  lib/net/networking_engine.js
  lib/player.js
  lib/routing/payload.js
  lib/util/error.js
  test/routing/walker_unit.js
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#5691 feat(demo): Added icons for new demo assets
  demo/common/assets.js
Labels: type: enhancement, component: demo page

#5690 feat(UI): Add config to preferDocumentPictureInPicture
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#5694 fix(HLS): Fix display CEA-708 in HLS
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P1

#5699 fix(CMCD): Fix CMCD for some mimetypes in src=
  lib/util/cmcd_manager.js
Labels: type: bug, priority: P2
