Repository shaka-project/shaka-player, pull requests merged in 2023-01, with the labels that each got.

#4866 fix(ui): Avoid submitting form if player is inside form
  lib/util/dom_utils.js
Labels: type: bug, component: UI, priority: P2

#4867 fix: Fix flattenedCues in WebVttGenerator
  lib/text/web_vtt_generator.js
Labels: type: bug, component: captions/subtitles, priority: P2

#4871 fix: Release region timeline when unloading
  lib/player.js
Labels: type: bug, priority: P1

#4693 test: Consolidate emsg tests
  test/media/streaming_engine_unit.js
Labels: component: tests

#4848 fix: Fix media source duration when using sequence mode
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2

#4847 fix(HLS): Fix support for mixed AES-128/NONE decryption
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#4872 test: Added test to detect lingering timers
  lib/util/timer.js
  test/player_integration.js
Labels: priority: P1, component: tests

#4881 fix(HLS): Fix discontinuity tracking
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P0

#4883 feat: Config to require a minimum HDCP version
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/mediakeys.js
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/polyfill/patchedmediakeys_apple.js
  lib/polyfill/patchedmediakeys_nop.js
  lib/polyfill/patchedmediakeys_webkit.js
  lib/util/error.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: EME, priority: P3

#4884 fix: Fix potential duplicate segments, AV sync issues
  lib/media/segment_index.js
  test/media/segment_index_unit.js
Labels: type: bug, priority: P1

#4870 fix: Sync each segment against EXT-X-PROGRAM-DATE-TIME
  lib/hls/hls_parser.js
  lib/media/segment_index.js
  lib/media/segment_reference.js
Labels: type: bug, component: HLS, priority: P1

#4894 fix: Fix exception enabling captions on HLS
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P0

#4900 feat(i18n): add Occitan locale
  ui/locales/oc.json
Labels: type: enhancement, component: UI, priority: P4

#4906 chore: Factor out common code for layout tests
  test/test/util/layout_tests.js
  test/test/util/util.js
  test/ui/text_displayer_layout_unit.js
Labels: component: UI, component: captions/subtitles, component: WebVTT, component: tests

#4907 chore: Rename layout tests
  test/text/text_displayer_layout_unit.js
  test/text/ui_text_displayer_unit.js
Labels: component: UI, component: captions/subtitles, component: tests

#4909 test: Rewrite screenshot review tool
  test/test/assets/screenshots/review.html
Labels: component: UI, component: captions/subtitles, component: tests

#4845 feat(WebVTT): Add support to voice tag styles
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, priority: P2, component: WebVTT

#4911 test: Preserve filters when reloading the review page
  test/test/assets/screenshots/review.html
Labels: component: tests

#4915 fix: Fix WebVTT parser failure on REGION blocks
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P2, component: WebVTT

#4919 fix: Forbid MathML namespace in shaka.util.XmlUtils
  externs/mathml.js
  lib/util/xml_utils.js
  test/util/xml_utils_unit.js
Labels: type: bug, priority: P3

#4918 test: Reorganize screenshots in review tool
  test/test/assets/screenshots/review.html
Labels: component: tests

#4920 fix(WebVTT): Add support to &nbsp;, &lrm; and &rlm;
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P2, component: WebVTT

#4923 fix: Add mux.js to support.html
  support.html
Labels: type: bug, priority: P1

#4927 fix: Fix MediaCapabilities polyfill on Hisense
  lib/polyfill/media_capabilities.js
  lib/util/platform.js
Labels: type: bug, priority: P2

#4926 feat: Add ExpressPlay FairPlay util
  docs/tutorials/fairplay.md
  lib/util/fairplay_utils.js
Labels: type: enhancement, priority: P3, component: FairPlay

#4928 fix(HLS): Fix detection of WebVTT subtitles in HLS by extension
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#4922 fix(WebVTT): Fix voices with styles and support to multiple styles
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P2, component: WebVTT

#4931 feat: Add AC-3 detection in TS
  lib/util/ts_parser.js
Labels: type: enhancement, priority: P3

#4935 test: End-to-end WebVTT layout tests
  test/test/assets/screenshots/review.html
  test/text/web_vtt_layout_integration.js
Labels: component: tests

#4809 feat(HLS): Improve detection of basic info from Media Playlist
  lib/hls/hls_parser.js
  lib/util/mp4_box_parsers.js
  test/hls/hls_parser_unit.js
  test/util/mp4_box_parsers_unit.js
Labels: type: enhancement, component: HLS, priority: P2

#4932 feat(logs): Add extra logging for 3015 errors
  lib/media/media_source_engine.js
  lib/util/error.js
  test/media/media_source_engine_unit.js
Labels: type: enhancement, priority: P3

#4914 fix(DASH): Fix dynamic manifests from edgeware
  lib/dash/segment_template.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#4941 chore: Add text_utils.js
  build/types/core
  lib/text/simple_text_displayer.js
  lib/text/text_utils.js
  lib/text/web_vtt_generator.js
Labels: type: code health, priority: P2

#4942 fix(HLS): IMSC1 subtitles not working in a HLS stream
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#4623 feat(HLS): Add HLS support for non-sequence mode
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/manifest.js
  externs/shaka/offline.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/manifest_parser.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/util/id3_utils.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
  test/hls/hls_parser_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, component: HLS, priority: P2

#4849 feat(DASH): Add support for <dashif:Laurl>
  lib/dash/content_protection.js
  test/dash/dash_parser_content_protection_unit.js
Labels: type: enhancement, component: EME, priority: P3, component: DASH

#4952 feat(HLS): Improve Low Latency performance in HLS
  lib/media/streaming_engine.js
Labels: type: enhancement, component: HLS, priority: P1

#4953 fix(MCap): Remove robustness when robustness value is default
  lib/util/stream_utils.js
Labels: type: bug, platform: TV/STB, priority: P2

#4784 feat: Support Parallel Segment Fetching
  build/types/core
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  docs/tutorials/config.md
  externs/shaka/player.js
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
  test/media/segment_prefetch_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/fake_segment_prefetch.js
Labels: type: enhancement, priority: P2
