Repository shaka-project/shaka-player, pull requests merged in 2023-07, with the labels that each got.

#5384 fix: gap jumping when gap exists at start position
  lib/media/gap_jumping_controller.js
  lib/media/playhead.js
  lib/media/video_wrapper.js
Labels: type: bug, priority: P1

#5388 fix(DRM): broken keySystemsMapping due to multiple references of drmInfo
  lib/media/drm_engine.js
Labels: type: bug, component: EME, priority: P1

#5392 feat(Demo): Add Low Latency filter in demo page
  demo/common/assets.js
  demo/common/message_ids.js
  demo/locales/en.json
  demo/locales/source.json
  demo/search.js
Labels: type: enhancement, component: demo page, priority: P3

#5394 feat(DASH): Add support for service descriptions
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  test/dash/dash_parser_manifest_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P3, component: DASH

#5391 feat(DRM): use preferredKeySystems to reduce requestMediaKeySystemAccess() calls
  lib/media/drm_engine.js
  lib/util/stream_utils.js
  test/media/drm_engine_unit.js
  test/util/stream_utils_unit.js
Labels: type: enhancement, component: EME, priority: P3

#5439 fix: Fix exiting fullscreen on Safari
  lib/polyfill/orientation.js
Labels: type: bug
