Repository shaka-project/shaka-player, pull requests merged in 2023-08, with the labels that each got.

#5454 fix: Support fLaC and Opus codec strings in HLS
  lib/util/manifest_parser_utils.js
  lib/util/stream_utils.js
  test/hls/hls_parser_unit.js
  test/util/stream_utils_unit.js
Labels: type: bug, component: HLS, priority: P1

#5442 fix: Typing of PeriodCombiner.Period was incorrect
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug

#5452 fix: add MIME type for HTML5 tracks
  lib/util/stream_utils.js
Labels: type: bug

#5481 fix: gettting maxWidth and maxHeight for restrictToElementSize option
  lib/abr/simple_abr_manager.js
Labels: type: bug, priority: P1

#5464 fix: Default language to 'und' for native tracks
  lib/util/stream_utils.js
Labels: type: bug, priority: P1

#5400 feat: Abr improvement config
  AUTHORS
  CONTRIBUTORS
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/util/player_configuration.js
  test/abr/simple_abr_manager_unit.js
Labels: type: enhancement, priority: P3

#5485 feat(Demo): Add MSS Playready asset
  demo/common/assets.js
Labels: type: enhancement, component: demo page, priority: P3

#5484 feat: Add support for AC-3 and EC-3 audio in DVB streams
  lib/util/ts_parser.js
Labels: type: enhancement, priority: P3

#5486 feat(MSS): Fix MSS PlayReady support
  externs/isoboxer.js
  lib/mss/content_protection.js
  lib/transmuxer/mss_transmuxer.js
  test/mss/mss_parser_unit.js
  test/mss/mss_player_integration.js
Labels: type: enhancement, priority: P3, component: PlayReady, component: MSS

#5499 fix(WebVTT): Fix text-shadow in WebVTT not working
  lib/text/vtt_text_parser.js
Labels: type: bug, component: captions/subtitles, priority: P2, component: WebVTT

#5497 fix(UI): Disable right click on range elements
  ui/range_element.js
Labels: type: bug, component: UI, priority: P1

#5494 fix: Fix playRangeEnd does not work with HLS streams
  lib/player.js
Labels: type: bug, component: HLS, priority: P2

#5492 fix: Remove duplicate adaptation event before init
  lib/player.js
Labels: type: bug, priority: P2

#5501 feat: Parses a TFDT Box, with a loss of precision beyond 53 bits
  lib/cea/mp4_cea_parser.js
  lib/text/mp4_vtt_parser.js
Labels: type: bug, type: enhancement

#5510 feat(demo): Improve bug report button in demo
  demo/autoTemplate.txt
  demo/customWarning.txt
  demo/main.js
Labels: type: enhancement, component: demo page

#5500 feat(SRT): Support stylized payload in SRT format
  lib/text/srt_text_parser.js
  lib/text/vtt_text_parser.js
  test/text/srt_text_parser_unit.js
Labels: type: enhancement, component: captions/subtitles, priority: P4

#5491 fix(HLS): Fix external subtitles out of sync in HLS
  externs/shaka/manifest.js
  externs/shaka/offline.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/mss/mss_parser.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  test/media/adaptation_set_unit.js
  test/media/media_source_engine_unit.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
  test/test/util/offline_utils.js
  test/test/util/streaming_engine_util.js
Labels: type: bug, component: HLS, priority: P2

#5515 fix(HLS): Parse the correct codec for AVC and MP4A in HLS parser
  lib/hls/hls_parser.js
  lib/util/mp4_box_parsers.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#5518 docs: Update Label documentation
  ui/externs/ui.js
Labels: type: docs

#5519 feat(UI): Add PageUp and PageDown to UI seek bar
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI

#5521 fix(Demo): Show correctly external text in the Demo
  demo/main.js
Labels: type: bug, component: demo page, priority: P2

#5524 feat(ads): Add getPodIndex to CS and SS ads
  externs/ima.js
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/server_side_ad.js
  lib/text/simple_text_displayer.js
  test/test/util/fake_ad.js
Labels: type: enhancement, component: ads, priority: P3

#5525 feat: Make gap jump timer time configurable
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/media/gap_jumping_controller.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P2

#5522 chore(Demo): Update LCEVC assets
  demo/common/assets.js
Labels: component: demo page, priority: P2

#5527 fix(UI): Fix playback restarts in safari when click on seekbar end
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2, browser: Safari

#5533 fix: Remove sourcebuffer before create a new media source instance
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#5532 feat(WebVTT): Add support to auto position
  lib/text/vtt_text_parser.js
Labels: type: enhancement, priority: P3, component: WebVTT

#5530 feat(Ads): Disable custom playback on iOS 10+ browsers for CC
  externs/ima.js
  lib/ads/client_side_ad_manager.js
  test/ads/ad_manager_unit.js
Labels: type: enhancement, component: ads, priority: P4

#5531 feat(CEA): Add support to vertical position in CEA-608
  lib/cea/cea608_memory.js
  test/cea/cea608_memory_unit.js
  test/cea/cea_decoder_unit.js
Labels: type: enhancement, component: captions/subtitles, priority: P2

#5529 feat: Use shaka.text.Cue everywhere instead of shaka.extern.Cue
  externs/shaka/text.js
  lib/text/cue.js
  lib/text/lrc_text_parser.js
  lib/text/mp4_vtt_parser.js
  lib/text/sbv_text_parser.js
  lib/text/simple_text_displayer.js
  lib/text/ssa_text_parser.js
  lib/text/ui_text_displayer.js
  lib/text/vtt_text_parser.js
  test/test/util/ttml_utils.js
  test/text/cue_integration.js
  test/text/ui_text_displayer_unit.js
Labels: type: enhancement, type: code health, component: captions/subtitles, priority: P3

#5536 feat(Ads): Add control AdsRenderingSettings
  demo/main.js
  docs/tutorials/ad_monetization.md
  externs/ima.js
  externs/shaka/ads.js
  lib/ads/ad_manager.js
  lib/ads/client_side_ad_manager.js
  test/ads/ad_manager_unit.js
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#5537 chore(Demo): Move livesim URLs to livesim2
  demo/common/assets.js
Labels: component: demo page, priority: P2

#5539 test: Cache Babel output
  .github/workflows/selenium-lab-tests.yaml
  .gitignore
  karma.conf.js
  package-lock.json
  package.json
Labels: component: tests

#5545 fix: Orange set top box is incorrectly categorized as Apple
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, priority: P2

#5541 fix(Ads): Initialize correctly the IMA ads manager
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#5542 feat(Ads): Allow multiple calls to requestAds in CS
  lib/ads/client_side_ad_manager.js
  test/ads/ad_manager_unit.js
Labels: type: enhancement, component: ads, priority: P3

#5543 feat(Ads): Allow use a custom playhead tracker in CS
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/ima.js
  externs/shaka/player.js
  lib/ads/client_side_ad_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: ads, priority: P3

#5386 feat: Add TS transmuxer
  README.md
  build/types/transmuxer
  externs/shaka/codecs.js
  karma.conf.js
  lib/media/media_source_engine.js
  lib/mss/mss_parser.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/h264.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/mpeg_ts_transmuxer.js
  lib/transmuxer/transmuxer_engine.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/exp_golomb.js
  lib/util/mime_utils.js
  lib/util/mp4_generator.js
  lib/util/ts_parser.js
  shaka-player.uncompiled.js
  test/media/drm_engine_unit.js
  test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0000.ts
  test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0001.ts
  test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0002.ts
  test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0003.ts
  test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0004.ts
  test/test/assets/hls-ts-ac3/ChID_voices_6ch_640kbps_dd_sub_0005.ts
  test/test/assets/hls-ts-ac3/prog_index.m3u8
  test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0000.ts
  test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0001.ts
  test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0002.ts
  test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0003.ts
  test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0004.ts
  test/test/assets/hls-ts-ec3/ChID_voices_6ch_256kbps_ddp_sub_0005.ts
  test/test/assets/hls-ts-ec3/prog_index.m3u8
  test/test/assets/hls-ts-mp3/manifest.m3u8
  test/test/assets/hls-ts-mp3/media_w239891843_0.ts
  test/test/assets/hls-ts-mp3/media_w239891843_1.ts
  test/test/assets/hls-ts-mp3/media_w239891843_2.ts
  test/test/assets/hls-ts-mp3/media_w239891843_3.ts
  test/transmuxer/transmuxer_engine_integration.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, component: HLS, priority: P3

#5555 feat: Allow generate muxed content with Mp4Generator
  lib/mss/mss_parser.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/mp4_generator.js
Labels: type: enhancement, priority: P3

#5557 feat: Add AAC silent frame getter
  lib/transmuxer/adts.js
Labels: type: enhancement, priority: P3

#5553 test: Improve transmuxer tests
  test/test/util/ui_utils.js
  test/transmuxer/transmuxer_integration.js
Labels: type: code health, priority: P3, component: tests

#5561 feat: add feature-flag to insert fake encryption in init segments on broken platforms
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/util/player_configuration.js
  test/media/media_source_engine_unit.js
Labels: type: enhancement, priority: P3

#5566 fix: Fix Mp4Generator
  lib/util/mp4_generator.js
Labels: type: bug, priority: P2

#5568 fix: Prevent codecs override in the transmuxer
  lib/mss/mss_parser.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/mp4_generator.js
Labels: type: bug, priority: P2

#5569 test: Fix MSS PlayReady test
  test/mss/mss_player_integration.js
Labels: priority: P2, component: tests

#5570 test: Fix "extracts ID3 metadata from AAC" tests
  test/media/media_source_engine_integration.js
Labels: priority: P2, component: tests
