Repository shaka-project/shaka-player, pull requests merged in 2023-03, with the labels that each got.

#5047 fix: Fire correctly MIN_HDCP_VERSION_NOT_MATCH error
  lib/media/drm_engine.js
Labels: type: bug, component: EME, priority: P2

#5045 feat(ads): Dispatch a player event for client-side ad errors
  lib/ads/ad_manager.js
  lib/ads/client_side_ad_manager.js
Labels: type: enhancement, component: ads, priority: P2

#5050 fix: Simplify logging code for compatibility with webpack-terser-plugin
  lib/debug/log.js
Labels: type: code health

#4973 fix: Tizen video error fixed by checking the extended MIME type
  lib/polyfill/media_capabilities.js
Labels: type: bug, priority: P2, platform: Tizen

#5063 fix(Tizen): Fix exceptions thrown from logging methods
  lib/debug/log.js
Labels: type: bug, priority: P1, platform: Tizen

#5065 fix(demo): Fix native controls pointer events stolen by LCEVC canvas
  ui/less/containers.less
Labels: type: bug, component: demo page

#5071 fix: prevent bad calls to MediaSource.endOfStream
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#5082 docs: Remove next links from tutorials
  docs/tutorials/a11y.md
  docs/tutorials/ad_monetization.md
  docs/tutorials/basic-usage.md
  docs/tutorials/config.md
  docs/tutorials/debugging.md
  docs/tutorials/drm-config.md
  docs/tutorials/license-server-auth.md
  docs/tutorials/license-wrapping.md
  docs/tutorials/network-and-buffering-config.md
  docs/tutorials/ui-customization.md
  docs/tutorials/ui.md
  docs/tutorials/welcome.md
Labels: type: docs

#5066 fix(HLS): preserve discontinuitySequence in SegmentIndex#fit
  lib/media/segment_index.js
Labels: type: bug, component: HLS, priority: P2

#5091 fix: Fix fetch plugin with old implementations
  lib/net/http_fetch_plugin.js
Labels: type: bug, priority: P0, platform: iOS

#5085 feat(Ads): Add ads config
  externs/shaka/ads.js
  externs/shaka/player.js
  lib/ads/ad_manager.js
  lib/ads/client_side_ad_manager.js
  lib/ads/server_side_ad_manager.js
  lib/player.js
  lib/util/player_configuration.js
  test/ads/ad_manager_unit.js
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#5069 fix: mitigate uncaught type error in media_source_engine
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#5072 fix: missing CMCD params in some http requests
  demo/common/asset.js
  docs/tutorials/ad_monetization.md
  docs/tutorials/application-level-redirects.md
  docs/tutorials/fairplay.md
  docs/tutorials/license-server-auth.md
  docs/tutorials/license-wrapping.md
  externs/shaka/manifest_parser.js
  externs/shaka/net.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  lib/net/networking_engine.js
  lib/offline/storage.js
  lib/player.js
  lib/util/cmcd_manager.js
  lib/util/fairplay_utils.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/hls/hls_live_unit.js
  test/media/drm_engine_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/util/fake_networking_engine.js
  test/test/util/streaming_engine_util.js
  test/util/cmcd_manager_unit.js
Labels: type: bug, priority: P2

#5079 fix(HLS): don't do sequence mode workaround unless there's a text stream
  lib/media/media_source_engine.js
  test/media/media_source_engine_unit.js
Labels: type: bug, component: HLS, priority: P2

#5060 test: clear support map between tests
  test/polyfill/media_capabilities_unit.js
Labels: priority: P2, component: tests

#5100 feat(utils): Export shaka.util.StreamUtils.meetsRestrictions
  AUTHORS
  CONTRIBUTORS
  lib/util/stream_utils.js
Labels: type: enhancement, priority: P4

#5102 fix(HLS): support discontinuities in segments mode
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_unit.js
  test/test/util/fake_media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#5103 feat(HLS): Add HLS config to ignore manifest timestamps when in segments mode
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/offline/manifest_converter.js
  lib/util/player_configuration.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, component: HLS, priority: P3

#5113 fix: Add missing AdvancedRequestType in some requests
  lib/hls/hls_parser.js
Labels: type: bug, priority: P2

#5114 fix: Fix missing originalUri in response filters
  externs/shaka/net.js
  test/media/streaming_engine_unit.js
  test/net/networking_engine_unit.js
Labels: type: bug, priority: P2

#5117 fix(HLS): Adding support for DTS Express in HLS fMP4 (#5112)
  AUTHORS
  CONTRIBUTORS
  lib/media/media_source_engine.js
  lib/util/manifest_parser_utils.js
Labels: type: bug, component: HLS, priority: P2

#5118 fix: stream property of request context obfuscated in production builds
  externs/shaka/net.js
  lib/hls/hls_parser.js
  lib/net/networking_engine.js
  lib/util/cmcd_manager.js
  lib/util/fairplay_utils.js
  test/test/util/fake_networking_engine.js
Labels: type: bug, priority: P1

#5119 fix: cmcd not applying configuration changes
  lib/player.js
  lib/util/cmcd_manager.js
Labels: type: bug, priority: P1

#5002 feat(MSS): Add support for Microsoft Smooth Streaming (VOD only)
  LICENSE
  README.md
  build/misspellings.txt
  build/types/manifests
  build/types/mss
  demo/common/assets.js
  demo/common/message_ids.js
  demo/config.js
  demo/index.html
  demo/locales/en.json
  demo/locales/source.json
  demo/main.js
  demo/search.js
  demo/service_worker.js
  docs/tutorials/upgrade.md
  externs/isoboxer.js
  externs/shaka/manifest.js
  externs/shaka/player.js
  externs/shaka/transmuxer.js
  karma.conf.js
  lib/dependencies/all.js
  lib/media/manifest_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/mss/content_protection.js
  lib/mss/mss_parser.js
  lib/mss/mss_utils.js
  lib/transmuxer/mss_transmuxer.js
  lib/util/error.js
  lib/util/player_configuration.js
  lib/util/xml_utils.js
  package-lock.json
  package.json
  shaka-player.uncompiled.js
  test/cast/cast_utils_unit.js
  test/demo/demo_unit.js
  test/media/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/mss/mss_parser_content_protection_unit.js
  test/mss/mss_parser_unit.js
  test/mss/mss_player_integration.js
  test/test/util/mss_parser_util.js
Labels: type: enhancement, priority: P4, component: MSS

#4945 fix: exclude "future" segments from presentation timeline auto correct drift calculations
  lib/media/presentation_timeline.js
  test/dash/dash_parser_live_unit.js
Labels: type: bug, priority: P1, component: DASH

#5123 test: add test for ContentWorkarounds
  test/media/content_workarounds_unit.js
Labels: component: tests

#5120 fix(HLS): Report HLS playlist updates as media playlist in network filters
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P2
