Repository shaka-project/shaka-player, pull requests merged in 2023-04, with the labels that each got.

#5127 feat: Add a Mp4Generator
  build/types/core
  build/types/mss
  lib/mss/mss_parser.js
  lib/mss/mss_utils.js
  lib/util/mp4_generator.js
Labels: type: enhancement, priority: P3

#5153 fix(ads): Fix ads starting muted behavior
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads

#5149 fix: prevent memory leak in SimpleAbrManager while destroying
  externs/network_information.js
  externs/shaka/abr_manager.js
  lib/abr/simple_abr_manager.js
  lib/player.js
  test/player_unit.js
  test/test/util/simple_fakes.js
Labels: type: bug, priority: P2

#5155 fix(Ads): Fix SS configure
  lib/ads/ad_manager.js
Labels: type: bug, component: ads, priority: P2

#5154 fix: Fix selectVariantsByLabel using src=
  lib/player.js
Labels: type: bug, priority: P2, browser: Safari

#5129 fix: Fix race that allows multiple text streams to be loaded
  CONTRIBUTORS
  lib/media/streaming_engine.js
  test/player_integration.js
  test/test/assets/text-clip-alt.vtt
Labels: type: bug, component: captions/subtitles, priority: P2

#5057 fix: Fix temporarily disable streams on network error
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/periods.js
  lib/util/stream_utils.js
  test/cast/cast_utils_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/player_unit.js
  test/test/util/streaming_engine_util.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P2

#5156 fix(HLS): Fix support of fragmented WebVTT
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P2

#5157 fix: check for existance of addEventListener and removeEventListener in navigator.connection before using them
  lib/abr/simple_abr_manager.js
Labels: type: bug, priority: P2

#5110 fix(DASH): Fix seeking on multiperiod content after variant change
  lib/dash/dash_parser.js
  lib/util/periods.js
Labels: type: bug, priority: P2, component: DASH

#5159 chore: Fix unreleased HLS playback regression
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#5160 fix: Fix handling of CC when switching between codecs
  lib/media/media_source_engine.js
  lib/text/text_engine.js
Labels: type: bug, component: captions/subtitles, priority: P2

#4461 feat: allow reuse of persistent license sessions
  docs/tutorials/drm-config.md
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/player.js
  lib/util/error.js
  lib/util/player_configuration.js
  test/cast/cast_utils_unit.js
  test/demo/demo_unit.js
  test/media/drm_engine_unit.js
  test/offline/storage_integration.js
Labels: type: enhancement, component: EME, priority: P2

#5147 test: Add transmuxer integration tests
  test/transmuxer/transmuxer_integration.js
Labels: component: tests

#5167 fix: `config.streaming.preferNativeHls` only applies to HLS streams
  lib/player.js
  lib/util/mime_utils.js
  test/player_unit.js
  test/test/util/fake_drm_engine.js
  test/test/util/simple_fakes.js
  test/util/mime_utils_unit.js
Labels: type: bug, priority: P2

#5170 docs: update `config.drm.initDataTransform` documentation
  docs/tutorials/fairplay.md
  externs/shaka/player.js
Labels: type: docs

#5180 fix(net): Fix HEAD requests in new Chromium
  lib/net/http_fetch_plugin.js
Labels: type: bug, priority: P0, browser: Chrome, browser: Edge

#5186 test: Drop Axinom DRM servers from tests
  test/media/drm_engine_integration.js
  test/test/util/test_scheme.js
Labels: component: tests

#5138 feat: Raise fatal error on linear manifest request update failure
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
  test/dash/dash_parser_live_unit.js
  test/demo/demo_unit.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, priority: P3

#5193 chore: Update maintained branches
  maintained-branches.md
Labels: type: docs

#5198 fix: unnecessary parsing of in-band pssh when pssh is in the manifest
  lib/media/drm_engine.js
Labels: type: bug, platform: Xbox

#5185 feat: Allow generate segments with Mp4Generator
  lib/mss/mss_parser.js
  lib/util/mp4_generator.js
Labels: type: enhancement

#5196 fix: Fix buffering on the end of MSS streams
  lib/mss/mss_parser.js
Labels: type: bug, priority: P2, component: MSS

#5061 feat(dash): Improve DASH SegmentTemplate performance with on-demand segment references
  lib/dash/mpd_utils.js
  lib/dash/segment_template.js
  lib/media/presentation_timeline.js
  lib/media/segment_index.js
  test/dash/dash_parser_segment_template_unit.js
  test/media/presentation_timeline_unit.js
Labels: type: enhancement, priority: P2, component: DASH

#5195 feat: Convert CEA parsers to plugins
  AUTHORS
  CONTRIBUTORS
  build/types/cea
  build/types/complete
  build/types/core
  externs/shaka/cea.js
  lib/cea/cea608_data_channel.js
  lib/cea/cea608_memory.js
  lib/cea/cea708_service.js
  lib/cea/cea708_window.js
  lib/cea/cea_decoder.js
  lib/cea/cea_utils.js
  lib/cea/dummy_caption_decoder.js
  lib/cea/dummy_cea_parser.js
  lib/cea/i_caption_decoder.js
  lib/cea/i_cea_parser.js
  lib/cea/mp4_cea_parser.js
  lib/cea/ts_cea_parser.js
  lib/media/closed_caption_parser.js
  lib/media/media_source_engine.js
  lib/text/text_engine.js
  shaka-player.uncompiled.js
  test/text/text_engine_unit.js
Labels: type: enhancement, priority: P3
