Repository shaka-project/shaka-player, pull requests merged in 2023-02, with the labels that each got.

#4954 feat(webvtt): webvtt colors output
  lib/text/cue.js
  lib/text/text_utils.js
  test/text/vtt_text_parser_unit.js
  test/text/web_vtt_generator_unit.js
Labels: type: enhancement, priority: P2, component: WebVTT

#4960 fix(WebVTT): Tags in the WebVTT subtitle are not parsed
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P1, component: WebVTT

#4962 fix: Failed to set 'currentTime' property on 'HTMLMediaElement' on a Hisense TV
  lib/media/video_wrapper.js
Labels: type: bug, platform: TV/STB, priority: P2

#4963 feat(UI): Allow customizate FullScreen element
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#4971 fix: DrmEngine exception thrown when using FairPlay
  lib/media/drm_engine.js
Labels: type: bug, priority: P1

#4978 fix: Caption can not turn off at iOS Safari
  lib/player.js
Labels: type: bug, component: captions/subtitles, priority: P2, platform: iOS

#4979 fix: Prevent content from being restarted after Postroll ads
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#4977 fix(Demo): Allow manifest type for DAI custom assets
  demo/common/asset.js
  demo/common/assets.js
  demo/common/message_ids.js
  demo/custom.js
  demo/locales/en.json
  demo/locales/source.json
  demo/main.js
  externs/ima.js
Labels: type: bug, component: demo page, component: ads, priority: P2

#4982 feat(HLS): Add support to HLS-AES128 low latency
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P1

#4984 fix: Increase IndexedDB timeout
  lib/offline/indexeddb/storage_mechanism.js
Labels: type: bug, priority: P3, browser: Firefox, component: offline

#2394 feat: Allow VTT files with erroneous linebreaks
  lib/text/vtt_text_parser.js
  lib/util/text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, priority: P3, component: WebVTT

#4969 feat: Add support for Document Picture-in-Picture
  demo/close_button.js
  demo/main.js
  docs/tutorials/ui-customization.md
  externs/pictureinpicture.js
  ui/pip_button.js
Labels: type: enhancement, component: UI, priority: P3

#4995 fix(ads): Fix VMAP ads stay muted on muted autoplay
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#4999 fix: Explicitly specify @externs in transmuxer externs.
  externs/shaka/transmuxer.js
Labels: component: build system

#4983 docs: add error handling tutorial
  docs/tutorials/errors.md
Labels: type: docs, priority: P3

#5016 fix(Ads): Fix CS volume ad
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#5017 fix(Ads): Fix usage of EventManager on CS
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#4993 ci: Fix workflow to update screenshots
  .github/workflows/build-and-test.yaml
  .github/workflows/selenium-lab-tests.yaml
  .github/workflows/update-screenshots.yaml
Labels: type: CI

#5006 feat(net): Added advanced type to filters
  demo/common/asset.js
  docs/tutorials/ad_monetization.md
  docs/tutorials/application-level-redirects.md
  docs/tutorials/fairplay.md
  docs/tutorials/license-server-auth.md
  docs/tutorials/license-wrapping.md
  externs/shaka/net.js
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_template.js
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  lib/net/networking_engine.js
  lib/util/fairplay_utils.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/media/drm_engine_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/util/fake_networking_engine.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P2

#5018 docs: Add Widevine Service Certificate tutorial
  docs/tutorials/fairplay.md
  docs/tutorials/index.json
  docs/tutorials/widevine-service-certs.md
Labels: type: docs

#5021 feat: Add getManifestType method
  lib/cast/cast_utils.js
  lib/player.js
Labels: type: enhancement, priority: P3

#5034 fix(HLS): Add `.tsa` and .`tsv` file extensions as valid MPEG2-TS.
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#5040 chore: Fix style of MuxjsTransmuxer
  lib/transmuxer/muxjs_transmuxer.js
Labels: priority: P2

#5043 fix: Reject TS content on Edge
  lib/polyfill/mediasource.js
Labels: type: bug, priority: P1, browser: Edge

#5044 chore: the implementation of abort() on SourceBuffer in Safari, now works
  lib/polyfill/mediasource.js
Labels: priority: P2, browser: Safari

#5012 fix: Fallback to isTypeSupported when cast namespace is undefined
  lib/polyfill/media_capabilities.js
  test/polyfill/media_capabilities_unit.js
Labels: type: bug, platform: TV/STB, priority: P1
