Repository shaka-project/shaka-player, pull requests merged in 2023-10, with the labels that each got.

#5706 docs: Fix offline tutorial
  docs/tutorials/offline.md
Labels: type: bug, type: docs, priority: P1

#5695 feat: Add KeyStatusChanged and UpdateState events
  lib/player.js
  lib/util/fake_event.js
Labels: type: enhancement, priority: P3

#5705 fix(HLS): Skip segments without duration and without partial segments
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#5708 fix(Demo): Fix url of "Low Latency HLS Live" asset
  demo/common/assets.js
Labels: type: bug, component: demo page

#5707 fix(DASH): Fix bigint implementation
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#5712 fix: Fix unreleased stack overflow on statechanged
  lib/player.js
  lib/util/state_history.js
  test/cast/cast_receiver_integration.js
Labels: type: bug, priority: P1

#5459 feat: Migration of LCEVC DIL (Decoder Integration Layer) to LCEVC Dec (Decoder)
  README.md
  build/types/lcevc
  demo/common/assets.js
  demo/index.html
  docs/design/lcevc-integration.md
  docs/tutorials/index.json
  docs/tutorials/lcevc.md
  externs/lcevc.js
  lib/lcevc/lcevc_dec.js
  lib/lcevc/lcevc_dil.js
  lib/media/media_source_engine.js
  lib/player.js
  package-lock.json
  package.json
  test/player_unit.js
  test/test/util/fake_media_source_engine.js
Labels: type: enhancement, priority: P3

#5714 feat: Add getBandwidthEstimate to the player interface for custom manifest parser
  externs/shaka/manifest_parser.js
  lib/offline/storage.js
  lib/player.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
Labels: type: enhancement, priority: P3

#5715 test: Stop correctly DASH parser
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/test/util/dash_parser_util.js
Labels: type: bug, priority: P1, component: tests

#5716 fix: seeking in segment timeline returns incorrect index
  lib/media/segment_index.js
  test/dash/dash_parser_segment_template_unit.js
Labels: type: bug, priority: P1, component: DASH

#5470 feat: Enable codec switching
  build/types/core
  demo/config.js
  externs/shaka/player.js
  karma.conf.js
  lib/config/codec_switching_strategy.js
  lib/media/adaptation_set.js
  lib/media/adaptation_set_criteria.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/platform.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/codec_switching/codec_switching_integration.js
  test/media/adaptation_set_criteria_unit.js
  test/media/media_source_engine_unit.js
  test/offline/storage_integration.js
  test/player_unit.js
  test/test/assets/dash-multi-codec/audio_en_2c_128k_aac.mp4
  test/test/assets/dash-multi-codec/audio_es_2c_64k_opus.webm
  test/test/assets/dash-multi-codec/dash.mpd
  test/test/assets/dash-multi-codec/video_144p_108k_h264.mp4
  test/test/util/fake_media_source_engine.js
  test/test/util/manifest_generator.js
  test/ui/ui_unit.js
  test/util/stream_utils_unit.js
Labels: type: enhancement, priority: P3

#5717 chore: Update README
  README.md
Labels: type: docs

#5718 docs: Update docs for v4.5 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#5696 feat: Stop setting playbackRate to 0 to control buffering state
  lib/media/play_rate_controller.js
  lib/media/stall_detector.js
  lib/player.js
  test/media/play_rate_controller_unit.js
  test/player_src_equals_integration.js
Labels: type: enhancement, priority: P2

#5731 fix: For text content is not necessary codec switching
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1

#5732 fix(HLS): Fix init segment when EXT-X-MAP is preceded by EXT-X-BYTERANGE
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#5734 chore: Switch to new issues email
  .github/ISSUE_TEMPLATE/bug_report.md
  CODE_OF_CONDUCT.md
Labels: type: docs

#5722 fix(HLS): Fix url management in HLS
  lib/hls/hls_classes.js
  lib/hls/hls_parser.js
  lib/hls/hls_utils.js
  lib/hls/manifest_text_parser.js
  test/hls/manifest_text_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#5740 chore(HLS): Reduce complexity of HLS parser
  build/types/core
  lib/hls/hls_parser.js
  lib/util/segment_utils.js
Labels: type: code health, component: HLS, priority: P2

#5739 chore(DASH): Update DASH URL management to allow Content Steering in the future
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
Labels: priority: P2, component: DASH

#5750 docs: Add missing text and manifest parsers
  docs/tutorials/plugins.md
Labels: type: docs, priority: P2

#5751 fix(UI): Fix text selector when the trackLabelFormat is set to LABEL
  ui/language_utils.js
Labels: type: bug, component: UI, priority: P2

#5753 feat(UI): Display frame rates in the quality selector
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#5756 feat(net): Add shaka.net.NetworkingUtils
  build/types/core
  lib/media/manifest_parser.js
  lib/net/networking_utils.js
  lib/player.js
  test/net/networking_utils_unit.js
Labels: type: enhancement, priority: P3

#5683 feat: Use ManagedMediaSource when available
  externs/managedmediasource.js
  lib/media/media_source_capabilities.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/util/platform.js
  test/test/util/fake_media_source_engine.js
Labels: type: enhancement, priority: P3

#5736 fix(DASH): Fix manifest update time for LL-DASH
  externs/shaka/manifest_parser.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/offline_manifest_parser.js
  lib/player.js
  test/offline/storage_integration.js
  test/test/util/test_scheme.js
Labels: type: bug, priority: P1, component: DASH

#5763 fix(DASH): Fix manifest update time for Live manifests
  lib/dash/dash_parser.js
Labels: type: bug, priority: P1, component: DASH

#5764 fix: Dispatch streamDataCallback correctly in SegmentPrefetchOperation
  lib/media/segment_prefetch.js
Labels: type: bug, priority: P1

#5773 perf(manifest): avoid unnecessary looping in uri resolver
  lib/util/manifest_parser_utils.js
Labels: type: performance, priority: P1

#5774 perf(DASH): reduce looping and remove chaining awaits in period
  lib/util/periods.js
Labels: type: performance, priority: P1, component: DASH

#5777 perf(Xbox): drop incompatible variants for XBOX early
  lib/util/stream_utils.js
Labels: type: performance, priority: P1, platform: Xbox

#5783 feat(thumbnails): Add Player.getAllThumbnails
  lib/player.js
  test/cast/cast_utils_unit.js
  test/player_integration.js
  test/player_unit.js
Labels: type: enhancement, priority: P2

#5772 feat(HLS): Add new config to get codecs from media segment for playlists without CODECS attribute
  AUTHORS
  CONTRIBUTORS
  demo/config.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5768 perf(dash): improve readability and reduce number of loops in dash parser
  lib/dash/dash_parser.js
Labels: type: performance, priority: P1, component: DASH

#5786 chore(DASH): move repetitive code to method, avoid full iteration if possible
  lib/dash/mpd_utils.js
Labels: priority: P2, component: DASH

#5775 perf: simplify and improve performance of parsing initData when deduping
  lib/media/drm_engine.js
Labels: type: performance, priority: P1

#5788 test: Update test with invalid initData.
  lib/media/drm_engine.js
  test/media/drm_engine_unit.js
Labels: type: code health, component: tests

#5791 perf(utils): use WeakSet to track object references
  AUTHORS
  CONTRIBUTORS
  lib/util/object_utils.js
Labels: type: performance, priority: P1

#5805 fix: Allow parseXmlString when createNodeIterator is not available
  lib/util/xml_utils.js
Labels: type: bug, priority: P3

#5800 fix: Fix chooseCodecsAndFilterManifest for some HLS manifest
  lib/hls/hls_parser.js
  lib/media/adaptation_set.js
  lib/media/adaptation_set_criteria.js
  lib/player.js
  lib/util/stream_utils.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: bug, priority: P1

#5801 feat(HLS): Add support for QUERYPARAM variable type in #EXT-X-DEFINE
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
  third_party/closure-uri/uri.js
Labels: type: enhancement, component: HLS, priority: P3

#5803 docs(Ads): Add AWS Elemental MediaTailor tutorial
  docs/tutorials/ad_monetization.md
Labels: type: docs, component: ads, priority: P1

#5807 fix(WebVTT): Fix wrong writing-mode in nested cues
  lib/text/vtt_text_parser.js
Labels: type: bug, priority: P2, component: WebVTT

#5789 perf: Improve transmuxer performance
  lib/transmuxer/h264.js
  lib/transmuxer/h265.js
  lib/util/mp4_generator.js
Labels: type: performance, priority: P1

#5790 fix: Fix converts legacy avc1 codec strings on transmuxer
  lib/transmuxer/ts_transmuxer.js
  test/transmuxer/transmuxer_engine_integration.js
Labels: type: bug, priority: P1

#5813 chore: Add AC-4 to probeSupport
  lib/media/media_source_engine.js
Labels: priority: P3

#5802 feat: Add thumbnails support in src=
  demo/common/assets.js
  lib/player.js
  lib/util/error.js
  test/player_src_equals_integration.js
Labels: type: enhancement, priority: P4

#5806 feat: Add a stub text display class (#5804)
  build/types/core
  lib/player.js
  lib/text/stub_text_displayer.js
Labels: type: enhancement, priority: P4

#5811 feat(HLS): Build closed captions metadata for media playlist on-the-fly.
  build/types/core
  externs/shaka/cea.js
  externs/shaka/manifest.js
  externs/shaka/offline.js
  lib/cea/cea_decoder.js
  lib/cea/dummy_caption_decoder.js
  lib/hls/hls_parser.js
  lib/media/closed_caption_parser.js
  lib/media/segment_utils.js
Labels: type: enhancement, component: HLS, component: captions/subtitles, priority: P4

#5809 feat(HLS): Add support for REQ-VIDEO-LAYOUT
  demo/config.js
  externs/shaka/manifest.js
  externs/shaka/offline.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/adaptation_set_criteria.js
  lib/mss/mss_parser.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/hls/hls_parser_unit.js
  test/media/adaptation_set_criteria_unit.js
  test/offline/manifest_convert_unit.js
  test/offline/storage_integration.js
  test/player_unit.js
  test/test/util/manifest_generator.js
  ui/resolution_selection.js
Labels: type: enhancement, component: HLS, priority: P3

#5798 chore(Demo): Allow add custom MediaTailor assets
  demo/custom.js
Labels: component: demo page, component: ads

#5817 fix: Fix chooseCodecsAndFilterManifest for similar frameRate
  lib/util/stream_utils.js
Labels: type: bug, priority: P1

#5820 feat: Improve latency in LL DASH streams
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3

#5819 fix(HLS): Fix kind detection for 'captions' text tracks
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#5823 fix(DASH): Handle minimumUpdatePeriod=0 with urn:mpeg:dash:event:2012 (EMSG)
  lib/dash/dash_parser.js
  test/dash/dash_parser_live_unit.js
Labels: type: bug, priority: P2, component: DASH

#5825 feat: Allow prefetch init segments
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  test/test/util/fake_segment_prefetch.js
Labels: type: enhancement, priority: P3

#5822 feat: Add partial info to shaka.media.SegmentReference
  lib/media/segment_reference.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, priority: P3

#5796 chore(Demo): Add extra chapter functionality
  demo/common/asset.js
  demo/common/assets.js
  demo/main.js
Labels: component: demo page

#5816 feat(UI): Bucketize resolution names in the UI
  test/ui/ui_integration.js
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#5794 chore(Demo): Remove HLS tab and add extra tracks tab on custom assets
  demo/common/asset.js
  demo/common/assets.js
  demo/custom.js
Labels: component: demo page

#5793 fix(UI): Console error on remote.cancelwatchavailability() method in remote playback feature
  ui/remote_button.js
Labels: type: bug, component: UI, priority: P1

#5828 test: Fix asset of EC3 test
  test/transmuxer/transmuxer_integration.js
Labels: priority: P1, component: tests

#5830 fix: Fix crash while playing HLS AES 128 streams
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#5831 fix: Fix incompatible codec is selected in Windows Edge for Widevine
  lib/offline/storage.js
  lib/player.js
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P1

#5833 fix(hisense): set stallSkip to 0 for HiSense devices
  lib/util/player_configuration.js
Labels: type: bug, priority: P2

#5752 chore: Remove state engine
  build/types/core
  demo/main.js
  docs/tutorials/basic-usage.md
  docs/tutorials/errors.md
  docs/tutorials/offline.md
  docs/tutorials/ui.md
  lib/cast/cast_receiver.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/manifest_parser.js
  lib/media/media_source_engine.js
  lib/mss/mss_parser.js
  lib/offline/storage.js
  lib/player.js
  lib/routing/node.js
  lib/routing/payload.js
  lib/routing/walker.js
  lib/util/fake_event.js
  lib/util/mutex.js
  shaka-player.uncompiled.js
  test/ads/ad_manager_unit.js
  test/cast/cast_receiver_integration.js
  test/cast/cast_utils_unit.js
  test/codec_switching/codec_switching_integration.js
  test/dash/dash_parser_integration.js
  test/mss/mss_player_integration.js
  test/offline/offline_integration.js
  test/offline/storage_integration.js
  test/player_external.js
  test/player_integration.js
  test/player_load_graph_integration.js
  test/player_src_equals_external.js
  test/player_src_equals_integration.js
  test/player_unit.js
  test/routing/walker_unit.js
  test/test/util/ui_utils.js
  test/text/text_displayer_layout_unit.js
  test/transmuxer/transmuxer_integration.js
  test/ui/ad_ui_unit.js
  test/ui/ui_customization_unit.js
  test/ui/ui_integration.js
  test/ui/ui_unit.js
  ui/ui.js
Labels: type: code health

#5835 fix: Fix bug with live start time
  lib/player.js
Labels: type: bug, priority: P1

#5837 perf(DASH): PeriodCombiner optimisations
  lib/util/periods.js
Labels: type: performance, priority: P1, component: DASH

#5838 fix: ban new Uint16Array(buffer)
  build/conformance.textproto
  lib/util/buffer_utils.js
  lib/util/fairplay_utils.js
  test/util/buffer_utils_unit.js
Labels: type: bug, priority: P1

#5841 docs: fix await keyword for attach method
  docs/tutorials/basic-usage.md
Labels: type: docs

#5840 fix(HLS): Fix accessibilityPurpose detection
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2
