Repository shaka-project/shaka-player, pull requests merged in 2023-12, with the labels that each got.

#5964 fix(HLS): Provide a fallback to GET request when HEAD request fails
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#5963 feat: Add config to prefer spatial audio
  demo/config.js
  externs/shaka/player.js
  lib/media/adaptation_set_criteria.js
  lib/player.js
  lib/util/player_configuration.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: enhancement, priority: P3

#5950 feat(DASH): Handle mixed-codec variants.
  README.md
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/util/mime_utils.js
  lib/util/periods.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/util.js
  test/util/stream_utils_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#5969 chore: Remove unnecessary hints for the compiler and add missing requires
  demo/common/asset.js
  demo/common/assets.js
  lib/ads/client_side_ad_manager.js
  lib/ads/media_tailor_ad_manager.js
  lib/ads/server_side_ad_manager.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/text/simple_text_displayer.js
  test/test/util/layout_tests.js
  test/text/simple_text_displayer_unit.js
Labels: type: code health, priority: P3

#5970 fix: Fix color detection in text utils
  lib/text/simple_text_displayer.js
  lib/text/text_utils.js
  lib/text/web_vtt_generator.js
  test/text/web_vtt_generator_unit.js
Labels: type: bug, priority: P2

#5976 test: Fix Edge versions to skip
  test/transmuxer/transmuxer_integration.js
Labels: priority: P1, component: tests

#5975 test: Update screenshots
  test/test/assets/screenshots/chrome-Linux/text-displayer-ui-region-position.png
  test/test/assets/screenshots/chrome-Linux/webvtt-native-align-end-long.png
  test/test/assets/screenshots/chrome-Linux/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/chrome-Linux/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/chrome-Linux/webvtt-ui-escaped-entities.png
  test/test/assets/screenshots/chrome-Linux/webvtt-ui-size-50.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-ui-region-position.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-end-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-ui-escaped-entities.png
  test/test/assets/screenshots/chrome-Mac/webvtt-ui-size-50.png
  test/test/assets/screenshots/chrome-Windows/text-displayer-ui-region-position.png
  test/test/assets/screenshots/chrome-Windows/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/chrome-Windows/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/chrome-Windows/webvtt-ui-escaped-entities.png
  test/test/assets/screenshots/chrome-Windows/webvtt-ui-size-50.png
  test/test/assets/screenshots/msedge-Linux/text-displayer-ui-region-position.png
  test/test/assets/screenshots/msedge-Linux/webvtt-native-align-end-long.png
  test/test/assets/screenshots/msedge-Linux/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/msedge-Linux/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/msedge-Linux/webvtt-ui-escaped-entities.png
  test/test/assets/screenshots/msedge-Linux/webvtt-ui-size-50.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-ui-region-position.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-end-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-ui-escaped-entities.png
  test/test/assets/screenshots/msedge-Mac/webvtt-ui-size-50.png
  test/test/assets/screenshots/msedge-Windows/text-displayer-ui-region-position.png
  test/test/assets/screenshots/msedge-Windows/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/msedge-Windows/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/msedge-Windows/webvtt-ui-escaped-entities.png
  test/test/assets/screenshots/msedge-Windows/webvtt-ui-size-50.png
Labels: priority: P1, component: tests

#5960 docs: Update docs for v4.7 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#5983 test: Add test for frameRate restriction
  test/player_unit.js
Labels: type: code health, priority: P3, component: tests

#5985 fix: Fix transmuxer when some PES has the same pts and dts value
  lib/util/ts_parser.js
Labels: type: bug, component: HLS, priority: P2

#5984 fix(HLS): Fix variant synchronization in HLS after selectVariantTrack
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2

#5981 fix(UI): Fix keyboard navigation of volume bar on Firefox
  ui/volume_bar.js
Labels: type: bug, component: UI, type: accessibility, priority: P3, browser: Firefox

#5982 fix: Fix liveLatency in stats
  lib/player.js
Labels: type: bug, priority: P2

#5986 fix: Provide a fallback to GET request when HEAD request fails
  lib/net/networking_utils.js
Labels: type: bug, priority: P2

#5992 fix(UI): Fix disable PiP when using documentPictureInPicture
  ui/controls.js
Labels: type: bug, component: UI, priority: P1

#5990 feat: Rename aes128Key to aesKey to allow aes256 in the future
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/hls/hls_parser.js
  lib/media/segment_index.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_unit.js
  test/media/segment_index_unit.js
  test/media/segment_prefetch_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P4

#5996 fix: Fix untrusted types in MediaTailorAdManager
  lib/ads/media_tailor_ad_manager.js
Labels: type: bug, component: ads

#5994 chore: Add missing @externs header to codec extern
  externs/shaka/codecs.js
Labels: type: bug

#5998 fix(DASH): Check if periodCombiner_ exists before configuring
  lib/dash/dash_parser.js
Labels: type: bug, component: DASH

#6000 fix(HLS): Fix clear init segment mapping
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#6004 feat(UI): Hide resolution overflow menu button if there's only one choice
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2
