Repository shaka-project/shaka-player, pull requests merged in 2023-06, with the labels that each got.

#5253 fix: Ship to NPM without node version restrictions
  .npmignore
  package-lock.json
  package.json
Labels: type: bug

#5240 feat: Add AAC transmuxer
  build/types/transmuxer
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/adts.js
  lib/transmuxer/muxjs_transmuxer.js
  lib/util/mp4_generator.js
  lib/util/platform.js
  lib/util/player_configuration.js
  shaka-player.uncompiled.js
  test/media/media_source_engine_integration.js
  test/transmuxer/muxjs_transmuxer_integration.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, priority: P2

#5235 feat: Add AC-3 and EC-3 support in Mp4Generator
  lib/mss/mss_parser.js
  lib/transmuxer/mp3_transmuxer.js
  lib/util/mp4_generator.js
Labels: type: enhancement, priority: P3

#5260 fix: Fix build issue in the main branch
  lib/transmuxer/aac_transmuxer.js
Labels: type: bug

#5261 feat: Improve parsing time in DASH and HLS
  lib/dash/segment_list.js
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P3, component: DASH

#5263 fix(HLS): Fix HLS seekRange for live streams
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#5262 feat(HLS): Add support to _HLS_msn query param in LL streams
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5265 feat(HLS): Add support to _HLS_part query param in LL streams
  lib/hls/hls_parser.js
  lib/media/segment_reference.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5270 fix: Avoid unnecessary timestampOffset updates when using HLS segments mode
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2

#5269 fix(HLS): Avoid variable substitution if no variables
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#5264 feat(HLS): Improve HLS parsing time
  lib/hls/hls_classes.js
  lib/hls/manifest_text_parser.js
  lib/util/manifest_parser_utils.js
  test/hls/manifest_text_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5268 feat: Improve live latency on load
  lib/media/playhead.js
  lib/media/video_wrapper.js
Labels: type: enhancement, priority: P3

#5267 feat(HLS): Add support to BYTERANGE-LENGTH in EXT-X-PRELOAD-HINT
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5274 fix(HLS): Fix prefetch with LL-HLS stream
  lib/media/segment_prefetch.js
Labels: type: bug, component: HLS, priority: P2

#5266 fix(Demo): Allow enable LL only with Low Latency Mode config
  demo/main.js
Labels: type: bug, component: demo page, priority: P2

#5279 feat(HLS): Add support to blocking playlist reload by adding the CAN-BLOCK-RELOAD=YES
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5281 feat(HLS): Add support to HOLD-BACK in EXT-X-SERVER-CONTROL
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5273 feat(UI): Remove copyStyleSheets
  externs/pictureinpicture.js
  ui/pip_button.js
Labels: type: enhancement, component: UI, priority: P3

#5282 fix(HLS): Fix live playlist update when using no LL in a LL stream
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#5283 fix(HLS): Fix seek on LL streams when using segments mode
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P2

#5285 fix(DASH): Ignore minBufferTime when using LL
  lib/dash/dash_parser.js
Labels: type: bug, priority: P3, component: DASH

#5275 feat: Set segmentPrefetchLimit to 2 by default for low latency streaming
  docs/tutorials/config.md
  lib/player.js
  lib/util/player_configuration.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#5284 fix(HLS): Avoid HLS resync when there is a gap in the stream
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P2

#5221 docs: Link to Shaka Player React UI Library
  README.md
Labels: type: docs

#5296 fix: Fix implementation of AAC and MP3 transmuxers
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
Labels: type: bug, priority: P2

#5291 feat(DASH): Achieve better latency in LL streams
  lib/dash/dash_parser.js
Labels: type: enhancement, priority: P2, component: DASH

#5292 feat(HLS): Allow delivery directives in Live streams
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P3

#5303 fix(UI): Use pagehide instead of unload for PiP
  demo/close_button.js
  ui/pip_button.js
Labels: type: bug, component: UI, priority: P2

#5294 fix(HLS): Skip EXT-X-PRELOAD-HINT without full byterange info
  lib/hls/manifest_text_parser.js
Labels: type: bug, component: HLS, priority: P1

#5305 fix: Fix error when network status changes on src= playbacks
  lib/player.js
Labels: type: bug, priority: P1

#5311 fix(HLS): Parse EXT-X-PART-INF as media playlist tag
  lib/hls/manifest_text_parser.js
Labels: type: bug, component: HLS, priority: P2

#5309 fix(Demo): Fix error link width to avoid overlap with close button
  demo/demo.less
Labels: type: bug, component: demo page, priority: P2

#5310 feat: Add support to streamDataCallback when using prefetch
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3, component: DASH

#5316 feat: Add safeMargin as a parameter of the player selectAudioLanguage method
  AUTHORS
  CONTRIBUTORS
  lib/player.js
Labels: type: enhancement, priority: P3

#5320 feat: Add support to old EMSG schemeId for ID3
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3

#5322 chore: Create getTimestampAndDispatchMetadata_function in MediaSourceEngine
  lib/media/media_source_engine.js
Labels: priority: P2

#5315 fix(HLS): Don't do sequence mode workaround unless there's a text stream
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  test/media/streaming_engine_unit.js
Labels: type: bug, component: HLS, priority: P2

#5312 fix(HLS): Mark first partial segment as independent always
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#5326 feat: Improve sequence mode start time
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_unit.js
Labels: type: enhancement, priority: P3

#5332 fix(HLS): Avoid "Possible encoding problem detected!" when is a preload reference
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2

#5334 ci: main branch only - fix bad release PR
  .github/workflows/release-please.yaml
  .release-please-config.json
  .release-please-manifest.json
Labels: type: CI

#5327 fix: Get the correct timescale when there are two trak boxes
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  lib/util/mp4_box_parsers.js
Labels: type: bug, priority: P1

#5319 feat(HLS): Optimization of LL-HLS with byterange
  lib/hls/hls_parser.js
  lib/hls/manifest_text_parser.js
  lib/media/segment_prefetch.js
  lib/media/segment_reference.js
  lib/media/streaming_engine.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5329 feat: Parses a TFDT Box, with a loss of precision beyond 53 bits
  lib/media/media_source_engine.js
  lib/util/mp4_box_parsers.js
Labels: type: enhancement, component: HLS, priority: P4

#5342 feat(HLS): Optimize LL-HLS with byterange
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#5304 feat: Add liveSync configuration to catch up on live streams
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#5343 chore: Update IMA externs
  externs/ima.js
Labels: component: ads

#5347 feat(HLS): Support byterange optimization on servers with support to blocking playlist reload
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P3

#5297 feat: Add AC3 transmuxer
  build/types/transmuxer
  lib/transmuxer/ac3.js
  lib/transmuxer/ac3_transmuxer.js
  lib/util/mp4_generator.js
  lib/util/platform.js
  shaka-player.uncompiled.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, component: HLS, priority: P4

#5353 chore: Remove unused functions
  lib/transmuxer/ac3.js
  lib/transmuxer/adts.js
Labels: priority: P4

#5354 feat: Parses a PRFT Box, with a loss of precision beyond 53 bits
  lib/media/streaming_engine.js
  lib/util/mp4_box_parsers.js
  test/media/streaming_engine_unit.js
Labels: type: enhancement, priority: P4

#5349 chore(HLS): Update README regarding blocking playlist reload
  README.md
Labels: component: HLS

#5350 feat: Improve performance of multi-period DASH parsing
  lib/media/drm_engine.js
  lib/util/periods.js
Labels: type: enhancement, priority: P3, component: DASH

#5359 fix(docs): fix player configuration code in drm config tutorial
  docs/tutorials/drm-config.md
Labels: type: docs

#5345 fix: Fix DASH rejection of streams with ColourPrimaries and MatrixCoefficients
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#5352 feat: Add EC3 transmuxer
  build/types/transmuxer
  lib/transmuxer/ec3.js
  lib/transmuxer/ec3_transmuxer.js
  shaka-player.uncompiled.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, component: HLS, priority: P4

#5361 fix(media): Fix region checking in livestreams
  lib/media/region_observer.js
  lib/player.js
  test/media/region_observer_unit.js
Labels: type: bug, priority: P2, component: DASH

#5364 fix(HLS): Fix dvh1 and dvhe detection as video codec
  lib/util/manifest_parser_utils.js
Labels: type: bug, component: HLS, priority: P1

#5367 fix(UI): Fix resolution selection on src=
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#5365 feat(UI): Use Intl.DisplayNames to show the language name
  ui/language_utils.js
Labels: type: enhancement, component: UI, priority: P3

#5366 fix(WebVTT): Add support to middle position
  lib/text/vtt_text_parser.js
Labels: type: bug, priority: P2, component: WebVTT

#5369 fix: Populate HDR correctly
  lib/util/stream_utils.js
Labels: type: bug, priority: P2

#5371 fix(HLS): Ignore segments with zero duration
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#5372 fix(HLS): Fix avoid prefetch missing segments
  lib/media/segment_prefetch.js
Labels: type: bug, component: HLS, priority: P1

#5370 feat: Add preferredVideoHdrLevel config.
  demo/common/message_ids.js
  demo/config.js
  demo/locales/en.json
  demo/locales/source.json
  demo/main.js
  externs/shaka/player.js
  lib/media/adaptation_set_criteria.js
  lib/player.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: enhancement, browser: Chrome

#5373 feat(UI): Add HDR label to resolution when the track is HDR
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P4

#5376 fix(DASH): Avoid "Possible encoding problem detected!" when appending chunked data
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2, component: DASH

#5379 chore: Add transmuxer support in the README
  README.md
Labels: type: docs

#5378 fix(Demo): Trim custom manifestUri to avoid copy-paste errors
  demo/custom.js
Labels: type: bug, component: demo page, priority: P2

#5380 feat: Improve performance of setStreamProperties on low-end devices
  lib/media/media_source_engine.js
Labels: type: enhancement, priority: P3

#5377 feat: Optimize appendBuffer operations for init segments
  lib/media/media_source_engine.js
Labels: type: enhancement, priority: P3

#5381 fix: Only parse/probe TS if the reference is not an MP4 and not WebM
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1
