Repository shaka-project/shaka-player, pull requests merged in 2024-05, with the labels that each got.

#6433 fix: reBufferingGoal is not respected
  lib/media/play_rate_controller.js
  lib/media/stall_detector.js
  lib/player.js
  test/media/play_rate_controller_unit.js
  test/player_integration.js
  test/player_unit.js
Labels: type: bug, priority: P1

#6535 chore: Add new question to bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: process

#6532 fix: Make UITextDisplayer constructor backward compatible
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6536 fix(UI): Allow show same resolution with different video bandwidth
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#6537 fix: Fix init segment equality in Segment Prefetch
  lib/media/segment_prefetch.js
Labels: type: bug, priority: P2

#6538 fix: Fix tXml conversion to DOMElement
  lib/util/tXml.js
Labels: type: bug, priority: P2

#6547 docs: Clarify bandwidth estimation docs.
  externs/shaka/player.js
Labels: type: docs

#6548 feat(UI): List bandwidth for duplicate resolutions
  ui/resolution_selection.js
Labels: type: enhancement, component: UI

#6549 feat: Set autoCorrectDrift to false by default for low latency streaming
  docs/tutorials/config.md
  externs/shaka/player.js
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6555 docs: Write up-to-date tutorial for Preload
  docs/design/preload.md
  docs/design/preload.png
  docs/tutorials/index.json
  docs/tutorials/preload.md
Labels: type: docs

#6484 feat: Check encryptionScheme against MCap
  lib/util/stream_utils.js
  package-lock.json
  package.json
  test/media/drm_engine_unit.js
Labels: type: enhancement, component: EME, priority: P1

#6546 fix: Re-add setting playbackRate to 0 to control buffering state
  lib/media/play_rate_controller.js
  lib/media/stall_detector.js
  lib/player.js
  test/media/play_rate_controller_unit.js
  test/player_src_equals_integration.js
Labels: type: bug, priority: P1

#6558 fix: Issue with compiler minifying webOS device properties
  lib/util/platform.js
Labels: type: bug, priority: P1, platform: WebOS

#6557 test: Improve tests speed
  test/test/util/waiter.js
Labels: component: tests

#6561 feat: Add response URI to BAD_HTTP_STATUS error
  lib/net/http_plugin_utils.js
  lib/util/error.js
  test/net/http_plugin_unit.js
Labels: type: enhancement, priority: P3

#6565 test: Improve waitUntilPlayheadReaches function
  test/test/util/waiter.js
Labels: component: tests

#6563 ci: Add additional lab Chromecast devices
  .github/workflows/shaka-bot-commands/command-test.sh
  build/shaka-lab.yaml
  test/player_unit.js
  test/transmuxer/transmuxer_engine_integration.js
  test/ui/ui_unit.js
Labels: type: CI

#6568 test: Upgrade UA parser to differentiate Chromecasts
  package-lock.json
  package.json
Labels: component: tests

#6571 docs: Fix incomplete sentence in preload docs.
  docs/tutorials/preload.md
Labels: type: docs

#6567 test: Use MCap in test conditions
  test/codec_switching/codec_switching_integration.js
  test/test/util/util.js
  test/transmuxer/transmuxer_integration.js
Labels: component: tests

#6576 fix: Destroy preload managers on player destroy
  lib/player.js
Labels: type: bug, priority: P1

#6584 fix: Clear preload array before awaiting destroy
  lib/player.js
Labels: type: bug

#6590 feat(DASH): Support Dolby Vision profile 8.x (HEVC) and 10.x (AV1)
  lib/dash/dash_parser.js
  lib/media/segment_utils.js
Labels: type: enhancement, priority: P3, component: DASH

#6597 fix(HLS): Fix mimetype checking when using SUPPLEMENTAL-CODECS
  AUTHORS
  CONTRIBUTORS
  lib/media/segment_utils.js
Labels: type: bug, component: HLS, priority: P1

#6593 test: Show full name of skipped tests
  karma.conf.js
Labels: component: tests

#6601 chore: Check TextEngine support on all platforms
  lib/media/media_source_engine.js
Labels: priority: P4

#6598 feat(Ads): Implement skip ad functionality in Media Tailor
  lib/ads/media_tailor_ad.js
  lib/ads/media_tailor_ad_manager.js
  test/ui/ad_ui_unit.js
  ui/controls.js
  ui/less/ad_controls.less
Labels: type: enhancement, component: ads, priority: P3

#6596 test: Fix MSS VoD PlayReady test
  test/mss/mss_player_integration.js
Labels: component: tests

#6595 test: Remove bad condition on extracts ID3 metadata from AAC when transmuxing
  test/media/media_source_engine_integration.js
Labels: component: tests

#6594 test: Use drmIt for HLS SAMPLE-AES test
  test/hls/hls_parser_integration.js
Labels: component: tests

#6602 chore: Remove duplicate getCorrectVideoCodecs function
  lib/transmuxer/ts_transmuxer.js
Labels: type: code health, priority: P4

#6600 feat: Add a new setting to allow remove based on channels count
  demo/config.js
  externs/shaka/player.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6606 fix(CEA): reset PTS on new init segment
  lib/cea/cea_decoder.js
  lib/media/closed_caption_parser.js
Labels: type: bug, component: captions/subtitles, priority: P1

#6604 test: Use MCap on StreamUtils tests
  test/test/util/util.js
  test/util/stream_utils_unit.js
Labels: component: tests

#6608 fix(HLS): Fix bad detection in some MediaPlaylist
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6607 fix: Fix Opus support in Safari
  lib/media/media_source_engine.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/stream_utils.js
  test/test/util/util.js
Labels: type: bug, priority: P1, browser: Safari

#6614 test: Add multiperiod test case mirroring partner bug
  test/util/periods_unit.js
Labels: component: tests

#6617 feat: Set maxDisabledTime to 1 by default for low latency streaming
  docs/tutorials/config.md
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6624 fix(Ads): Fix CS destroy
  externs/ima.js
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#6621 test: Fix PlayReady test in Chromecast
  lib/media/drm_engine.js
  test/mss/mss_player_integration.js
  test/offline/offline_integration.js
  test/player_integration.js
Labels: component: tests, platform: Cast

#6620 feat: Add getNonDefaultConfiguration
  .github/ISSUE_TEMPLATE/bug_report.md
  lib/player.js
  lib/util/config_utils.js
  test/cast/cast_utils_unit.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6629 fix(HLS): Support request byterange on media playlist detection
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6634 fix: Disallow Object.fromEntries in Tizen
  build/conformance.textproto
  lib/util/config_utils.js
Labels: type: bug, priority: P3, platform: Tizen

#6633 test: Fix flaky test on Tizen
  test/player_integration.js
Labels: component: tests, platform: Tizen

#6630 feat(Preload): Add detachAndSavePreload method
  lib/player.js
  test/cast/cast_utils_unit.js
  test/player_integration.js
Labels: type: enhancement, priority: P3

#6643 test: Fix Chromecast testing in lab
  build/build.py
  build/check.py
  build/conformance.textproto
  build/shaka-lab.yaml
  externs/cast-namespace.js
  externs/cast-sdk-v2.js
  externs/cast-sdk-v3.js
  externs/mediatailor.js
  externs/remote-playback.js
  karma.conf.js
  package-lock.json
  proxy-cast-platform.js
  support.html
  test/test/boot.js
  test/test/cast-boot.js
Labels: type: CI, platform: Cast

#6641 feat(DASH): Add MPD Chaining support
  README.md
  demo/common/assets.js
  demo/config.js
  demo/search.js
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  lib/util/player_configuration.js
  roadmap.md
  test/dash/dash_parser_manifest_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/player_integration.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
  test/test/util/test_scheme.js
Labels: type: enhancement, priority: P3, component: DASH

#6619 test: Fix encryption scheme checks in tests
  karma.conf.js
  package-lock.json
  package.json
Labels: component: tests

#6638 test: Log support map on test startup
  test/test/boot.js
Labels: component: tests

#6648 docs: update error documentation
  docs/tutorials/errors.md
Labels: type: docs

#6640 test: Flatten test environment for Chromecast
  build/test.py
  karma.conf.js
  package-lock.json
  test/test/closure-boot.js
  test/test/util/layout_tests.js
Labels: type: CI, platform: Cast

#6649 feat: Optionally force HTTP content URIs
  demo/config.js
  externs/shaka/player.js
  lib/net/networking_engine.js
  lib/player.js
  lib/util/player_configuration.js
  test/test/util/fake_networking_engine.js
Labels: type: enhancement, priority: P4

#6653 fix: Fix numBytesRemaining when the request is done
  lib/net/http_fetch_plugin.js
  lib/net/http_xhr_plugin.js
Labels: type: bug, priority: P2, component: networking

#6651 test: Probe DRM robustness levels
  externs/shaka/player.js
  lib/media/drm_engine.js
Labels: component: tests

#6575 feat(Ads): Support CS on devices that don't support multiple media elements
  demo/config.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
  test/ads/ad_manager_unit.js
  test/ads_integration.js
Labels: type: enhancement, platform: TV/STB, component: ads, priority: P2, platform: Cast, platform: WebOS, platform: Tizen

#6650 feat: Add config for add headers to license requests
  demo/common/assets.js
  demo/main.js
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/util/config_utils.js
  lib/util/player_configuration.js
  test/media/drm_engine_unit.js
Labels: type: enhancement, priority: P3

#6659 chore(Demo): Update demo assets
  demo/common/assets.js
Labels: component: demo page

#6657 feat(ABR): Add cacheLoadThreshold config
  demo/config.js
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#6663 feat: Parse colorGamut and use it in MCap
  externs/shaka/manifest.js
  externs/shaka/offline.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
  lib/mss/mss_parser.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/util/mp4_box_parsers.js
  lib/util/stream_utils.js
  test/dash/dash_parser_manifest_unit.js
  test/offline/manifest_convert_unit.js
  test/offline/storage_integration.js
  test/player_unit.js
  test/test/util/manifest_generator.js
Labels: type: enhancement, priority: P3

#6666 test: Load IMA globally in one place once
  test/ads/ad_manager_unit.js
  test/ads_integration.js
  test/test/boot.js
Labels: type: code health, component: tests

#6667 test: Consolidate probeSupport in one place
  test/cast/cast_receiver_integration.js
  test/hls/hls_parser_integration.js
  test/media/drm_engine_integration.js
  test/mss/mss_player_integration.js
  test/offline/offline_integration.js
  test/offline/storage_integration.js
  test/player_external.js
  test/test/boot.js
Labels: type: code health, component: tests

#6668 chore(Demo): Disable Shaka Player history streams
  demo/common/assets.js
Labels: component: demo page

#6678 feat: add config to clear decodingInfo cache on unload
  demo/config.js
  externs/shaka/player.js
  lib/media/drm_engine.js
  lib/player.js
  lib/polyfill/media_capabilities.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/polyfill/media_capabilities_unit.js
  test/test/boot.js
Labels: type: enhancement, priority: P2, platform: Playstation 4, platform: Playstation 5

#6680 fix(HLS): Fix HLS load when using #EXT-X-I-FRAME-STREAM-INF without resolution
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#6679 fix(UI): Fix unhandled error when playing VR
  ui/vr_webgl.js
Labels: type: bug, component: UI, priority: P1

#6675 fix: Fix MCap checking when using src=
  lib/player.js
Labels: type: bug, priority: P2

#6677 fix(UI): Fix dragging the seek bar seeks and pans the view in VR mode
  ui/range_element.js
Labels: type: bug, component: UI, priority: P2

#6656 fix(Cast): Incorrect detection of MediaCapabilities on Chromecast
  lib/polyfill/media_capabilities.js
  test/polyfill/media_capabilities_unit.js
Labels: type: bug, priority: P1, platform: Cast

#6676 fix: Add timeout to fullyLoaded in src=
  demo/config.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: bug, priority: P2

#6684 chore(Demo): Fix CMSD asset features
  demo/common/assets.js
Labels: component: demo page

#6685 fix: Fix default value of liveSyncMinPlaybackRate
  externs/shaka/player.js
  lib/util/player_configuration.js
Labels: type: bug, priority: P2

#6686 fix: Ban smooth codec switching on Tizen 5 & 6
  lib/util/platform.js
  test/util/platform_unit.js
Labels: type: bug, priority: P2, platform: Tizen

#5247 feat(DASH): Add MPD Patch support
  README.md
  demo/common/assets.js
  demo/search.js
  lib/dash/dash_parser.js
  lib/dash/mpd_utils.js
  lib/dash/segment_template.js
  lib/util/error.js
  lib/util/periods.js
  lib/util/tXml.js
  test/dash/dash_parser_patch_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/dash/mpd_utils_unit.js
  test/util/tXml_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#6694 chore(Demo): Add missing icons
  demo/common/assets.js
Labels: component: demo page

#6689 test: Fix flaky ads integration test in uncompiled mode
  lib/player.js
Labels: component: tests

#6688 fix: Fix progress events for VOD when using vodDynamicPlaybackRate
  lib/player.js
Labels: type: bug, priority: P1

#6687 fix(DASH): Fix update of SegmentTemplate with $number$ for LL
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#6683 feat(DASH): Parse and use target latency
  demo/config.js
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/player.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#6696 fix: patch `setServerCertificate()` on older Tizens & webOS
  build/types/polyfill
  lib/polyfill/patchedmediakeys_cert.js
  lib/util/platform.js
  test/util/platform_unit.js
Labels: type: bug, component: EME, priority: P1, platform: WebOS, platform: Tizen

#6695 fix: Xbox - round gap jumping values
  lib/media/gap_jumping_controller.js
Labels: type: bug, priority: P1, platform: Xbox

#6691 fix(DASH): Firefox multi-period/multi-codec bug
  CONTRIBUTORS
  lib/util/stream_utils.js
Labels: type: bug, priority: P1, browser: Firefox, component: DASH

#6697 chore(Demo): Add missing icon
  demo/common/assets.js
Labels: component: demo page

#6702 fix(CEA): Ignore XDS control codes
  lib/cea/cea608_data_channel.js
  lib/cea/cea_decoder.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6699 fix: Fix COLR box parsing
  lib/util/mp4_box_parsers.js
Labels: type: bug, priority: P1

#6703 fix(CEA): Fix stream detection when the stream has not control codes
  lib/cea/cea_decoder.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6705 chore(Demo): Add new asset for CMSD
  demo/common/assets.js
  demo/search.js
Labels: component: demo page

#6706 test: Update screenshots
  test/test/assets/screenshots/safari-Mac/webvtt-native-align-center-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-native-align-end-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-native-align-start-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-native-bold-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-native-italic-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-native-size-50.png
  test/test/assets/screenshots/safari-Mac/webvtt-native-underline-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-ui-bold-long.png
Labels: component: tests

#6647 fix: Fix multi-codec filtering on DASH live
  lib/media/manifest_filterer.js
  lib/media/preload_manager.js
Labels: type: bug, priority: P1, component: DASH

#6700 feat(HLS): Build closed captions metadata on-the-fly
  demo/config.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
  test/cast/cast_receiver_integration.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, component: captions/subtitles, priority: P4

#6707 docs: Update docs for v4.9 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#6709 fix(preload): Copy net filters to preload manager
  docs/tutorials/preload.md
  lib/net/networking_engine.js
  lib/player.js
  test/test/util/fake_networking_engine.js
Labels: type: bug, priority: P1

#6714 feat: Add segment URIs to segment-related errors
  lib/media/content_workarounds.js
  lib/media/media_source_engine.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/mpeg_ts_transmuxer.js
  lib/transmuxer/mss_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/error.js
  test/media/content_workarounds_unit.js
  test/media/media_source_engine_unit.js
Labels: type: enhancement, priority: P2

#6716 fix(PS4): Fix serverCertificate defaulted to null
  lib/util/object_utils.js
Labels: type: bug, priority: P2, platform: Playstation 4

#6721 fix(UI): UI does not update after loading a new stream
  ui/audio_language_selection.js
  ui/resolution_selection.js
  ui/text_selection.js
Labels: type: bug, component: UI, priority: P2

#6722 chore(Demo): Add new assets with clearkeys
  demo/common/assets.js
Labels: component: demo page

#6713 fix: ensure all timelineregionenter events are fired
  lib/player.js
Labels: type: bug, priority: P1
