Repository shaka-project/shaka-player, pull requests merged in 2024-06, with the labels that each got.

#6718 feat(HLS): Add support for EXT-X-DATERANGE
  externs/shaka/manifest_parser.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/hls/manifest_text_parser.js
  lib/offline/storage.js
  lib/player.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_patch_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
  test/util/content_steering_manager_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6736 test: Add DASH ClearKey integration test
  karma.conf.js
  test/dash/dash_parser_integration.js
  test/test/assets/dash-clearkey/0001.m4s
  test/test/assets/dash-clearkey/0002.m4s
  test/test/assets/dash-clearkey/0003.m4s
  test/test/assets/dash-clearkey/0004.m4s
  test/test/assets/dash-clearkey/0005.m4s
  test/test/assets/dash-clearkey/dash.mpd
  test/test/assets/dash-clearkey/init.mp4
Labels: component: tests, component: ClearKey

#6737 fix: Avoid filter manifest when the DRM is not initialized
  lib/media/preload_manager.js
Labels: type: bug, priority: P1

#6730 test: Fix Karma debug.html support
  test/test/closure-boot.js
  test/test/externs/karma.js
Labels: component: tests

#6717 fix: Support for Zenterio
  lib/player.js
  lib/polyfill/mediasource.js
  lib/util/platform.js
  test/player_unit.js
Labels: type: bug, platform: TV/STB, priority: P2

#6739 fix: Do not export functions in getNonDefaultConfiguration
  lib/util/config_utils.js
Labels: type: bug, priority: P2

#6740 feat: Fix processing EXT-X-DATERANGE on live streams
  lib/hls/hls_parser.js
Labels: type: bug, priority: P2

#6738 feat(Ads): Add content resume/pause requested events
  lib/ads/ad_manager.js
  lib/ads/client_side_ad_manager.js
  lib/player.js
Labels: type: enhancement, component: ads, priority: P3

#6742 fix(UI): Fix resolution sorting
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#6741 chore: Collapse override comments in fake_ad_manager.js
  test/test/util/fake_ad_manager.js
Labels: type: code health

#6735 chore(Demo): Allow configure preferredAudioCodecs and preferredVideoCodecs
  demo/config.js
  demo/main.js
  test/demo/demo_unit.js
Labels: component: demo page

#6746 fix(preload): Fix preload error reporting
  lib/media/preload_manager.js
  lib/player.js
Labels: type: bug, priority: P1

#6752 fix(UI): Don't show presentation time in ads
  ui/presentation_time.js
Labels: type: bug, component: UI, component: ads, priority: P2

#6751 feat(HLS): Add support to variable substitution in EXT-X-DATERANGE
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P3

#6753 fix(preload): Fix error handling
  lib/media/drm_engine.js
  lib/media/preload_manager.js
  lib/player.js
  test/player_load_graph_integration.js
Labels: type: bug, priority: P2

#6755 fix(HLS): Ignore query params in the uri of EXT-X-SESSION-KEY tags
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#6756 feat(preload): Add new method destroyAllPreloads
  lib/player.js
  test/cast/cast_utils_unit.js
Labels: type: enhancement, priority: P3

#6757 feat(HLS): Ignore EXT-X-DATERANGE in the past
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, priority: P2

#6758 fix(HLS): Fix seekRange when using delta playlist
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P1

#6760 fix(ABR): Fix variant choose when two variants have the same bandwidth but different resolution
  lib/abr/simple_abr_manager.js
Labels: type: bug, priority: P2

#6759 feat: Add dontChooseCodecs config
  demo/config.js
  externs/shaka/player.js
  lib/media/manifest_filterer.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#6723 feat: Add audio codec to `selectAudioLanguage()`
  lib/media/adaptation_set_criteria.js
  lib/player.js
  test/media/adaptation_set_criteria_unit.js
  test/player_unit.js
  ui/audio_language_selection.js
  ui/language_utils.js
Labels: type: enhancement, priority: P3

#6761 feat(HLS): Add HLS interstitial support
  README.md
  build/types/ads
  demo/common/assets.js
  demo/main.js
  externs/shaka/ads.js
  externs/shaka/player.js
  karma.conf.js
  lib/ads/ad_manager.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
  lib/hls/hls_parser.js
  lib/media/preload_manager.js
  lib/player.js
  test/ads_integration.js
  test/hls/hls_parser_unit.js
  test/test/assets/hls-interstitial/ad-init.mp4
  test/test/assets/hls-interstitial/ad-s1.mp4
  test/test/assets/hls-interstitial/ad.m3u8
  test/test/assets/hls-interstitial/init.mp4
  test/test/assets/hls-interstitial/main.m3u8
  test/test/assets/hls-interstitial/s1.mp4
  test/test/assets/hls-interstitial/s2.mp4
  test/test/assets/hls-interstitial/s3.mp4
  test/test/assets/hls-interstitial/s4.mp4
  test/test/assets/hls-interstitial/s5.mp4
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, component: HLS, component: ads, priority: P3

#6719 fix: Fix green screen issue on Edge with mixed content
  build/types/core
  lib/media/content_workarounds.js
  lib/media/drm_engine.js
  lib/media/media_source_engine.js
  lib/player.js
  lib/util/drm_utils.js
  lib/util/platform.js
  test/cast/cast_utils_unit.js
  test/media/content_workarounds_unit.js
  test/media/drm_engine_integration.js
  test/media/drm_engine_unit.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
  test/util/drm_utils_unit.js
Labels: type: bug, priority: P2, platform: Windows, browser: Edge

#6774 feat(Ads): Improve resume times when the interstial uses two video elements
  lib/ads/interstitial_ad_manager.js
Labels: type: enhancement, type: performance, component: ads, priority: P3

#6778 chore: Remove old LCEVC code
  lib/player.js
Labels: type: code health

#6777 feat(Ads): Add support for interstitials when using src=
  lib/ads/interstitial_ad_manager.js
  lib/player.js
Labels: type: enhancement, component: ads, priority: P3, browser: Safari

#6781 feat(Stats): count non fatal errors
  externs/shaka/player.js
  lib/player.js
  lib/util/stats.js
  test/player_integration.js
  ui/statistics_button.js
Labels: type: enhancement, priority: P3

#6782 fix(Ads): Fix interstitial ad values when the ad is loading
  lib/ads/interstitial_ad.js
Labels: type: bug, component: ads, priority: P2

#6783 feat(Stats): add size of the manifest to player stats
  externs/shaka/player.js
  lib/player.js
  lib/util/stats.js
  test/player_integration.js
  ui/statistics_button.js
Labels: type: enhancement, priority: P3

#6780 fix: Fix AC-4 codec string in MediaSourceEngine
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#6775 fix(DRM): close properly webkit media key sessions
  externs/polyfill.js
  lib/media/drm_engine.js
  lib/player.js
  lib/polyfill/patchedmediakeys_apple.js
  lib/polyfill/patchedmediakeys_nop.js
  lib/polyfill/patchedmediakeys_webkit.js
  lib/util/platform.js
  test/player_unit.js
  test/polyfill/patchedmediakeys_apple_unit.js
  test/util/platform_unit.js
Labels: type: bug, component: EME, priority: P1, platform: WebOS

#6784 fix(Ads): Fix duplicate interstitials when using src=
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#6785 feat(Ads): Add CUE ONCE support in Interstitials
  README.md
  lib/ads/interstitial_ad_manager.js
  lib/player.js
  test/test/assets/hls-interstitial/main.m3u8
Labels: type: enhancement, component: ads, priority: P3

#6790 fix: `getPresentationStartTimeAsDate()` should return time unaffected by clock drift
  lib/media/presentation_timeline.js
Labels: type: bug, priority: P2

#6787 feat(DASH): add `MPD_PATCH` advanced request type
  lib/dash/dash_parser.js
  lib/net/networking_engine.js
  test/dash/dash_parser_patch_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#6797 feat(UI): Initialize interstitials by default when using UI
  demo/main.js
  ui/controls.js
Labels: type: enhancement, component: UI, component: ads, priority: P3

#6798 feat(Stats): Add `manifestPeriodCount` to stats
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  lib/util/stats.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_patch_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/player_integration.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
  ui/statistics_button.js
Labels: type: enhancement, priority: P3

#6792 feat(Ads): Improve preload timing on interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#6791 feat(Ads): Add CUEPOINTS_CHANGED event to interstitials
  lib/ads/ad_manager.js
  lib/ads/interstitial_ad_manager.js
  lib/cast/cast_utils.js
  lib/player.js
  ui/seek_bar.js
Labels: type: enhancement, component: ads, priority: P3

#6793 feat(HLS): Only process DATE-RANGE in AUDIO and VIDEO playlists
  lib/hls/hls_parser.js
Labels: type: enhancement, component: HLS, priority: P3

#6800 feat(HLS): Use PLANNED-DURATION to determine the end time
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6803 fix: Fix initial track selection in src= when using HLS
  lib/player.js
Labels: type: bug, priority: P2, browser: Safari

#6799 feat(Ads): Add CUE PRE and POST support in Interstitials
  lib/ads/interstitial_ad_manager.js
  lib/player.js
  test/ads_integration.js
  test/test/assets/hls-interstitial/main.m3u8
Labels: type: enhancement, component: ads, priority: P3

#6805 fix: `selectAudioLanguage()` should ignore unplayable variants
  lib/player.js
  test/player_unit.js
Labels: type: bug, priority: P2

#6802 fix: ignore buffered content less than 1e-4s
  lib/media/time_ranges_utils.js
Labels: type: bug, priority: P2, browser: Firefox

#6807 feat(HLS): Allow disable streams when the media playlist fails
  externs/shaka/manifest_parser.js
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  lib/offline/storage.js
  lib/player.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_patch_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
  test/util/content_steering_manager_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6806 feat(Ads): Add support for X-TIMELINE-OCCUPIES
  lib/ads/interstitial_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#6804 feat(Stats): Add `manifestGapCount` to stats
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  lib/util/stats.js
  test/dash/dash_parser_manifest_unit.js
  test/hls/hls_parser_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/player_integration.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
  ui/statistics_button.js
Labels: type: enhancement, priority: P3

#6813 test: Enable IMA tests in Tizen
  test/ads_integration.js
  test/test/boot.js
Labels: component: ads, component: tests, platform: Tizen

#6814 feat(UI): Add new stats to context menu
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#6811 ci: Compute sha1 from ref in advance in lab and screenshot workflows
  .github/workflows/selenium-lab-tests.yaml
  .github/workflows/update-screenshots.yaml
Labels: type: CI

#6815 chore(Demo): Allow configure customContextMenu UI config
  demo/config.js
  demo/main.js
  test/test/util/fake_demo_main.js
Labels: component: demo page

#6818 fix(HLS): Fix AC-4 codec selection in HLS
  lib/util/manifest_parser_utils.js
Labels: type: bug, component: HLS, priority: P2

#6817 feat(Ads): Fill loadTime stats in interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#6821 fix(CMCD): Fix reset CMCD on unload
  lib/player.js
  lib/util/cmcd_manager.js
Labels: type: bug, priority: P2

#6832 fix(TTML): Extended subtitle codec support
  lib/text/mp4_ttml_parser.js
Labels: type: bug, component: TTML, priority: P3

#6830 fix(TTML): Fix timing parsing when using 1dp
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: type: bug, component: TTML, priority: P2

#6826 chore(Ads): Remove testing workaround in interstitials
  lib/ads/interstitial_ad_manager.js
Labels: component: ads, priority: P1

#6827 feat(UI): Add ad statistics button
  build/types/ui
  docs/tutorials/ui-customization.md
  shaka-player.uncompiled.js
  ui/ad_statistics_button.js
  ui/externs/ui.js
  ui/less/containers.less
  ui/locales/en.json
  ui/locales/es-419.json
  ui/locales/es.json
  ui/locales/source.json
  ui/ui.js
Labels: type: enhancement, component: UI, component: ads, priority: P3

#6822 feat: add liveSyncTargetLatency option and deprecate liveSyncMinLatency and liveSyncMaxLatency options
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#6838 fix: Exclude fetch polyfill from fetch plugin
  lib/net/http_fetch_plugin.js
Labels: type: bug, priority: P2, component: networking

#6845 feat: move live sync options into their own object
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#6846 fix(UI): update Polish translations
  ui/locales/pl.json
Labels: type: bug, component: UI, priority: P2

#6852 ci: Remove ChromecastHub from shaka bot commands
  .github/workflows/shaka-bot-commands/command-test.sh
Labels: type: CI

#6854 docs: fix typo
  docs/tutorials/text-displayer.md
Labels: type: docs

#6855 docs: fix test.py enable-logging section of README
  build/README.md
Labels: type: docs

#6842 feat: Add isLowLatency to shaka.extern.Manifest
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  test/hls/hls_parser_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P3

#6853 ci: Migrate Firefox from macos-13 to macos-latest
  .github/workflows/build-and-test.yaml
Labels: type: CI

#6828 feat(Ads): Add averageLoadTime and errors to ad stats
  externs/shaka/ads.js
  lib/ads/ad_manager.js
  lib/ads/ads_stats.js
  ui/ad_statistics_button.js
  ui/ui.js
Labels: type: enhancement, component: ads, priority: P3

#6843 fix: Allow use startTime equal to 0 in HLS live streams using src=
  lib/media/playhead.js
Labels: type: bug, component: HLS, priority: P2, browser: Safari

#6851 fix(DRM): Probe robustness only for modern PlayReady keysystem
  lib/media/drm_engine.js
Labels: type: bug, component: EME, priority: P2, component: PlayReady

#6857 feat(hls): expose manifest skd uri on drmInfo
  docs/tutorials/fairplay.md
  externs/shaka/manifest.js
  lib/hls/hls_parser.js
  lib/media/drm_engine.js
  lib/util/manifest_parser_utils.js
  test/hls/hls_parser_unit.js
  test/test/util/manifest_generator.js
Labels: type: enhancement, component: HLS, priority: P3, component: FairPlay

#6865 fix: Fix normalized codec for Dolby Vision
  lib/util/mime_utils.js
  test/util/mime_utils_unit.js
Labels: type: bug, priority: P2

#6864 ci: Reduce timeout minutes on test workflows
  .github/workflows/build-and-test.yaml
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#6861 fix: Fix continues to play a few seconds after reaching playRangeEnd
  lib/media/streaming_engine.js
  lib/player.js
  test/test/util/simple_fakes.js
Labels: type: bug, priority: P3

#6866 feat: Parse dvvC box for Dolby Vision support
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
Labels: type: enhancement, priority: P3

#6868 feat(Ads): Remove circular dependency
  build/types/ads
  docs/tutorials/ad_monetization.md
  lib/ads/ad_manager.js
  lib/ads/ad_utils.js
  lib/ads/client_side_ad_manager.js
  lib/ads/interstitial_ad_manager.js
  lib/ads/media_tailor_ad_manager.js
  lib/ads/server_side_ad_manager.js
  lib/player.js
  test/ads/ad_manager_unit.js
  test/ads_integration.js
  test/test/util/fake_ad_manager.js
  test/ui/ad_ui_unit.js
  ui/ad_counter.js
  ui/ad_position.js
  ui/ad_statistics_button.js
  ui/controls.js
  ui/element.js
  ui/mute_button.js
  ui/overflow_menu.js
  ui/play_button.js
  ui/presentation_time.js
  ui/seek_bar.js
  ui/skip_ad_button.js
  ui/volume_bar.js
Labels: type: enhancement, type: code health, component: ads, priority: P3

#6870 feat(UI): Highlight current time when hovered on seek bar
  ui/less/thumbnails.less
  ui/seek_bar.js
Labels: type: enhancement, component: UI, priority: P3

#6867 fix: Fix audio properties detection
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
  test/test/assets/audio-ac-4.mp4
  test/util/mp4_box_parsers_unit.js
Labels: type: bug, priority: P2

#6873 fix(UI): update French translations
  ui/locales/fr.json
Labels: type: bug, component: UI, priority: P2

#6874 fix(UI): update Portuguese translations
  ui/locales/pt-BR.json
  ui/locales/pt-PT.json
Labels: type: bug, component: UI, priority: P2

#6875 fix(UI): update Spanish translations
  ui/locales/es.json
Labels: type: bug, component: UI, priority: P2

#6878 fix(CEA): CEA-608 is not rendered in some cases (multiples TRAF boxes)
  lib/cea/mp4_cea_parser.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6880 fix(HLS): Avoid make a HEAD request of gap segments
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6881 fix: Avoid firing SEGMENT_MISSING when there is an alternative
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#6879 fix: Generate the correct codec for AV1 HDR
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
Labels: type: bug, priority: P2

#6882 fix(HLS): Avoid get basic info when the first segment is a gap
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6884 fix(HLS): Identify EXT-X-GAP with segment tags
  lib/hls/manifest_text_parser.js
Labels: type: bug, component: HLS, priority: P2

#6890 fix(preload): Fix preload load latency logic.
  lib/media/preload_manager.js
  lib/player.js
Labels: type: bug, priority: P2

#6892 fix(HLS): Allow detect mimeType from non-gap segments
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6894 fix(preload): Fix memory leak with preload feature
  lib/media/streaming_engine.js
Labels: type: bug, type: performance, priority: P1

#6901 fix(HLS): Fix MPEG-H codec selection in HLS
  lib/util/manifest_parser_utils.js
Labels: type: bug, component: HLS, priority: P2

#6900 fix(HLS): Disable stream when the media live playlist is stuck
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6898 fix(HLS): Fix get basic info from segments
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6895 ci: Improve test times
  test/test/util/waiter.js
Labels: component: tests

#6896 fix(DASH): Allow play when SegmentTimeline has a duration 0 "S" element
  lib/dash/mpd_utils.js
  test/dash/mpd_utils_unit.js
Labels: type: bug, priority: P2, component: DASH

#6903 chore(demo): fix pattern to allow <1 decimals if can't be zero
  demo/input.js
Labels: component: demo page

#6907 fix(CS): Fix IMA integration
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#6858 feat: Dynamic target latency
  demo/config.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
  test/cast/cast_receiver_integration.js
Labels: type: enhancement, priority: P3

#6899 fix(Prefetch): cache iterator to avoid precision issues
  lib/media/preload_manager.js
  lib/media/segment_index.js
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  test/media/segment_prefetch_unit.js
  test/test/util/fake_segment_prefetch.js
Labels: type: bug, priority: P2

#6908 fix(Prefetch): Ensure prefetched segments are continuous
  lib/media/segment_prefetch.js
  test/media/segment_prefetch_unit.js
Labels: type: bug, priority: P2

#6906 test: Add Dolby Vision integration tests
  karma.conf.js
  test/player_dolby_vision_integration.js
  test/test/assets/dv-p10-av1/dovi_10-video.mp4
  test/test/assets/dv-p10-av1/manifest.mpd
  test/test/assets/dv-p10-av1/master.m3u8
  test/test/assets/dv-p10-av1/media.m3u8
  test/test/assets/dv-p8-hevc/dovi_8-video.mp4
  test/test/assets/dv-p8-hevc/manifest.mpd
  test/test/assets/dv-p8-hevc/master.m3u8
  test/test/assets/dv-p8-hevc/media.m3u8
Labels: component: tests

#6912 feat(CEA): Add CEA support for VVC/H.266
  lib/cea/cea_utils.js
  lib/cea/mp4_cea_parser.js
Labels: type: enhancement, component: captions/subtitles, priority: P4

#6911 test: Fix flaky test in Edge macOS
  test/hls/hls_parser_integration.js
Labels: component: tests

#6910 fix(Ads): Fix skip functionality in MediaTailor
  externs/mediatailor.js
  lib/ads/media_tailor_ad.js
Labels: type: bug, component: ads, priority: P2

#6915 fix(HLS): Fix getAvailableSegment_ function
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#6916 feat: Add option to disable continue loading live stream manifest when paused
  demo/config.js
  externs/shaka/manifest_parser.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/offline_manifest_parser.js
  lib/player.js
  lib/util/player_configuration.js
  test/offline/storage_integration.js
  test/test/util/test_scheme.js
Labels: type: enhancement, priority: P3

#6919 chore(Demo): Clear visualizer on unloading
  demo/visualizer.js
Labels: type: bug, component: demo page, priority: P2

#6920 chore(Demo): Save visualizer state
  demo/main.js
  demo/visualizer_button.js
Labels: type: enhancement, component: demo page, priority: P3

#6921 chore(Demo): Show muxed content in the visualizer
  demo/visualizer.js
  lib/player.js
Labels: type: enhancement, component: demo page, priority: P2

#6913 feat: add an audiotrackchanged event for when label, language, or roles of an audio track change
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/media/quality_observer.js
  lib/player.js
  lib/util/fake_event.js
  test/media/quality_observer_unit.js
  test/media/segment_reference_unit.js
  test/test/util/test_scheme.js
Labels: type: enhancement, priority: P3

#6925 chore(demo): Change visualizer update duration
  demo/visualizer.js
Labels: type: enhancement, component: demo page, priority: P2

#6923 feat(MSS): Add support for MediaQualityInfo events
  lib/media/quality_observer.js
  lib/mss/mss_parser.js
  lib/player.js
Labels: type: enhancement, priority: P3, component: MSS

#6926 feat(UI): Add save video frame button
  build/types/ui
  docs/tutorials/ui-customization.md
  shaka-player.uncompiled.js
  ui/enums.js
  ui/locales/en.json
  ui/locales/es.json
  ui/locales/fr.json
  ui/locales/pl.json
  ui/locales/pt-BR.json
  ui/locales/pt-PT.json
  ui/locales/source.json
  ui/save_video_frame_button.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#6935 feat: Fix useNativeHlsOnSafari deprecation
  demo/common/assets.js
  demo/config.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
  test/ads_integration.js
  test/hls/hls_parser_integration.js
  test/player_dolby_vision_integration.js
  test/player_unit.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, priority: P3

#6930 test: Fix flaky test in Edge macOS
  test/player_src_equals_integration.js
Labels: component: tests

#6928 fix(ABR): Add a guard when variant is null
  lib/abr/simple_abr_manager.js
Labels: type: bug, priority: P2

#6927 feat(HLS): Add support for MediaQualityInfo events
  lib/hls/hls_parser.js
  lib/media/segment_reference.js
  lib/player.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6929 fix: Only request initialization segment when it's necessary
  lib/media/streaming_engine.js
  test/media/streaming_engine_unit.js
Labels: type: bug, priority: P1

#6931 fix: Don't clear the buffer when disable a stream
  lib/media/streaming_engine.js
  lib/player.js
Labels: type: bug, priority: P1

#6936 build: don't include externs in generated .d.ts files
  build/build.py
Labels: type: bug, priority: P2

#6940 fix(HLS): Allow disable initial variant if necessary
  lib/hls/hls_parser.js
  lib/player.js
Labels: type: bug, component: HLS, priority: P1
