Repository shaka-project/shaka-player, pull requests merged in 2024-10, with the labels that each got.

#7389 fix(UI): Restore missing AirPlay button
  lib/player.js
  ui/remote_button.js
Labels: type: bug, component: UI, priority: P2, browser: Safari

#7393 chore: Remove duplicated code in MediaSourceEngine
  lib/media/media_source_engine.js
Labels: type: code health, priority: P3

#7402 test: Fix lingering timer test leak
  test/player_integration.js
Labels: component: tests

#7408 fix: Fire PRFT event every time
  lib/media/media_source_engine.js
Labels: type: bug, priority: P3

#7410 test: Disable codec switch smooth test if changeType() is unavailable
  test/codec_switching/codec_switching_integration.js
Labels: component: tests

#7413 fix(PS4/5): Disable smooth codec switch on PS4/5
  lib/util/platform.js
Labels: type: bug, priority: P2, platform: Playstation 4, platform: Playstation 5

#7414 fix: Disable smooth codec switch if changeType is unavailable
  lib/util/player_configuration.js
Labels: type: bug, priority: P2

#7406 feat: Use source tags instead of src attribute
  lib/media/drm_engine.js
  lib/media/media_source_engine.js
  lib/player.js
  lib/util/dom_utils.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/player_load_graph_integration.js
  test/player_src_equals_integration.js
  test/test/util/simple_fakes.js
  ui/ui.js
Labels: type: enhancement, priority: P3

#7405 fix(DASH): Live DASH allows segment overlap in the updated manifest for first new segments
  lib/dash/segment_template.js
Labels: type: bug, priority: P2, component: DASH

#7404 fix(DASH): Live to vod transition
  karma.conf.js
  lib/dash/dash_parser.js
  test/player_integration.js
  test/test/assets/7401/chunk-stream0-00001.m4s
  test/test/assets/7401/chunk-stream0-00002.m4s
  test/test/assets/7401/chunk-stream0-00003.m4s
  test/test/assets/7401/chunk-stream0-00004.m4s
  test/test/assets/7401/chunk-stream0-00005.m4s
  test/test/assets/7401/chunk-stream0-00006.m4s
  test/test/assets/7401/chunk-stream0-00007.m4s
  test/test/assets/7401/dash_0.mpd
  test/test/assets/7401/dash_1.mpd
  test/test/assets/7401/dash_2.mpd
  test/test/assets/7401/init-stream0.m4s
  test/test/util/waiter.js
Labels: type: bug, priority: P1, component: DASH

#7430 fix(UI): Fix auto-load with source tags
  test/ui/ui_unit.js
  ui/ui.js
Labels: type: bug, component: UI, priority: P1

#7432 docs: Update roadmap
  roadmap.md
Labels: type: docs

#7423 fix: Seek delay for Cast Nest hub
  lib/media/playhead.js
Labels: type: bug, priority: P1, platform: Cast

#7438 fix(UI): Fix the position of save video frame in the overflow menu
  ui/ui.js
Labels: type: bug, component: UI, priority: P2

#7439 feat(UI): Added Mute button to context menu and overflow menu
  docs/tutorials/ui-customization.md
  ui/mute_button.js
Labels: type: enhancement, component: UI, priority: P3

#7421 fix: calculations of channel count for DASH AudioChannelConfiguration elements.
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#7457 fix(DRM): Fix persistent licenses not working for online playback
  lib/media/drm_engine.js
  test/media/drm_engine_unit.js
Labels: type: bug, priority: P2

#7459 chore: Clean up code
  lib/media/drm_engine.js
  test/media/drm_engine_unit.js
Labels: type: code health

#7461 chore: Remove IMA tests
  test/ads_integration.js
  test/test/boot.js
Labels: component: tests

#7470 fix: Fix select HLG tracks when using AUTO hdr level
  lib/media/adaptation_set_criteria.js
Labels: type: bug, priority: P2

#7472 docs: Add a section to the UI tutorial
  docs/tutorials/ui.md
Labels: type: docs

#7464 fix(UI): Hidden cursor correctly
  ui/controls.js
  ui/less/containers.less
Labels: type: bug, component: UI, priority: P2

#7465 fix(Ads): Allow preload and remove old interstitials when playing a interstitial
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7469 fix(Ads): Don't load useless segments when using playoutLimit on interstitial ads
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7474 chore: Update issue template to mention geo-blocks
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: docs

#7476 fix: Fix Windows detection
  lib/media/content_workarounds.js
  lib/util/platform.js
Labels: type: bug, priority: P2, platform: Windows

#7478 fix: Fix metadata timing when using TS
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#7479 fix(Ads): Disable interstitials when using AirPlay
  lib/ads/interstitial_ad_manager.js
  lib/player.js
  test/cast/cast_utils_unit.js
Labels: type: bug, component: ads, priority: P2, component: AirPlay

#7481 fix(UI): Don't enable StatisticsButton when create overflow menu
  ui/statistics_button.js
Labels: type: bug, component: UI, priority: P3

#7467 feat(Ads): New HLS interstitial DATERANGE attributes for Skip Button
  externs/shaka/ads.js
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
  ui/skip_ad_button.js
Labels: type: enhancement, component: ads, priority: P3

#7482 feat(UI): Add close button to statistics panel
  test/ui/ui_unit.js
  ui/ad_statistics_button.js
  ui/statistics_button.js
Labels: type: enhancement, component: UI, priority: P4

#7454 feat: Support Fairplay DRM in DASH manifest.
  lib/dash/content_protection.js
  lib/util/error.js
  lib/util/player_configuration.js
  test/dash/dash_parser_content_protection_unit.js
Labels: type: enhancement, priority: P3, component: DASH, component: FairPlay

#7484 fix(MSS): Fix timeline repetitions
  lib/mss/mss_parser.js
  test/mss/mss_parser_unit.js
Labels: type: bug, priority: P1, component: MSS

#7487 feat(Demo): Add new asset with DASH-FairPlay
  demo/asset_card.js
  demo/common/assets.js
  demo/demo.less
  demo/icons/custom_fairplay.svg
  demo/main.js
  lib/media/media_source_engine.js
  test/player_external.js
Labels: component: demo page, priority: P3, component: DASH, component: FairPlay

#7488 fix(Ads): Limit interstitial duration to actual duration if available when using src=
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7489 ci: Do not cancel other Selenium jobs
  .github/workflows/selenium-lab-tests.yaml
Labels: priority: P0, type: CI

#7497 fix: Fix disable stream when no manifest
  lib/player.js
Labels: type: bug, priority: P1

#7493 fix(Ads): fix pre-roll identification when using src=
  lib/player.js
Labels: type: bug, component: ads, priority: P2

#7495 fix: Allow streaming again when we reset MSE
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1, browser: Safari

#7496 chore: Unify getBuffered_ behaviour in MediaSourceEngine to avoid issues
  lib/media/media_source_engine.js
Labels: type: code health, priority: P1

#7494 fix: Fix reset MSE to last independent segment
  lib/media/segment_index.js
  lib/media/streaming_engine.js
  test/test/util/simple_fakes.js
Labels: type: bug, priority: P1

#7500 fix(AirPlay): Prefer Playback Remote API for closeOpenSessions
  lib/media/drm_engine.js
Labels: type: bug, priority: P2, component: AirPlay

#7501 chore: Simplify listener management to be able to use the same basic listeners in MSE and src=
  lib/player.js
Labels: type: code health, priority: P2

#7502 docs: Update documentation about MPD alternate
  README.md
  docs/tutorials/ad_monetization.md
Labels: type: docs

#7499 fix(HLS): Ignore DATERANGE with errors instead of fire an error
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#7504 fix: Don't use info from MSE mode when using Remote Playback
  lib/player.js
Labels: type: bug, priority: P2

#7503 fix: Do not allow MSE operations when using Remote Playback
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#7508 fix: Fix support of getAllThumbnails when using shaka.dash.TimelineSegmentIndex
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#7506 fix: Reset MSE when we disconnect from Remote Playback
  lib/player.js
Labels: type: bug, priority: P2

#7507 fix(UI): Remove buffering spinner when playing a client side ad
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/interstitial_ad.js
  lib/ads/media_tailor_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
  ui/controls.js
Labels: type: bug, component: UI, component: ads, priority: P2

#7498 feat(HLS): Add the update period for HLS manifest
  demo/config.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: HLS, priority: P3

#7513 fix(UI): Fix remote button availability and icon
  ui/remote_button.js
Labels: type: bug, component: UI, priority: P2, platform: Cast, component: AirPlay

#7515 fix(AirPlay): Show AirPlay button when starting the playback with AirPlay
  ui/remote_button.js
Labels: type: bug, priority: P2, component: AirPlay

#7517 fix(MSS): Fix playback of some MSS streams
  lib/util/mp4_generator.js
Labels: type: bug, priority: P2, browser: Safari, component: MSS

#7514 fix(AirPlay): Don't show subtitles on the player when using AirPlay
  lib/player.js
Labels: type: bug, component: captions/subtitles, priority: P2, component: AirPlay

#7521 fix(UI): Fix set MediaSession info when no previous Metadata
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#7524 chore(Ads): Add starting interstitials log
  lib/ads/interstitial_ad_manager.js
Labels: component: ads, priority: P2

#7525 perf(Ads): Reduce latency for interstitial to start playing
  lib/ads/interstitial_ad_manager.js
Labels: type: performance, component: ads, priority: P1

#7431 feat: Enable AirPlay in MSE
  lib/media/media_source_engine.js
  lib/player.js
Labels: type: enhancement, priority: P1, browser: Safari, component: AirPlay

#7523 feat: Add preferredTextFormats config
  demo/config.js
  demo/main.js
  externs/shaka/player.js
  lib/media/manifest_filterer.js
  lib/offline/storage.js
  lib/util/player_configuration.js
  lib/util/stream_utils.js
  test/demo/demo_unit.js
  test/util/stream_utils_unit.js
Labels: type: enhancement, priority: P3

#7526 chore: Reduce severity of some MediaSession logs
  ui/controls.js
Labels: type: code health

#7528 perf(Ads): Reduce latency for interstitial to start playing
  lib/ads/interstitial_ad_manager.js
Labels: type: performance, component: ads, priority: P2
