Repository shaka-project/shaka-player, pull requests merged in 2024-07, with the labels that each got.

#6937 docs: Update docs for v4.10 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#6948 fix(SimpleTextDisplayer): Do not disable metadata & chapters tracks
  lib/text/simple_text_displayer.js
Labels: type: bug, priority: P2

#6952 perf(DRM): compare init data only when config flag is set
  lib/media/drm_engine.js
Labels: type: performance, priority: P1

#6954 perf(HLS): do not loop twice when processing nalus
  lib/util/ts_parser.js
Labels: type: performance, priority: P1

#6960 chore(DRM): Move util methods from DrmEngine to DrmUtils
  lib/hls/hls_parser.js
  lib/media/drm_engine.js
  lib/player.js
  lib/polyfill/media_capabilities.js
  lib/polyfill/patchedmediakeys_apple.js
  lib/polyfill/patchedmediakeys_webkit.js
  lib/util/drm_utils.js
  lib/util/periods.js
  test/media/drm_engine_unit.js
  test/polyfill/media_capabilities_unit.js
  test/util/drm_utils_unit.js
Labels: type: code health

#6962 docs: Fix downloadfailed documentation
  lib/player.js
Labels: type: docs

#6959 fix: Avoid clear buffer when select the same audio track
  lib/player.js
Labels: type: bug, priority: P1

#6958 fix(UI): Don't display NaN stats
  ui/statistics_button.js
Labels: type: bug, component: UI, priority: P2

#6957 fix(Stats): Fix completionPercent for Live
  lib/player.js
Labels: type: bug, priority: P2

#6947 fix(SSA): Support files with line breaks that are not necessary
  lib/text/ssa_text_parser.js
  test/text/ssa_text_parser_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6949 fix: Filter duplicate cues on text displayer append
  lib/text/text_utils.js
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6956 fix: Fix NaN and empty objects in getNonDefaultConfiguration
  lib/util/config_utils.js
  test/player_unit.js
Labels: type: bug, priority: P3

#6938 feat(HLS): Add support for EXT-X-START
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  roadmap.md
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, component: HLS, priority: P3

#6966 test: Fail IMA tests on ad-error
  test/ads_integration.js
Labels: component: tests

#6967 fix(TTML): Show background color with image subtitles
  lib/text/ui_text_displayer.js
Labels: type: bug, component: TTML, component: captions/subtitles, priority: P2

#6969 fix(TTML): Fix font styles parsing
  lib/text/ttml_text_parser.js
Labels: type: bug, component: TTML, priority: P2

#6971 feat(DASH): Add DVB Font downloads
  demo/common/assets.js
  externs/font_face_set.js
  externs/shaka/manifest_parser.js
  lib/dash/dash_parser.js
  lib/offline/storage.js
  lib/player.js
  test/cast/cast_utils_unit.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_patch_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
  test/util/content_steering_manager_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#6970 fix: Exclude future segments in notifyTimeRange calculations
  lib/media/presentation_timeline.js
  test/media/presentation_timeline_unit.js
Labels: type: bug, priority: P1

#6968 feat(TTML): Add support for IMSC1 (CMAF) image subtitle
  demo/common/assets.js
  externs/shaka/text.js
  lib/player.js
  lib/text/mp4_ttml_parser.js
  lib/text/srt_text_parser.js
  lib/text/text_engine.js
  lib/text/ttml_text_parser.js
  test/test/assets/imsc-image-init.cmft
  test/test/assets/imsc-image-segment.cmft
  test/text/mp4_ttml_parser_unit.js
  test/text/text_engine_unit.js
  test/text/ttml_text_parser_unit.js
Labels: type: enhancement, component: TTML, priority: P3

#6982 fix(UI): fix wrong french in translation
  ui/locales/fr.json
Labels: type: bug, component: UI, priority: P2

#6981 chore(HLS): Change bad warning
  lib/hls/hls_parser.js
Labels: priority: P2

#6977 fix: honor autoShowText on non-audio streams
  lib/player.js
Labels: type: bug, priority: P2

#6975 feat: Export addFont method
  lib/player.js
Labels: type: enhancement, priority: P3

#6974 feat(DASH): Support DVB fonts with relative urls
  demo/common/assets.js
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#6976 fix: Fix iteration of document.fonts
  externs/font_face_set.js
  lib/player.js
Labels: type: bug, priority: P3

#6951 fix(HLS): Add HLS_EMPTY_MEDIA_PLAYLIST error
  lib/hls/hls_parser.js
  lib/util/error.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#6993 chore: Move CueRegion to its own file
  build/types/core
  lib/text/cue.js
  lib/text/cue_region.js
Labels: type: code health, priority: P2

#6992 feat: Add public method for parsing cue payload
  lib/text/cue.js
  lib/text/mp4_vtt_parser.js
  lib/text/vtt_text_parser.js
Labels: type: enhancement, component: captions/subtitles, priority: P3

#6990 fix(UI): Show the ad marker in the seek bar when there are some intersections
  lib/ads/interstitial_ad_manager.js
  ui/seek_bar.js
Labels: type: bug, component: UI, component: ads, priority: P2

#6988 fix(Xbox): Fix screen resolution detection
  lib/util/platform.js
Labels: type: bug, priority: P1, platform: Xbox

#6953 feat: Allow set the videoContainer in the Player constructor
  lib/player.js
  test/offline/storage_integration.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6978 feat(HLS): Deprecate useSafariBehaviorForLive config
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/player.js
  lib/util/player_configuration.js
  test/ads_integration.js
  test/hls/hls_live_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6986 fix: Offset text regions that are out of viewport
  lib/text/ui_text_displayer.js
  test/text/text_displayer_layout_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6987 fix(HLS): A/V sync regression for HLS live
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#6989 fix(HLS): Fix parsing of width and height when using media playlist
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
Labels: type: bug, component: HLS, priority: P1

#6997 docs: Add documentation about screen resolution detection
  docs/tutorials/index.json
  docs/tutorials/screen-resolution-detection.md
Labels: type: docs, priority: P3

#6998 feat: Parse TS frameRate
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
  lib/util/ts_parser.js
Labels: type: enhancement, priority: P3

#6991 feat(Ads): Allow the use of custom interstitials ads
  externs/shaka/ads.js
  externs/shaka/player.js
  lib/ads/ad_manager.js
  lib/ads/interstitial_ad_manager.js
  lib/player.js
  lib/util/error.js
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#6999 fix: Fix bad warning when use selectAudioLanguage
  lib/player.js
Labels: type: bug, priority: P2

#7003 fix(Prefetch): Use the same references time for evict and prefetchSegmentsByTime
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#6745 feat(DASH): Add support for urn:mpeg:dash:ssr:2023 with SegmentTemplate $Number$
  lib/dash/segment_template.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_segment_template_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#7004 fix: Avoid reset iterator when seek into the buffer
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#7010 fix: Disable seek retry cooldown on most platforms
  lib/media/playhead.js
  lib/util/platform.js
  test/media/playhead_unit.js
Labels: type: bug, priority: P1

#7012 fix(HLS): Fix load AES media playlist
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_integration.js
  test/test/assets/hls-aes-256/index.m3u8
Labels: type: bug, component: HLS, priority: P2

#7006 fix(HLS): Propagate bandwidth to stream in audio-only and video-only
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#7015 fix(HLS): A/V sync regression for HLS with different segment sizes
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#7017 fix(UI): Show all resolutions when there are only one audio.
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#7018 feat(UI): Add chapter button
  build/types/ui
  docs/tutorials/ui-customization.md
  shaka-player.uncompiled.js
  ui/chapter_selection.js
  ui/enums.js
  ui/less/overflow_menu.less
  ui/locales/en.json
  ui/locales/es.json
  ui/locales/fr.json
  ui/locales/source.json
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P4

#7021 chore: Move convertToTextTrackCue_ to shaka.text.Utils
  lib/text/simple_text_displayer.js
  lib/text/text_utils.js
Labels: type: code health, component: captions/subtitles, priority: P2

#7024 fix(CEA): Offset text CEA-608 that are out of viewport
  lib/cea/cea608_memory.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7022 feat(CEA): Support alignment in CEA-608
  lib/cea/cea608_data_channel.js
  lib/cea/cea608_memory.js
Labels: type: enhancement, component: captions/subtitles, priority: P2

#7028 chore: Remove console.log
  lib/text/mp4_ttml_parser.js
Labels: priority: P1

#7027 fix(UI): Fix seek preview time in VoD
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#7032 fix(PeriodCombiner): Use normalized codec to remove duplicates
  lib/util/periods.js
Labels: type: bug, priority: P2, component: DASH

#7029 fix(DASH): Fix transitions from 'dynamic' to 'static'
  lib/dash/dash_parser.js
Labels: type: bug, priority: P2, component: DASH

#7033 docs: Extract the current defaults config values into the config documentation
  externs/shaka/player.js
Labels: type: docs, priority: P3

#7038 chore: Add native cue to shaka cue mapping
  lib/text/text_utils.js
  test/text/text_utils_unit.js
Labels: component: captions/subtitles, priority: P2

#6985 feat: Render native cues using text displayer
  lib/media/media_source_engine.js
  lib/player.js
  test/media/media_source_engine_unit.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#7039 fix(DASH): Improve memory usage with live streams
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#7042 fix(Transmuxer): Fix init segment between discontinuities
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
Labels: type: bug, priority: P1, component: transmuxer

#7043 fix(UI): Fix resolution label when the stream has not resolution
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P1

#7045 fix(DASH): Prioritize highest bandwidth in PeriodCombiner
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P1, component: DASH

#7047 fix(ttml): Handle escaped special characters.
  lib/util/string_utils.js
  test/util/string_utils_unit.js
Labels: type: bug, component: TTML, priority: P1

#7049 fix: Fix MSE polyfill for iOS
  lib/polyfill/mediasource.js
Labels: type: bug, priority: P0, platform: iOS

#7050 fix: Fix skip interstitials with another ID but same URL
  externs/shaka/ads.js
  lib/ads/interstitial_ad_manager.js
  lib/hls/hls_parser.js
  lib/player.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: ads, priority: P2

#7052 feat(Ads): Add basic VAST support without IMA
  externs/shaka/ads.js
  lib/ads/ad_manager.js
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
  lib/ads/media_tailor_ad.js
  lib/text/cue.js
  lib/text/sbv_text_parser.js
  lib/text/vtt_text_parser.js
  lib/util/error.js
  lib/util/tXml.js
  lib/util/text_parser.js
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#7054 feat(Ads): Add basic VMAP support without IMA
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#7058 chore(HLS): Add mimeType to the segments
  lib/hls/hls_parser.js
Labels: component: HLS, priority: P2

#7061 fix: Allow reference mimeType change in StreamingEngine
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#7060 fix(HLS): Remove init segment on formats without init segment
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#7059 fix: Destroy correctly unused transmuxer
  lib/media/media_source_engine.js
Labels: type: bug, type: performance, priority: P2

#7064 docs: Update documentation
  README.md
  docs/tutorials/ad_monetization.md
  docs/tutorials/index.json
  roadmap.md
Labels: type: docs

#7071 test: Disable IMA tests
  test/ads_integration.js
Labels: component: tests

#7066 chore(Demo): Add boolean input to use IMA or our basic VAST/VMAP support
  demo/common/asset.js
  demo/custom.js
  demo/input.js
  demo/main.js
Labels: component: demo page, priority: P3

#7065 fix(DASH): Fix period combining when roles are equal
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P2, component: DASH

#7067 fix(ABR): Do not adapt between spatial & non spatial audio
  lib/media/adaptation_set.js
  test/media/adaptation_set_unit.js
Labels: type: bug, priority: P2

#7072 docs: Update maxAttempts documentation
  demo/config.js
  externs/shaka/net.js
Labels: type: docs

#7073 test: Add tests for our implementation of VAST and VMAP
  test/ads_integration.js
Labels: component: ads, component: tests

#7075 fix(DASH): Fix codec/mimeType for single text file
  lib/dash/dash_parser.js
Labels: type: bug, priority: P1, component: DASH

#7079 fix: Only check encryptionScheme when is not null and not empty string
  lib/util/stream_utils.js
  test/media/drm_engine_unit.js
Labels: type: bug, component: EME, priority: P1

#7078 fix: Disable CC with disableText config
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1, component: DASH

#7077 fix: Unify maxDisabledTime behaviour
  lib/media/streaming_engine.js
  lib/player.js
  test/media/streaming_engine_unit.js
Labels: type: bug, priority: P2

#7074 feat: Add getFetchedPlaybackInfo method
  externs/shaka/player.js
  lib/player.js
  test/cast/cast_utils_unit.js
Labels: type: enhancement, priority: P3

#7084 fix(Ads): Don't show duplicate SKIP UI in IMA CS
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/interstitial_ad.js
  lib/ads/media_tailor_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
  ui/skip_ad_button.js
Labels: type: bug, component: UI, component: ads, priority: P1

#7086 feat(DASH): Support Annex I: Flexible Insertion of URL Parameters
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/util/manifest_parser_utils.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#7091 fix(Ads): Fix timelineRange detection in HLS interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7089 fix(UI): Fix ad markers set before full initialization
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#7090 feat(ABR): Add preferNetworkInformationBandwidth config
  demo/config.js
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#6825 feat: Store bandwidth info inside references.
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/media/segment_reference.js
  lib/player.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/test/util/manifest_parser_util.js
  test/test/util/util.js
Labels: type: enhancement, priority: P3

#7092 fix(Ads): Fix playback of preroll interstitial when the currentTime is 0
  lib/ads/interstitial_ad_manager.js
  test/test/assets/hls-interstitial/main.m3u8
Labels: type: bug, component: ads, priority: P1

#7093 fix(Ads): Detect correctly interstitial preroll when using native HLS playback in Safari
  lib/player.js
Labels: type: bug, component: ads, priority: P2

#7095 fix(Ads): Fix back to live for native HLS when interstitial endTime is Infinity
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7096 fix(Ads): Only allow play the preroll once
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#7098 fix: Allow dispatch metadata event with cueTime equal to 0
  lib/player.js
Labels: type: bug, priority: P1

#7099 fix: Fix ID3 timing when included in EMSG
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#7102 fix(CEA): Always init CEA parser with new init segment
  lib/media/closed_caption_parser.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7104 fix(WebVTT): Re-add rollover logic
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, component: captions/subtitles, priority: P1, component: WebVTT

#7107 feat: Add width/height to getFetchedPlaybackInfo
  externs/shaka/player.js
  lib/player.js
Labels: type: enhancement
