Repository shaka-project/shaka-player, pull requests merged in 2024-02, with the labels that each got.

#6208 revert: Add chapter titles and dividers on the seek bar
  docs/tutorials/ui-customization.md
  ui/externs/ui.js
  ui/less/range_elements.less
  ui/seek_bar.js
  ui/ui.js
Labels: component: UI, priority: P1

#6188 feat!: Prefer MSE HLS over native HLS in Apple platform when not encrypted
  README.md
  demo/common/assets.js
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
  test/hls/hls_parser_integration.js
  test/player_unit.js
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, component: HLS, priority: P3, platform: macOS, browser: Safari, platform: iOS

#6203 docs: Add specific doc on UI localization strategies
  docs/tutorials/ui-customization.md
Labels: type: docs, priority: P3

#6211 fix: Fix gitpkg.now.sh dependencies
  package-lock.json
Labels: type: bug, priority: P0

#6180 feat: Detect maximum HW resolution automatically on some platforms
  externs/hisense.js
  externs/playstation.js
  externs/tizen.js
  externs/webos.js
  externs/xbox.js
  lib/cast/cast_receiver.js
  lib/player.js
  lib/util/platform.js
  lib/util/stream_utils.js
  test/cast/cast_receiver_unit.js
  test/player_unit.js
Labels: type: enhancement, platform: TV/STB, priority: P3, platform: Cast, platform: WebOS, platform: Tizen, platform: Playstation 4, platform: Playstation 5

#6172 feat: vod dynamic playback rate buffer control
  demo/config.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#5897 feat: Add preload system to player
  build/types/core
  demo/asset_card.js
  demo/common/asset.js
  demo/custom.js
  demo/front.js
  demo/main.js
  demo/search.js
  lib/media/drm_engine.js
  lib/media/manifest_filterer.js
  lib/media/preload_manager.js
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/error.js
  test/cast/cast_utils_unit.js
  test/player_integration.js
  test/player_load_graph_integration.js
  test/player_unit.js
Labels: type: enhancement, type: performance, priority: P2

#6222 fix(preload): Only start preload if manager exists
  demo/asset_card.js
  lib/player.js
Labels: type: bug

#6238 fix(preload): Fix timing of call to stopQueuingLatePhaseQueuedOperations
  lib/player.js
  test/player_unit.js
Labels: type: bug

#6246 fix: don't double wrap URIs for HLS key requests
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6250 fix: Fix detection of flac support on Safari
  AUTHORS
  CONTRIBUTORS
  lib/util/stream_utils.js
Labels: type: bug, priority: P1, browser: Safari

#6252 feat(text): Add time context to modifyCueCallback
  externs/shaka/text.js
  lib/text/text_engine.js
  test/text/text_engine_unit.js
Labels: type: enhancement, component: captions/subtitles

#6014 perf: Optimize init segment reference comparison for common case
  lib/media/segment_reference.js
Labels: type: bug, priority: P2

#6121 fix(DASH): Use labels to stitch streams across periods
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P2, component: DASH

#6207 feat: Add config to set live stream duration to Infinity
  demo/config.js
  externs/shaka/player.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P2

#6287 fix(VTT): fix setting textShadow when multiple CSS classes provided
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, priority: P2, component: WebVTT

#6295 fix(HLS): Ban unsupported combinations of SAMPLE-AES encryption
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#6296 chore: Add createDrmInfoFromClearKeys and simplify DrmEngine
  lib/media/drm_engine.js
  lib/util/manifest_parser_utils.js
Labels: component: EME, priority: P2, component: ClearKey

#6298 fix: Fix ENCA box parsing
  lib/media/segment_utils.js
  lib/util/mp4_parser.js
Labels: type: bug, priority: P1

#6309 fix: Fix SAR when transmuxing
  lib/transmuxer/h264.js
  lib/transmuxer/h265.js
Labels: type: bug, priority: P1, component: transmuxer

#6312 fix: Fix compiler issue in Mp4BoxParsers
  lib/util/mp4_box_parsers.js
Labels: type: bug, priority: P1

#6308 feat(HLS): Add automatically keyId-key for identity format
  README.md
  karma.conf.js
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
  lib/util/manifest_parser_utils.js
  lib/util/mp4_box_parsers.js
  test/hls/hls_parser_integration.js
  test/hls/hls_parser_unit.js
  test/test/assets/hls-sample-aes/audio.mp4
  test/test/assets/hls-sample-aes/index.m3u8
  test/test/assets/hls-sample-aes/key.key
  test/test/util/manifest_generator.js
Labels: type: enhancement, component: HLS, priority: P3
