Repository shaka-project/shaka-player, pull requests merged in 2024-08, with the labels that each got.

#7157 fix: Defer `closeSegmentIndex()` for old streams during ABR switches when segment fetches are ongoing
  lib/media/streaming_engine.js
  test/media/streaming_engine_unit.js
  test/test/util/manifest_generator.js
Labels: type: enhancement, priority: P1, component: DASH, platform: Cast

#7147 fix: Repeated initial segment load & cancellations
  AUTHORS
  CONTRIBUTORS
  lib/media/video_wrapper.js
Labels: type: bug, priority: P2

#7153 fix(ABR): Fix restrictToElementSize running while abr disabled
  AUTHORS
  CONTRIBUTORS
  lib/abr/simple_abr_manager.js
Labels: type: bug, priority: P2

#7170 feat(preload): Add isPreload to net filter context
  externs/shaka/manifest_parser.js
  externs/shaka/net.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/drm_engine.js
  lib/media/preload_manager.js
  lib/media/streaming_engine.js
  lib/mss/mss_parser.js
  lib/player.js
  test/dash/dash_parser_live_unit.js
  test/media/drm_engine_unit.js
  test/test/util/fake_networking_engine.js
Labels: type: enhancement, priority: P3, component: networking

#7173 chore(Demo): Save all asset info in the URL
  demo/common/asset.js
  demo/main.js
Labels: component: demo page, priority: P3

#7172 test: Update SAMPLE-AES test asset
  test/hls/hls_parser_integration.js
  test/test/assets/hls-sample-aes/audio.mp4
  test/test/assets/hls-sample-aes/index.m3u8
  test/test/assets/hls-sample-aes/key.key
Labels: type: code health, component: tests

#7171 chore: Detect segmentDuration mismatch
  lib/media/media_source_engine.js
Labels: type: code health

#7168 fix: Apply playRange config to src=
  lib/player.js
  test/player_src_equals_integration.js
Labels: type: bug, priority: P2

#7167 fix: Fire the correct error code in src= mode in some situations
  lib/player.js
Labels: type: bug, priority: P2

#7181 fix: Add more info in getVariantTracks for muxed streams
  lib/util/stream_utils.js
Labels: type: bug, priority: P2

#7180 fix(DASH): Allow play all time fastSwitching tracks
  externs/shaka/abr_manager.js
  lib/abr/simple_abr_manager.js
  lib/media/preload_manager.js
  lib/media/segment_prefetch.js
  lib/player.js
Labels: type: bug, priority: P2, component: DASH

#7179 fix(DASH): Fix allPartialSegments signal when using L3D
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#7114 fix: Adjust timing of mediaqualitychanged event when safe margin is set
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#7182 fix(UI): Fix display seekbar and time when the seekrange is infinite
  ui/presentation_time.js
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#7166 fix(HLS): Fix use of EXT-X-MEDIA when not using Content Steering
  lib/hls/hls_classes.js
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#7183 chore(Demo): Improve media session data with metadata events
  demo/main.js
Labels: component: demo page, priority: P3

#7191 test: Update Firefox Mac screenshots
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-align-center-long.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-align-end-long.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-align-start-long.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-bold-long.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-italic-long.png
Labels: component: tests

#7149 fix(net): Remove `AbortController` polyfill
  build/conformance.textproto
  build/types/polyfill
  lib/hls/hls_parser.js
  lib/polyfill/abort_controller.js
  lib/util/abortable_operation.js
  shaka-player.uncompiled.js
Labels: type: bug, priority: P2, component: networking

#7189 fix: Fix ended state in stateHistory
  lib/player.js
Labels: type: bug, priority: P2

#7190 fix(UI): Only show frame rate if there are several frame rates
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#7188 feat(UI): Add MediaSession management
  demo/main.js
  externs/mediasession.js
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#7055 feat(DASH): MPD Alternate support
  externs/shaka/ads.js
  karma.conf.js
  lib/ads/ad_manager.js
  lib/ads/interstitial_ad_manager.js
  lib/player.js
  test/ads_integration.js
  test/test/assets/dash-mpd-alternate/0001.m4s
  test/test/assets/dash-mpd-alternate/0002.m4s
  test/test/assets/dash-mpd-alternate/0003.m4s
  test/test/assets/dash-mpd-alternate/0004.m4s
  test/test/assets/dash-mpd-alternate/0005.m4s
  test/test/assets/dash-mpd-alternate/dash.mpd
  test/test/assets/dash-mpd-alternate/init.mp4
  test/test/util/fake_ad_manager.js
Labels: type: enhancement, priority: P3, component: DASH

#7195 chore(Demo): Add more demo assets
  demo/common/assets.js
Labels: type: enhancement, component: demo page, priority: P4

#7197 test: Fix FakeSegmentIndex implementation
  test/media/streaming_engine_unit.js
  test/test/util/simple_fakes.js
  test/test/util/streaming_engine_util.js
Labels: component: tests

#7196 feat(Ads): Added advanced type to ad requests
  lib/ads/interstitial_ad_manager.js
  lib/ads/media_tailor_ad_manager.js
  lib/net/networking_engine.js
Labels: type: enhancement, component: ads, priority: P3

#7194 fix(DASH): Fix EventStream Elements creation
  lib/util/tXml.js
Labels: type: bug, type: performance, priority: P1, component: DASH

#7198 feat: Dispatch MediaSourceRecovered event
  lib/player.js
  lib/util/fake_event.js
Labels: type: enhancement, priority: P3

#7200 fix: Do not minify CodecSwitchingStrategy enum keys
  lib/config/codec_switching_strategy.js
Labels: type: bug, priority: P2

#7184 fix: Add null check for current reference
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#7201 fix: Fix normalized codec for VVC
  lib/util/mime_utils.js
  test/util/mime_utils_unit.js
Labels: type: bug, priority: P3

#7205 docs: Add missing link to README
  README.md
Labels: type: docs

#7204 feat: Add video codec preference array at same resolution and bitrate
  lib/util/stream_utils.js
  test/player_unit.js
  test/util/stream_utils_unit.js
Labels: type: enhancement, priority: P3

#7208 fix(HLS): Check that segment 0 exists
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#7207 fix: Dont use inaccurateManifestTolerance for sequenceMode
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P2

#7209 fix(HLS): Calculate the delay based on the sum of the segment lengths
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P2

#7212 fix: Fix support for Dolby Vision based in VVC
  lib/cea/mp4_cea_parser.js
  lib/media/content_workarounds.js
  lib/media/segment_utils.js
  lib/media/streaming_engine.js
  lib/util/mime_utils.js
  lib/util/stream_utils.js
  test/util/mime_utils_unit.js
Labels: type: bug, priority: P3

#7216 feat(CMCD): Implement new streaming format from CMCDv2
  lib/player.js
  lib/util/cmcd_manager.js
Labels: type: enhancement, priority: P3

#7217 fix: Correct the behavior to defer closeSegmentIndex() calls during updates
  lib/media/streaming_engine.js
  test/media/streaming_engine_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: priority: P1, component: DASH, platform: Cast

#7219 fix: Dont use trick play track for liveSync feature
  lib/player.js
Labels: type: bug, priority: P2

#7223 fix(Stats): Fix bytesDownloaded when using src=
  lib/player.js
Labels: type: bug, priority: P3

#7218 fix(DASH): Fix MPD Patch when SegmentTemplate is shared between Representations
  lib/dash/dash_parser.js
  lib/util/tXml.js
  test/dash/dash_parser_patch_unit.js
  test/util/tXml_unit.js
Labels: type: bug, priority: P1, component: DASH

#7224 feat(DASH): Support trick-mode per resolution
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#7227 chore(Demo): Add DASH-IF trick mode assets
  demo/common/assets.js
Labels: component: demo page

#7228 chore(Demo): Fix VNOVA asset features
  demo/common/assets.js
Labels: component: demo page

#7229 fix(DASH): Fix creation of multiperiod trickmode streams
  lib/util/periods.js
Labels: type: bug, priority: P1, component: DASH

#7234 fix: Allow recover normal stream when trick play stream fails
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#7236 chore(Demo): Remove duplicate asset
  demo/common/assets.js
Labels: component: demo page

#7235 fix: Don't throw an error when trying to disable a trick mode stream
  lib/player.js
Labels: type: bug, priority: P1

#7240 fix(DASH): Use proper namespace when mapping TXml node to Element
  lib/util/tXml.js
  test/util/tXml_unit.js
Labels: type: bug, priority: P1, component: DASH

#7239 fix: Revert change that caused a lot of warning with "cannot find endTime" and hls playback errors
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#7230 feat(HLS): Add I-Frame playlist support
  README.md
  demo/common/assets.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/util/stream_utils.js
  roadmap.md
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3
