Repository shaka-project/shaka-player, pull requests merged in 2024-11, with the labels that each got.

#7532 feat: Add safeSeekEndOffset feature for live reposition
  demo/config.js
  externs/shaka/player.js
  lib/media/playhead.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#7534 fix(UI): Disable fullscreen button conditionally when playing ads
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
  lib/ads/media_tailor_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
  ui/controls.js
  ui/fullscreen_button.js
Labels: type: bug, component: UI, component: ads, priority: P2, platform: iOS

#7536 test: Enable AC-3 and EC-3 in Edge Windows
  test/test/util/util.js
Labels: platform: Windows, browser: Edge, component: tests

#7529 fix: Install polyfills for Comcast X1 devices
  lib/polyfill/media_capabilities.js
  lib/polyfill/mediasource.js
  lib/util/platform.js
Labels: type: enhancement, platform: TV/STB, priority: P4

#7535 ci: Run "Build and Test" every midnight PST / 8am UTC
  .github/workflows/build-and-test.yaml
Labels: type: CI

#7539 fix: Allow show subtitles using webkit Fullscreen API when playing native HLS
  lib/player.js
Labels: type: bug, component: captions/subtitles, priority: P2, platform: iOS

#7533 feat(preload): Wait for prefetches when preloading
  lib/media/preload_manager.js
  lib/media/segment_prefetch.js
  test/test/util/fake_segment_prefetch.js
Labels: type: bug, type: enhancement

#7541 fix(UI): Fix name for Dolby Digital Plus
  ui/language_utils.js
Labels: type: bug, component: UI, priority: P2

#7538 fix(Ads): Allow play interstitials on iOS fullscreen
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2, platform: iOS

#7540 feat(UI): Allow configure the fullscreen mode in VisionOS
  lib/util/platform.js
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#7548 chore: Simplify and remove optional parameters in AdaptationSetCriteria to avoid future problems
  lib/media/adaptation_set_criteria.js
  lib/media/preload_manager.js
  lib/player.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: code health

#7550 fix(Ads): Allow play interstitials using single video element when use native HLS
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7554 chore(Demo): Update Demo bug template
  demo/autoTemplate.txt
Labels: component: demo page

#7552 chore(docs): Update FAQ to mention a HLS out of sync on some cases
  docs/tutorials/faq.md
Labels: type: docs

#7545 chore: Re-enable Shaka Player History live stream
  demo/common/assets.js
Labels: component: demo page

#7558 ci: Test Opera against macos-latest
  .github/workflows/build-and-test.yaml
Labels: type: CI

#7559 fix(WebVTT): Fix display italic subtitles with end align
  lib/text/cue.js
Labels: type: bug, priority: P2, component: WebVTT

#7560 fix(UI): Fix "Live" label in some languages
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#7561 ci: Add timeouts to avoid hangs on "Build and Test" workflow
  .github/workflows/build-and-test.yaml
Labels: type: CI

#7563 fix: Do not reuse the same tsParser for different contentType
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#7557 perf: Improve performance when parsing EMSG
  demo/config.js
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/player_configuration.js
  test/cast/cast_utils_unit.js
  test/media/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
Labels: type: performance

#7574 ci: Fix status reporting on PRs
  .github/workflows/selenium-lab-tests.yaml
  .github/workflows/update-screenshots.yaml
Labels: type: CI

#7586 ci: Fix auto-branch job
  .github/workflows/release-please.yaml
Labels: type: CI

#7569 fix: Prefer SimpleTextDisplayer on iOS
  lib/player.js
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P2, platform: iOS

#7575 chore(Demo): Change manifest.dash.clockSyncUri in the Demo
  demo/main.js
Labels: component: demo page, type: performance

#7578 fix: Allow the user to disable subtitles while paused
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7579 fix: Disable live sync when the stream is paused
  lib/player.js
Labels: type: bug, priority: P1

#7581 test: Update mpd alternate asset to avoid gaps and issues with the ad
  test/test/assets/dash-mpd-alternate/dash.mpd
Labels: component: tests

#7583 fix(Ads): Always set endTime for MPD Alternate
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7584 fix(Ads): Always fire CUEPOINTS_CHANGED when not using multi video elements
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7585 fix(Ads): Prevent playing the same ad twice
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7519 fix(DASH): Fix playback after DASH period eviction
  externs/shaka/manifest_parser.js
  lib/dash/dash_parser.js
  lib/media/streaming_engine.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_patch_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
  test/util/content_steering_manager_unit.js
Labels: type: bug, priority: P2, component: DASH

#7589 test: Add unit tests for DASH period eviction
  test/util/periods_unit.js
Labels: component: tests

#7593 fix(Ads): Fix VAST_INVALID_XML error code
  lib/util/error.js
Labels: type: bug, component: ads, priority: P1

#7596 feat: Add new error code for missing EME support
  build/types/polyfill
  docs/tutorials/plugins.md
  lib/media/drm_engine.js
  lib/player.js
  lib/polyfill/patchedmediakeys_nop.js
  lib/util/error.js
  shaka-player.uncompiled.js
Labels: type: enhancement, component: EME, priority: P4

#7592 ci: Switch to use macos-latest
  .github/workflows/build-and-test.yaml
Labels: type: CI

#7603 fix(DASH): Fix playback after DASH period eviction
  externs/shaka/manifest_parser.js
  lib/dash/dash_parser.js
  lib/media/streaming_engine.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/dash_parser_patch_unit.js
  test/dash/dash_parser_segment_base_unit.js
  test/dash/dash_parser_segment_list_unit.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/dash_parser_util.js
  test/test/util/mss_parser_util.js
  test/util/content_steering_manager_unit.js
  test/util/periods_unit.js
Labels: type: bug, priority: P1, component: DASH

#7605 fix: Calculate timeToFirstByte before fire the event 'downloadheadersreceived'
  lib/net/networking_engine.js
Labels: type: bug, priority: P3, component: networking

#7609 feat: Add 'downloadcompleted' event
  lib/net/networking_engine.js
  lib/player.js
  lib/util/fake_event.js
  test/util/cmcd_manager_unit.js
Labels: type: enhancement, priority: P3, component: networking

#7614 fix: Disable smooth codec switch on Tizen 8
  lib/util/platform.js
Labels: type: bug, priority: P2, platform: Tizen

#7619 fix: Silence aborted errors from PreloadManager.
  lib/media/preload_manager.js
Labels: type: bug, priority: P1

#7616 feat: Update usage of minBufferTime according to the DASH spec
  docs/tutorials/faq.md
  docs/tutorials/manifest-parser.md
  docs/tutorials/network-and-buffering-config.md
  externs/shaka/manifest.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/playhead.js
  lib/media/streaming_engine.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/player.js
  test/dash/dash_parser_manifest_unit.js
  test/media/playhead_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/offline/storage_compatibility_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P2, component: DASH

#7621 fix(Ads): Disable interstitials when playing an interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#7622 test: Simplification of "HlsParser supports text discontinuity"
  test/hls/hls_parser_integration.js
  test/test/assets/hls-text-offset/playlist-video.m3u8
  test/test/assets/hls-text-offset/playlist-vtt.m3u8
Labels: component: tests

#7623 chore: Convert IAbortableOperation to ES6
  externs/shaka/abortable.js
Labels: type: code health, priority: P3

#7624 fix: Abort operations only once
  lib/util/abortable_operation.js
Labels: type: bug, priority: P2

#7630 fix: cache source buffer params on codec switch reload
  AUTHORS
  CONTRIBUTORS
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1

#7632 fix: Fix cast support for HLG HDR
  .eslintrc.js
  lib/polyfill/media_capabilities.js
  package-lock.json
  package.json
Labels: type: bug, priority: P2, platform: Cast

#7628 fix(Cast): Incorrect detection of MediaCapabilities on Linux Chromecast
  lib/polyfill/media_capabilities.js
  test/polyfill/media_capabilities_unit.js
Labels: type: bug, priority: P1, platform: Cast

#7617 feat: Stop setting playbackRate to 0 to control buffering state when streaming.rebufferingGoal = 0
  demo/config.js
  docs/tutorials/config.md
  externs/shaka/player.js
  lib/media/buffering_observer.js
  lib/player.js
  lib/util/player_configuration.js
  test/player_unit.js
Labels: type: enhancement, priority: P1

#7626 ci: Add new shaka-bot commands
  .github/workflows/shaka-bot-commands/command-help.sh
  .github/workflows/shaka-bot-commands/command-test.sh
Labels: type: CI

#7636 fix: Disable smooth codec switch on webOS 6
  lib/util/platform.js
  test/util/platform_unit.js
Labels: type: bug, priority: P2, platform: WebOS

#7638 feat(Demo): Display unhandled rejections in demo
  demo/main.js
Labels: type: enhancement, component: demo page, priority: P3

#7637 fix(PS5): Prevent uncaught promise rejections when requests are aborted
  lib/util/abortable_operation.js
Labels: type: bug, priority: P2, platform: Playstation 5

#7641 fix(HLS): Fix playback of raw AAC
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#7644 feat(UI): Add config to show the audio codec in the audio selector
  ui/audio_language_selection.js
  ui/externs/ui.js
  ui/language_utils.js
  ui/text_selection.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#7643 fix(UI): Do not show codec name when the same codec is used for the same language
  ui/language_utils.js
Labels: type: bug, component: UI, priority: P2

#7645 fix: Fix normalized codec for VP9
  lib/util/mime_utils.js
  test/util/mime_utils_unit.js
Labels: type: bug, priority: P3

#7642 docs(Ads): Add new use case to Ads documentation
  docs/tutorials/ad_monetization.md
Labels: type: docs, component: ads

#7647 fix: Fix CBCS support in recent WebOS
  package-lock.json
  package.json
Labels: type: bug, component: EME, priority: P2, platform: WebOS

#7648 chore: Forbid using instanceof on arrays
  build/eslint-plugin-shaka-rules/array-no-instanceof.js
  build/eslint-plugin-shaka-rules/index.js
  test/test/util/manifest_parser_util.js
  test/test/util/ttml_utils.js
Labels: type: code health, priority: P3

#7651 feat: Add basic support for the Common Access Token
  lib/net/networking_engine.js
  lib/player.js
  test/test/util/fake_networking_engine.js
Labels: type: enhancement, priority: P3, component: networking

#7652 fix(Ads): Fix usage of ENABLE-SKIP-FOR in Interstitals
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7658 fix(UI): Change to use legacy css format to support old TVs
  .csslintrc
  demo/demo.less
  ui/less/ad_controls.less
  ui/less/buttons.less
  ui/less/containers.less
  ui/less/overflow_menu.less
  ui/less/thumbnails.less
  ui/less/tooltip.less
Labels: type: bug, component: UI, priority: P2

#7657 feat(Ads): Add support for overlay interstitials (or non-linear ads)
  build/conformance.textproto
  docs/tutorials/ad_monetization.md
  externs/shaka/ads.js
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
Labels: type: enhancement, component: ads, priority: P3

#7659 fix(Ads): Fix ad position by default
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7660 fix(Ads): Fix unnecessary request when using VAST
  docs/tutorials/ad_monetization.md
  externs/shaka/ads.js
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7654 fix: Fix video progress events accuracy
  build/types/core
  lib/player.js
  lib/util/number_utils.js
  test/util/number_utils_unit.js
Labels: type: bug, priority: P2

#7663 fix(Ads): Fix post-roll playback
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#7662 fix(Ads): Fix id of X-ASSET-LIST
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#7653 fix: Forbid usage of instanceof ArrayBuffer
  build/eslint-plugin-shaka-rules/buffersource-no-instanceof.js
  build/eslint-plugin-shaka-rules/index.js
  lib/cast/cast_utils.js
  lib/net/http_xhr_plugin.js
  lib/util/buffer_utils.js
  lib/util/object_utils.js
  lib/util/uint8array_utils.js
  test/test/util/canned_idb.js
Labels: type: bug, priority: P3

#7669 fix: Fix playback on Apple devices without ManagedMediaSource
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1, browser: Safari, platform: iOS

#7667 fix(Ads): Fix behavior when user JUMPS across more than one interstitial
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#7668 fix(HLS): Ignore errors when try to detect CC
  lib/media/segment_utils.js
Labels: type: bug, component: HLS, priority: P1

#7672 test(Ads): Add basic Interstitials unit tests
  test/ads/interstitial_ad_manager_unit.js
Labels: component: tests

#7677 fix(Ads): Fix usage of ENABLE-SKIP-AFTER and ENABLE-SKIP-FOR
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#7676 chore: Remove code duplication in shaka.media.Capabilities
  lib/media/media_source_capabilities.js
Labels: type: code health, priority: P3

#7674 test(Ads): Add more basic Interstitials unit tests
  lib/ads/interstitial_ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: component: tests

#7679 test: Remove some flaky integration test covered with unit tests
  test/ads_integration.js
Labels: component: tests

#7678 fix: Detect smooth codec switch support on Apple devices
  externs/managedmediasource.js
  lib/media/media_source_capabilities.js
Labels: type: bug, priority: P2, platform: macOS, browser: Safari, platform: iOS

#7681 fix(HLS): Fix subtitle timing when no discontinuity but there is X-TIMESTAMP-MAP
  lib/media/media_source_engine.js
  lib/text/vtt_text_parser.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P2

#7686 fix(Ads): Avoid skip interstitial when is not allowed
  lib/ads/interstitial_ad.js
Labels: type: bug, component: ads, priority: P1

#7689 chore(Ads): Simplify quartile management in Interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: code health, component: ads, priority: P2

#7690 fix: Fix unload call after destroy
  lib/player.js
Labels: type: bug, priority: P1

#7687 test(Ads): Add more basic Interstitials unit tests
  test/ads/interstitial_ad_manager_unit.js
Labels: component: tests

#7694 docs: Fix missing parameter in "Monetization with Ads" tutorial
  docs/tutorials/ad_monetization.md
Labels: type: docs

#7682 fix: Timeout unfulfilled request to decodingInfo and requestMediaKeySystemAccess
  lib/media/drm_engine.js
  lib/util/functional.js
  lib/util/stream_utils.js
  test/util/functional_unit.js
Labels: type: bug, priority: P2, platform: Android

#7695 fix(Ads): Don't dispatch cue points changed if it is an overlay
  lib/ads/interstitial_ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: bug, component: ads, priority: P2

#7412 feat: CMCD v2 LTC and MSD keys
  AUTHORS
  CONTRIBUTORS
  demo/config.js
  externs/cmcd.js
  externs/shaka/player.js
  lib/player.js
  lib/util/cmcd_manager.js
  lib/util/player_configuration.js
  test/cast/cast_utils_unit.js
  test/player_unit.js
  test/util/cmcd_manager_unit.js
Labels: type: enhancement, priority: P3, component: CMCD

#7696 fix(Ads): Avoid adding custom interstitials without URI
  lib/ads/interstitial_ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: bug, component: ads, priority: P2

#7697 fix(Ads): Don't try to play Image and HTML overlay interstitials
  lib/ads/interstitial_ad_manager.js
  lib/net/networking_utils.js
Labels: type: bug, component: ads, priority: P2
