Repository shaka-project/shaka-player, pull requests merged in 2024-04, with the labels that each got.

#6360 fix(transmuxer): Support raw AAC with TS extension
  karma.conf.js
  lib/transmuxer/ts_transmuxer.js
  test/test/assets/hls-ts-raw-aac/fileSequence0.ts
  test/test/assets/hls-ts-raw-aac/fileSequence1.ts
  test/test/assets/hls-ts-raw-aac/fileSequence2.ts
  test/test/assets/hls-ts-raw-aac/fileSequence3.ts
  test/test/assets/hls-ts-raw-aac/index.m3u8
  test/test/assets/hls-ts-raw-aac/playlist.m3u8
  test/transmuxer/transmuxer_integration.js
Labels: type: bug, priority: P2, component: transmuxer

#6371 fix(HLS): getPlayheadTimeAsDate() differs from X-EXT-PROGRAM-DATE-TIME
  lib/hls/hls_parser.js
  lib/media/presentation_timeline.js
  lib/player.js
  test/player_unit.js
Labels: type: bug, component: HLS, priority: P2

#6384 fix: Disable smooth codec switching in Edge Windows
  lib/util/platform.js
Labels: type: bug, priority: P1, platform: Windows, browser: Edge

#6385 fix: Add Opus and AV1 detection in TS
  lib/media/segment_utils.js
  lib/util/ts_parser.js
Labels: type: bug, priority: P3

#6383 feat(HLS): Create segmentIndex when there is only one variant
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6390 fix: Add LOAS-AAC detection in TS
  lib/media/segment_utils.js
  lib/util/ts_parser.js
Labels: type: bug, priority: P3

#6389 fix(HLS): Fix IAMF codec selection in HLS
  lib/util/manifest_parser_utils.js
Labels: type: bug, component: HLS, priority: P3

#6214 feat: Add unloadAndSavePreload
  lib/media/preload_manager.js
  lib/player.js
  test/cast/cast_utils_unit.js
  test/player_integration.js
Labels: type: enhancement, priority: P3

#6382 fix: Reject TS content on all platforms and transmux always
  lib/media/media_source_engine.js
  lib/polyfill/mediasource.js
Labels: type: bug, priority: P1

#6386 feat(UI): Add config for refreshTickInSeconds
  AUTHORS
  CONTRIBUTORS
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#6398 docs: Update HLS info in README
  README.md
Labels: type: docs

#6397 fix(WebVTT): Remove rollover logic because we always transmux TS
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P1, component: WebVTT

#6395 fix(TTML): Fix trim surrounding spaces with xml:space="default"
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: type: bug, component: TTML, priority: P2

#6394 fix(WebVTT): Fix multiline colored VTT subtitles
  lib/util/tXml.js
  test/text/vtt_text_parser_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2, component: WebVTT

#6388 fix(HLS): Reset textSequenceModeOffset on discontinuity
  karma.conf.js
  lib/media/media_source_engine.js
  test/hls/hls_parser_integration.js
  test/test/assets/hls-text-offset/index.m3u8
  test/test/assets/hls-text-offset/playlist-video.m3u8
  test/test/assets/hls-text-offset/playlist-vtt.m3u8
  test/test/assets/hls-text-offset/video-0000000069.ts
  test/test/assets/hls-text-offset/video-0000000070.ts
  test/test/assets/hls-text-offset/video-0000000071.ts
  test/test/assets/hls-text-offset/video-0000000072.ts
  test/test/assets/hls-text-offset/video-0000000073.ts
  test/test/assets/hls-text-offset/video-069.ts
  test/test/assets/hls-text-offset/video-070.ts
  test/test/assets/hls-text-offset/video-071.ts
  test/test/assets/hls-text-offset/video-072.ts
  test/test/assets/hls-text-offset/video-073.ts
  test/test/assets/hls-text-offset/vtt-069.vtt
  test/test/assets/hls-text-offset/vtt-070.vtt
  test/test/assets/hls-text-offset/vtt-071.vtt
  test/test/assets/hls-text-offset/vtt-072.vtt
  test/test/assets/hls-text-offset/vtt-073.vtt
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P1, component: WebVTT

#6403 feat: Set updateIntervalSeconds to 0.1 by default for low latency streaming
  docs/tutorials/config.md
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6405 chore(ABR): Use EventManager for network change events
  lib/abr/simple_abr_manager.js
Labels: type: code health, priority: P2

#6399 fix(HLS): Avoid duplicate AES requests
  lib/hls/hls_parser.js
  test/hls/hls_parser_integration.js
  test/test/assets/hls-aes-256/media.m3u8
Labels: type: bug, component: HLS, priority: P2

#6406 fix(DASH): Set delay to 0 for LL streams
  lib/dash/dash_parser.js
Labels: type: bug, priority: P1, component: DASH

#6416 feat(DASH): Add signalling the last segment number in Period
  lib/dash/dash_parser.js
  lib/dash/segment_template.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#6419 feat(DASH): update period as part of configuration
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3, component: DASH

#6422 fix: Looser tolerance for ending trick play at edge of seek range.
  lib/player.js
Labels: type: bug, priority: P2

#6425 docs: Add FAQ entry about new versions.
  docs/tutorials/faq.md
Labels: type: docs, type: process

#6348 fix(DASH): Fix support for multi-mimeType variants
  externs/shaka/manifest.js
  externs/shaka/offline.js
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_index.js
  lib/media/streaming_engine.js
  lib/mss/mss_parser.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/mime_utils.js
  lib/util/periods.js
  lib/util/stream_utils.js
  test/dash/dash_parser_segment_template_unit.js
  test/hls/hls_parser_unit.js
  test/media/adaptation_set_unit.js
  test/media/drm_engine_unit.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
  test/offline/manifest_convert_unit.js
  test/player_unit.js
  test/test/util/manifest_generator.js
  test/test/util/simple_fakes.js
  test/test/util/streaming_engine_util.js
Labels: type: bug, priority: P1, component: DASH

#6426 fix(HLS): Fix labelling of captions in Safari
  lib/util/stream_utils.js
Labels: type: bug, component: HLS, priority: P2, browser: Safari

#6417 feat: Make getPlayheadTimeAsDate and getPresentationStartTimeAsDate available for VOD
  lib/hls/hls_parser.js
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6387 feat: Add Opus TS transmuxer
  README.md
  build/types/transmuxer
  karma.conf.js
  lib/transmuxer/opus.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/mp4_generator.js
  lib/util/ts_parser.js
  shaka-player.uncompiled.js
  test/test/assets/hls-ts-muxed-opus-h264/file1.ts
  test/test/assets/hls-ts-muxed-opus-h264/file2.ts
  test/test/assets/hls-ts-muxed-opus-h264/file3.ts
  test/test/assets/hls-ts-muxed-opus-h264/playlist.m3u8
  test/transmuxer/transmuxer_integration.js
Labels: type: enhancement, priority: P3, component: transmuxer

#6431 docs: Add note about the result of calling storage.store twice
  docs/tutorials/offline.md
Labels: type: docs, priority: P3

#6435 revert: Fix potential AV sync issues after seek or adaptation
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P1

#6402 fix(HLS): Fix SAMPLE-AES playback
  demo/common/assets.js
  lib/hls/hls_parser.js
  lib/media/drm_engine.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#6263 feat: Update for LCEVC Integration with new features added.
  docs/tutorials/lcevc.md
  package-lock.json
  package.json
Labels: type: enhancement, priority: P3

#6304 fix: Correct playhead when seek beyond seekRange
  lib/media/playhead.js
  test/media/playhead_unit.js
Labels: type: bug, priority: P2

#6438 feat: Parse colr box
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
Labels: type: enhancement, priority: P3

#6437 feat: Trigger an event with spatial video info
  externs/shaka/codecs.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/fake_event.js
  lib/util/mp4_box_parsers.js
Labels: type: enhancement, priority: P3

#6444 fix(Ads): Fix ad pausing when using customPlayheadTracker
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#6443 feat(Ads): Skip play detection in some devices
  demo/config.js
  externs/shaka/player.js
  lib/ads/client_side_ad_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: ads, priority: P3

#6449 fix: clear listeners when resetting media source
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1

#6455 docs: Update roadmap
  roadmap.md
Labels: type: docs

#6454 chore: Add backwards compatibility for useNativeHlsOnSafari
  demo/common/assets.js
  demo/config.js
  externs/shaka/player.js
  lib/player.js
  lib/util/player_configuration.js
  test/hls/hls_parser_integration.js
  test/player_unit.js
  test/transmuxer/transmuxer_integration.js
Labels: priority: P1

#6453 chore: Add backwards compatibility for "Remove DOM Parser"
  build/conformance.textproto
  build/types/core
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/ads/ad_manager.js
  lib/dash/dash_parser.js
  lib/mss/mss_parser.js
  lib/player.js
  lib/util/player_configuration.js
  lib/util/tXml.js
  lib/util/xml_utils.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/media/region_observer_unit.js
  test/media/region_timeline_unit.js
  test/mss/mss_parser_unit.js
Labels: priority: P1

#6462 test: Rewrite MediaSourceEngine codec switching tests
  test/media/media_source_engine_unit.js
Labels: priority: P1, component: tests

#6463 fix: Fix webOS 4 & 5 utility methods
  lib/util/platform.js
  test/util/platform_unit.js
Labels: type: bug, priority: P1

#6465 test: Remove bogus MediaSourceEngine test case
  test/media/media_source_engine_unit.js
Labels: component: tests

#6464 fix: Fix support of getAllThumbnails when using DASH multi-period
  lib/media/segment_index.js
Labels: type: bug, priority: P2, component: DASH

#6466 fix: Fix exceptions in StreamingEngine when reloading
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#6469 feat: Add bytesDownloaded to stats
  externs/shaka/player.js
  lib/net/networking_engine.js
  lib/player.js
  lib/util/stats.js
  test/player_integration.js
  ui/statistics_button.js
  ui/ui.js
Labels: type: enhancement, priority: P4

#6468 perf(DRM): pass `preferredKeySystems` to `filterManifest()`
  lib/media/manifest_filterer.js
  lib/offline/storage.js
  lib/util/stream_utils.js
Labels: type: performance, priority: P1

#6470 feat: Parse XPath
  externs/shaka/player.js
  lib/util/tXml.js
  test/util/tXml_unit.js
Labels: type: enhancement, priority: P3

#6473 fix: Do not use `replaceAll` in XPath parsing
  lib/util/tXml.js
Labels: type: bug, priority: P1

#6474 fix: Don't update captions when video is paused
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P2

#6475 chore: Remove useless loop in compiled mode
  lib/text/ui_text_displayer.js
Labels: component: captions/subtitles, priority: P2

#6476 fix: Fix reusing region elements in UITextDisplayer
  lib/text/ui_text_displayer.js
Labels: type: bug, component: TTML, component: captions/subtitles, priority: P1

#6450 feat(UI): UI support for VR content
  LICENSE
  README.md
  build/shaka-lab.yaml
  build/types/ui
  demo/asset_card.js
  demo/common/asset.js
  demo/common/assets.js
  demo/index.html
  demo/main.js
  demo/search.js
  docs/tutorials/ui-customization.md
  docs/tutorials/ui.md
  externs/device_sensor_event.js
  karma.conf.js
  lib/util/dom_utils.js
  lib/util/platform.js
  roadmap.md
  shaka-player.uncompiled.js
  test/test/assets/dash-vr/dash.mpd
  test/test/assets/dash-vr/init.mp4
  test/test/assets/dash-vr/segment_0.m4s
  test/test/assets/dash-vr/segment_1.m4s
  test/test/assets/dash-vr/segment_2.m4s
  test/test/assets/dash-vr/segment_3.m4s
  test/test/assets/dash-vr/segment_4.m4s
  test/test/assets/dash-vr/segment_5.m4s
  test/test/util/ui_utils.js
  test/ui/ui_customization_unit.js
  test/ui/vr_ui_integration.js
  ui/controls.js
  ui/enums.js
  ui/externs/ui.js
  ui/gl_matrix/matrix_4x4.js
  ui/gl_matrix/matrix_quaternion.js
  ui/less/containers.less
  ui/locales/en-GB.json
  ui/locales/en.json
  ui/locales/es-419.json
  ui/locales/es.json
  ui/locales/source.json
  ui/recenter_vr.js
  ui/toggle_stereoscopic.js
  ui/ui.js
  ui/vr_manager.js
  ui/vr_utils.js
  ui/vr_webgl.js
Labels: type: enhancement, component: UI, priority: P3

#6480 feat: Add encryptionScheme to shaka.extern.DrmInfo
  externs/shaka/manifest.js
  lib/dash/content_protection.js
  lib/hls/hls_parser.js
  lib/media/drm_engine.js
  lib/mss/content_protection.js
  lib/util/manifest_parser_utils.js
  test/dash/dash_parser_content_protection_unit.js
  test/hls/hls_parser_unit.js
  test/media/drm_engine_unit.js
  test/offline/manifest_convert_unit.js
  test/offline/storage_integration.js
  test/test/util/manifest_generator.js
Labels: type: enhancement, component: HLS, priority: P3, component: DASH, component: MSS

#6479 fix: Fix duplicate init segment download when using startAtSegmentBoundary
  lib/player.js
  test/player_unit.js
Labels: type: bug, priority: P2

#6478 fix: call to load in MediaElement using src= in HLS Safari
  lib/player.js
Labels: type: bug, priority: P2, browser: Safari

#6482 feat: Add encryptionScheme support on MCap polyfill
  lib/polyfill/media_capabilities.js
Labels: type: enhancement, priority: P3

#6483 fix: Fix encryptionScheme for FairPlay
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, priority: P1

#6496 fix: Fix deprecation warning for manifestPreprocessor that is always logged
  lib/dash/dash_parser.js
  lib/mss/mss_parser.js
  lib/util/player_configuration.js
Labels: type: bug, priority: P1

#6499 fix(DASH): decrease memory preasure on manifest with SegmentReference by updating old initSegmentReference
  AUTHORS
  CONTRIBUTORS
  lib/dash/segment_template.js
  lib/media/segment_reference.js
Labels: type: bug, type: performance, priority: P1, component: DASH

#6497 fix: Fix flac detection in Safari
  lib/util/stream_utils.js
Labels: type: bug, priority: P2

#6501 fix(DASH): Fix unescape UTCTiming uris
  lib/dash/dash_parser.js
Labels: type: bug, priority: P1, component: DASH

#6489 fix: Fix inefficient buffering behavior with negative trick play rate
  lib/media/segment_index.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/cmcd_manager.js
  test/media/segment_index_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
  test/test/util/simple_fakes.js
Labels: type: bug, priority: P3

#6485 docs: Update roadmap
  roadmap.md
Labels: type: docs

#6503 ci: Fix appspot promotion during deployment
  .github/workflows/release-please.yaml
Labels: type: CI

#6495 feat: Preload AES key when the key is available in EXT-X-SESSION-KEY
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#6500 feat(DASH): Add manifest.dash.enableFastSwitching config
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3, component: DASH

#6512 chore: Remove old comment
  test/media/playhead_unit.js
Labels: type: code health, component: tests

#6513 chore(DASH): Remove support for float durations.
  lib/dash/mpd_utils.js
Labels: priority: P1, component: DASH

#6514 feat: Improve default retry delay for Low Latency
  lib/player.js
Labels: type: enhancement, priority: P3

#6515 fix: Remove preloaded segment when segment has network error
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#6518 fix: Handle non existing navigator.platform string (#6517)
  lib/util/platform.js
Labels: type: bug, priority: P2

#6516 fix(DASH): Fix get partial current position for LL when using SegmentTemplate@duration
  lib/dash/segment_template.js
Labels: type: bug, priority: P2, component: DASH
