Repository shaka-project/shaka-player, pull requests merged in 2024-01, with the labels that each got.

#6018 docs: fix use of encodeURIComponent() in fairplay tutorial
  docs/tutorials/fairplay.md
Labels: type: docs, priority: P1, component: FairPlay

#6034 fix: ENCRYPTED CONTENT WITHOUT DRM INFO on comcast X1 due to safari blocklist
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, priority: P2

#6012 fix: log prefetch miss for missing segments
  lib/media/segment_prefetch.js
Labels: type: bug, priority: P2

#6022 fix: avoid uiTextDisplayer.destroy crashing if called more than once
  AUTHORS
  CONTRIBUTORS
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
Labels: type: bug, priority: P2

#6003 perf(transmuxer): various performance improvements
  lib/transmuxer/ts_transmuxer.js
  lib/util/uint8array_utils.js
Labels: type: performance, priority: P1

#6041 perf(mp4generator): stop nesting concat in methods
  lib/util/mp4_generator.js
Labels: component: HLS, type: performance, priority: P1

#6026 fix: APL set-top box wrongly identifies as an Apple device.
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, priority: P2

#6044 fix: Improved HEAD request fail test when fallback-ing to GET request
  lib/hls/hls_parser.js
  lib/net/networking_utils.js
Labels: type: bug, priority: P2

#6053 fix: Install by default shaka.polyfill.PatchedMediaKeysApple when there is no unprefixed EME support
  lib/polyfill/patchedmediakeys_apple.js
Labels: type: bug, component: EME, priority: P2, browser: Safari, platform: iOS, component: FairPlay

#6051 fix(Demo): Allow play MP4 and TS in legacy iOS devices
  demo/main.js
Labels: type: bug, component: demo page, priority: P3, platform: iOS

#6047 fix(DASH): Fix bad error on DASH DAI
  lib/util/periods.js
Labels: type: bug, priority: P1, component: DASH

#6049 feat(UI): Disable forward and rewind with arrows while seekbar not active
  ui/controls.js
Labels: type: enhancement, component: UI, priority: P3

#6052 feat(UI): Separate trackLabelFormat settings for text tracks and audio tracks
  ui/externs/ui.js
  ui/text_selection.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#6002 feat(HLS): Add AES-256 and AES-256-CTR support
  karma.conf.js
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
  test/hls/hls_parser_integration.js
  test/test/assets/hls-aes-256/index.m3u8
  test/test/assets/hls-aes-256/init.key
  test/test/assets/hls-aes-256/init.mp4
  test/test/assets/hls-aes-256/media.m3u8
  test/test/assets/hls-aes-256/seg0.key
  test/test/assets/hls-aes-256/seg1.key
  test/test/assets/hls-aes-256/seg2.key
  test/test/assets/hls-aes-256/seg3_and_4.key
  test/test/assets/hls-aes-256/segment_0.m4s
  test/test/assets/hls-aes-256/segment_1.m4s
  test/test/assets/hls-aes-256/segment_2.m4s
  test/test/assets/hls-aes-256/segment_3.m4s
  test/test/assets/hls-aes-256/segment_4.m4s
Labels: type: enhancement, component: HLS, priority: P3

#6050 fix(UI): Fix the scrolling when scrolling from the laterals when seekOnTaps is enabled
  ui/hidden_seek_button.js
Labels: type: bug, component: UI, priority: P2

#6048 fix(HLS): Live recovery after disconnects
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6046 fix(Ads): Fix VMAP won't play in muted autoplay
  lib/ads/client_side_ad.js
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#6045 fix(HLS): Fix playback of muxed TS content in Safari
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1, browser: Safari

#6005 perf: PeriodCombiner improvements
  lib/dash/dash_parser.js
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: performance, priority: P1

#6059 fix(HLS): getPlayheadTimeAsDate() differs from X-EXT-PROGRAM-DATE-TIME
  lib/hls/hls_parser.js
  lib/media/presentation_timeline.js
Labels: type: bug, component: HLS, priority: P2

#6060 chore(Demo): Add more demo pages to README
  README.md
Labels: component: demo page, priority: P4

#6061 chore: Update Content Steering support in README
  README.md
Labels: priority: P3

#6062 chore(Demo): Add FairPlay asset from EZDRM to demo
  demo/common/assets.js
Labels: component: demo page, priority: P3

#6068 revert: Install by default shaka.polyfill.PatchedMediaKeysApple when there is no unprefixed EME support
  lib/polyfill/patchedmediakeys_apple.js
Labels: priority: P1

#6069 feat(UI): Use the same logic to group variants into audio and quality selectors
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#6066 perf(WebVTT): Improve parsing time for unstyled payloads
  lib/text/vtt_text_parser.js
Labels: type: performance, priority: P1, component: WebVTT

#6076 fix: fix handling of multiple CC tracks
  lib/cea/cea608_memory.js
  lib/cea/cea_decoder.js
  test/cea/cea_decoder_unit.js
Labels: type: bug, component: captions/subtitles, priority: P1

#6072 fix(UI): Fix replay button when the post-roll is running using CS
  ui/play_button.js
  ui/small_play_button.js
Labels: type: bug, component: UI, component: ads, priority: P2

#6073 fix(Ads): Fix muting/unmuting ads won't affect video and vice versa
  lib/ads/client_side_ad.js
  lib/ads/client_side_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#6080 fix(offline): Fix server certificate error when trying to delete stored content
  lib/offline/session_deleter.js
Labels: type: bug, component: EME, priority: P1, component: offline

#6078 test: Fix some tests in Safari 17
  lib/media/media_source_engine.js
  test/media/media_source_engine_unit.js
  test/player_load_graph_integration.js
Labels: component: tests

#6075 feat: Expose PresentationTimeline segment availability duration through Player
  lib/cast/cast_utils.js
  lib/media/presentation_timeline.js
  lib/player.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#6067 perf: Improve performance of addThumbnailsTrack
  lib/player.js
Labels: type: performance, priority: P1

#6085 test: Fix some tests in Safari 17
  test/player_unit.js
Labels: component: tests

#6088 perf(HLS): do not filter all tags to get the first tag
  lib/hls/hls_utils.js
Labels: component: HLS, type: performance, priority: P1

#6086 fix(TTML): Clip to video when extent is not present
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: type: bug, component: TTML, priority: P2

#6089 fix: Reset to default playback rate on release playback rate controller
  lib/media/play_rate_controller.js
Labels: type: bug, priority: P2

#6090 fix(UI): Update the playbackrate on loaded event
  ui/playback_rate_selection.js
Labels: type: bug, component: UI, priority: P2

#6093 fix: do not append blank codec strings
  lib/util/periods.js
Labels: type: bug, priority: P1, component: DASH

#6087 docs: Add tutorial for text displayer
  docs/tutorials/index.json
  docs/tutorials/text-displayer.md
Labels: type: docs, priority: P3

#6095 feat: SegmentIndex minimal interface
  externs/shaka/manifest.js
  lib/media/segment_index.js
Labels: type: enhancement, priority: P3

#6097 feat(DASH): Allow PeriodCombiner for using streams once
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/util/periods.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3, component: DASH

#6096 feat(UI): Use the same logic to group variants into audio and quality selectors
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#6100 fix: auto cancel trickPlay on live as specified
  lib/player.js
Labels: type: bug, priority: P2

#6102 test: Make it easier to run just the offline tests
  build/test.py
Labels: type: enhancement, type: code health, priority: P3, component: tests

#6105 test: Make it easier to run just the offline tests (documentation)
  build/test.py
Labels: type: docs, priority: P3, component: tests

#6103 fix: When disconnecting from chromecast, subtitles are turned off
  lib/cast/cast_proxy.js
Labels: type: bug, component: captions/subtitles, priority: P2, platform: Cast

#6108 fix: stay paused after codec switch
  lib/media/media_source_engine.js
  test/media/media_source_engine_unit.js
Labels: type: bug, priority: P2

#6112 fix: Don't retry MSE errors on startup
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#6110 fix(UI): Disable PiP on casting
  ui/controls.js
  ui/pip_button.js
Labels: type: bug, component: UI, priority: P1

#6113 fix(DASH): Fix PERIOD_FLATTENING_FAILED on fastswitching streams
  lib/util/periods.js
Labels: type: bug, priority: P1, component: DASH

#6118 fix(HLS): Avoid duplicate AES request when using the same info
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6117 feat(UI): Allow show/hide ui programmatically
  ui/controls.js
Labels: type: enhancement, component: UI, priority: P3

#6109 fix: Include text bandwidth in stats
  lib/player.js
  test/player_unit.js
Labels: type: bug, priority: P2

#6115 fix: Reject Opus encrypted on Firefox Android
  lib/util/platform.js
  lib/util/stream_utils.js
Labels: type: bug, priority: P1, browser: Firefox, platform: Android

#6114 fix: Change quality only when adding the last partial segment and it is fast switching
  externs/shaka/abr_manager.js
  lib/abr/simple_abr_manager.js
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  lib/net/networking_engine.js
  lib/player.js
Labels: type: bug, priority: P2

#6123 chore: Update question template
  .github/ISSUE_TEMPLATE/question.md
Labels: priority: P2

#6124 chore: Always use a template for issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: priority: P2

#6126 chore: Add warning on unsupported kind in addTextTrackAsync
  lib/player.js
Labels: priority: P2

#6122 feat(Demo): Show APIC(ID3) as poster for audio only streams
  demo/main.js
Labels: type: enhancement, component: demo page, priority: P4

#6130 fix: add missing properties to PlayButton type
  AUTHORS
  CONTRIBUTORS
  ui/externs/ui.js
  ui/play_button.js
Labels: type: bug, priority: P2

#6063 feat!: Remove DOM Parser
  build/conformance.textproto
  build/types/core
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/ads/ad_manager.js
  lib/dash/content_protection.js
  lib/dash/dash_parser.js
  lib/dash/mpd_utils.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/hls/hls_parser.js
  lib/media/drm_engine.js
  lib/mss/content_protection.js
  lib/mss/mss_parser.js
  lib/text/ttml_text_parser.js
  lib/text/vtt_text_parser.js
  lib/util/string_utils.js
  lib/util/tXml.js
  lib/util/xml_utils.js
  test/dash/dash_parser_content_protection_unit.js
  test/dash/dash_parser_live_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/mpd_utils_unit.js
  test/mss/mss_parser_content_protection_unit.js
  test/mss/mss_parser_unit.js
  test/test/util/util.js
  test/util/tXml_unit.js
  test/util/xml_utils_unit.js
Labels: type: enhancement, component: TTML, type: performance, priority: P2, component: DASH, component: WebVTT, component: MSS

#6135 chore(Demo): Split manifest sections by manifest parser
  demo/config.js
Labels: component: demo page, priority: P2

#6137 fix: Fix nalu parsing in TS
  lib/util/ts_parser.js
Labels: type: bug, component: HLS, priority: P2

#6145 feat(WebVTT): Remove un-needed VTT payload normalisation
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, priority: P3, component: WebVTT

#6144 fix: Allow by default variants without pssh in the manifest
  lib/media/drm_engine.js
  lib/player.js
  test/test/util/fake_drm_engine.js
Labels: type: bug, priority: P1

#6146 feat: Parse avcC, hvcC and dvcC boxes
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
Labels: type: enhancement, priority: P3

#6143 fix(offline): Fix store persistent licenses with drm info in the pssh
  lib/offline/storage.js
Labels: type: bug, priority: P1, component: offline

#6138 fix: Fix detection of spatial rendering support in Cast
  lib/polyfill/media_capabilities.js
  test/polyfill/media_capabilities_unit.js
Labels: type: bug, priority: P2, platform: Cast

#6153 chore: Fix minor typo in demo configuration.
  demo/config.js
Labels: flag: Why didn't we catch this sooner, component: demo page

#6154 feat: Add support for Dolby Vision based on AVC and AV1
  lib/cea/mp4_cea_parser.js
  lib/util/manifest_parser_utils.js
Labels: type: enhancement, priority: P3

#6155 feat(HLS): Add support for SUPPLEMENTAL-CODECS
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
  lib/util/manifest_parser_utils.js
Labels: type: enhancement, component: HLS, priority: P3

#6157 feat: Parse vpcC and av1C boxes
  lib/media/segment_utils.js
  lib/util/mp4_box_parsers.js
Labels: type: enhancement, priority: P3

#6156 fix(HLS): Fix VVC codec selection in HLS
  lib/util/manifest_parser_utils.js
Labels: type: bug, component: HLS, priority: P3

#6163 fix: player Dropping Variant (better codec available) when it should not
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P2

#6165 fix(HLS): Set the bandwidth correctly for audio/video-only variants
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#6167 feat(text): Add MediaSource.modifyCueCallback
  externs/shaka/player.js
  externs/shaka/text.js
  lib/media/media_source_engine.js
  lib/text/text_engine.js
  lib/util/player_configuration.js
  test/demo/demo_unit.js
  test/media/media_source_engine_unit.js
  test/text/text_engine_unit.js
Labels: type: enhancement, component: captions/subtitles

#6147 feat(WebVTT): Handle badly formed VTT
  lib/text/vtt_text_parser.js
  test/text/vtt_text_parser_unit.js
Labels: type: enhancement, priority: P3, component: WebVTT

#6166 fix: AC-3 audio codec support on Tizen
  AUTHORS
  CONTRIBUTORS
  lib/polyfill/media_capabilities.js
  lib/util/stream_utils.js
Labels: type: bug, priority: P2, platform: Tizen

#6170 fix: Fix wrong aspect ratio in transmuxed videos
  lib/mss/mss_parser.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/h264.js
  lib/transmuxer/h265.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/mp4_generator.js
Labels: type: bug, component: HLS, priority: P1

#6139 feat: prefetch audio languages.
  demo/config.js
  externs/shaka/player.js
  lib/media/segment_index.js
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
  test/media/segment_prefetch_unit.js
  test/media/streaming_engine_unit.js
  test/test/util/fake_segment_prefetch.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P2

#6171 feat(CMCD): Add support to dl, nrr and nor parameters
  lib/util/cmcd_manager.js
  test/util/cmcd_manager_unit.js
Labels: type: enhancement, priority: P3

#6177 fix(CMCD): Allow reconfigure session ID
  lib/util/cmcd_manager.js
Labels: type: bug, priority: P2

#6183 docs: Update roadmap for 5.0
  roadmap.md
Labels: type: docs

#6187 fix(DASH): Update dash manifest when minimumUpdatePeriod = 0
  lib/dash/dash_parser.js
  test/dash/dash_parser_live_unit.js
Labels: type: bug, priority: P2, component: DASH

#6190 test: Fix some tests in Safari 17
  test/player_integration.js
  test/test/assets/screenshots/safari-Mac/text-displayer-native-basic-cue.png
  test/test/assets/screenshots/safari-Mac/text-displayer-native-line-alignment.png
Labels: browser: Safari, component: tests

#6186 docs: Add Hisense information to README
  README.md
Labels: type: docs

#6189 feat!: Remove com.adobe.primetime keysystem
  demo/main.js
  lib/media/drm_engine.js
  lib/offline/storage.js
  lib/util/player_configuration.js
  test/dash/dash_parser_content_protection_unit.js
Labels: type: enhancement, type: code health

#6194 fix(Demo): Fix MSS assets
  demo/common/assets.js
Labels: type: bug, component: demo page, priority: P2

#6192 fix: allow session id to be configured
  lib/util/cmcd_manager.js
  test/util/cmcd_manager_unit.js
Labels: type: bug, priority: P2

#6198 feat: Escape html codes when getting node contents
  lib/util/tXml.js
  test/util/tXml_unit.js
Labels: type: enhancement, priority: P3

#6199 fix: Fix SegmentPrefetch in some cases
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#6204 fix: Prevent license requests for unplayable variants
  lib/player.js
Labels: type: bug, priority: P2

#6201 fix: Fix DRM workaround for Xbox with Dolby Vision boxes
  lib/media/content_workarounds.js
Labels: type: bug, priority: P2

#6197 feat: Add disableTextPrefetch config
  demo/config.js
  externs/shaka/player.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: captions/subtitles, priority: P3

#6206 docs: Add missing license details after tXml import
  LICENSE
  lib/util/tXml.js
Labels: type: docs
