Repository shaka-project/shaka-player, pull requests merged in 2024-09, with the labels that each got.

#7241 docs: Update docs for v4.11 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#7246 test: Update SAMPLE-AES test asset
  test/test/assets/hls-sample-aes/audio.mp4
  test/test/assets/hls-sample-aes/index.m3u8
  test/test/assets/hls-sample-aes/video.mp4
Labels: component: tests

#7242 fix(UI): Remove not loaded font
  demo/demo.less
  ui/less/containers.less
  ui/less/tooltip.less
Labels: type: bug, component: UI, priority: P2

#7250 chore: Update some native screenshots
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-bitmap-cue.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-cue-position.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-cue-with-newline.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-end-time-edge-case.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-line-alignment.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-region-with-display-alignment.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-two-basic-cues.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-center-position-50.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-center.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-end.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-start.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-line-1.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-line-50.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-line-85-position-50-size-63.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-line-negative-2.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-region-2-lines-scroll-up.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-bitmap-cue.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-cue-position.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-cue-with-newline.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-deeply-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-end-time-edge-case.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-line-alignment.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-nested-cues-with-linebreak.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-region-with-display-alignment.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-two-basic-cues.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-center-position-50.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-center.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-end-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-end.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-start.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-embedded-styles.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-line-0.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-line-1.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-line-50.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-line-85-position-50-size-63.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-line-negative-2.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-region-2-lines-scroll-up.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-region-anchor-top-center.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-region-anchor-top-left.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-region-complex-anchors.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-region-no-anchors.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-size-50.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-white-spaces.png
Labels: component: tests

#7233 fix: Fix type passed to isTypeSupported in some cases
  lib/media/streaming_engine.js
Labels: type: bug, platform: TV/STB, priority: P2, component: DASH

#7249 fix(UI): Fix font-family override in UITextDisplayer
  lib/text/ui_text_displayer.js
  ui/less/containers.less
Labels: type: bug, component: UI, priority: P1

#7264 feat(DASH): Disable xlink processing by default
  demo/common/assets.js
  externs/shaka/player.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
  test/test/util/dash_parser_util.js
Labels: type: enhancement, priority: P3, component: DASH

#7258 fix: Fix rendering of image subs when using SimpleTextDisplayer
  lib/text/simple_text_displayer.js
  lib/text/text_utils.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7265 chore: Raise screenshot threshold for native text
  build/updateScreenshots.py
  test/test/assets/screenshots/chrome-Android/webvtt-native-align-end-long.png
  test/test/assets/screenshots/chrome-Android/webvtt-native-size-50.png
  test/test/assets/screenshots/chrome-Linux/webvtt-native-align-center-long.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-basic-cue.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-deeply-nested-cues.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-duplicate-cues.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-flat-cue-bg.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-nested-cue-bg.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-region-position.png
  test/test/assets/screenshots/chrome-Mac/text-displayer-native-two-nested-cues.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-center-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-end-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-position-line.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-align-start-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-classes-with-styles.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-classes.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-embedded-styles.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-escaped-entities.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-italic-long.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-line-0.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-region-anchor-top-center.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-region-anchor-top-left.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-region-complex-anchors.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-region-no-anchors.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-size-50.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-voices-with-styles.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-voices.png
  test/test/assets/screenshots/chrome-Mac/webvtt-native-white-spaces.png
  test/test/assets/screenshots/chrome-Windows/webvtt-native-align-center-long.png
  test/test/assets/screenshots/chrome-Windows/webvtt-native-align-end-long.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-region-2-lines-scroll-up.png
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-underline-long.png
  test/test/assets/screenshots/msedge-Linux/webvtt-native-align-center-long.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-basic-cue.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-duplicate-cues.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-flat-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-nested-cue-bg.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-region-position.png
  test/test/assets/screenshots/msedge-Mac/text-displayer-native-two-nested-cues.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-center-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-position-line.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-align-start-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-bold-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-classes-with-styles.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-classes.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-escaped-entities.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-italic-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-underline-long.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-voices-with-styles.png
  test/test/assets/screenshots/msedge-Mac/webvtt-native-voices.png
  test/test/assets/screenshots/msedge-Windows/webvtt-native-align-center-long.png
  test/test/assets/screenshots/msedge-Windows/webvtt-native-align-end-long.png
  test/test/util/layout_tests.js
Labels: type: code health

#7270 fix(TTML): Fix subtitles not rendered due to complaint about xml:id
  lib/text/ttml_text_parser.js
Labels: type: bug, component: TTML, priority: P1

#7268 test: Fix flaky test in Tizen
  test/ads_integration.js
Labels: component: tests

#7271 feat(Ads): Add config to allow disable interstitials
  demo/config.js
  externs/shaka/player.js
  lib/ads/ad_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: ads, priority: P3

#7274 chore: Update IMA externs
  externs/ima.js
Labels: component: ads

#7266 fix(UI): Display the font-family correctly in some cases
  ui/less/overflow_menu.less
  ui/less/tooltip.less
Labels: type: bug, component: UI, priority: P2

#7267 feat(UI): Use the lang= attribute to help screen-readers recognize localized labels
  externs/shaka/text.js
  lib/player.js
  lib/text/simple_text_displayer.js
  lib/text/stub_text_displayer.js
  lib/text/ui_text_displayer.js
  test/test/util/fake_text_displayer.js
  ui/controls.js
Labels: type: enhancement, component: UI, priority: P3

#7273 fix(WebVTT): Fix mapNativeCueToShakaCue in Chromium browsers
  lib/text/text_utils.js
Labels: type: bug, priority: P2, component: WebVTT

#7278 docs(HLS): Add info about supported HLS tags
  README.md
Labels: type: docs, component: HLS, priority: P3

#7280 fix(TTML): Fix absence of conversion of alpha (transparency) from 0-255 -> 0-1
  lib/text/ttml_text_parser.js
  test/text/ttml_text_parser_unit.js
Labels: type: bug, component: TTML, priority: P2

#7281 fix(DASH): Avoid adding originalId when it is not necessary
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, type: performance, priority: P2, component: DASH

#7282 fix(DASH): Use presentationTimeOffset in EventStream
  lib/dash/dash_parser.js
  test/dash/dash_parser_live_unit.js
Labels: type: bug, priority: P2, component: DASH

#7285 fix(DASH): Clone EventStream nodes to reduce memory consumption
  lib/dash/dash_parser.js
Labels: type: bug, type: performance, priority: P1, component: DASH

#7287 ci: Increase selenium timeout to avoid timeouts in Tizen
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#7286 fix(DASH): Allow mixing SegmentTemplate-SegmentTimeline with SegmentTemplate-numbering
  lib/dash/segment_template.js
  lib/media/presentation_timeline.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#7294 perf(DASH): Create segment indexes only on new periods
  lib/util/periods.js
Labels: type: performance, priority: P1, component: DASH

#7296 fix(DASH): Evict (by time) indexes in MetaSegmentIndex
  lib/media/segment_index.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1, component: DASH

#7295 perf(DASH): Do not check is index instance of MetaSegmentIndex
  lib/util/periods.js
Labels: type: performance, priority: P1, component: DASH

#7299 ci: Fix SHA1 selection in lab run
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#7298 ci: Allow concurrent lab runs that use different devices
  .github/workflows/selenium-lab-tests.yaml
Labels: type: CI

#7292 feat(Cast): Enable storage in Android Cast devices
  lib/offline/indexeddb/storage_mechanism.js
Labels: type: enhancement, priority: P2, component: offline, platform: Cast

#7297 fix(DASH): Clear streamMap when period is removed from the manifest
  lib/dash/dash_parser.js
Labels: type: bug, priority: P1, component: DASH

#7301 perf(DASH): Delete old matchedStreams
  lib/dash/dash_parser.js
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: performance, priority: P1, component: DASH

#7304 perf: Only use tXml parent when necessary
  lib/dash/mpd_utils.js
  lib/text/ttml_text_parser.js
  lib/util/tXml.js
Labels: type: performance, priority: P1

#7305 fix(DASH): Clear usedPeriodIds when period is removed from the manifest
  lib/dash/dash_parser.js
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P2, component: DASH

#7306 perf(DASH): Delete old matchedStreams when using trickmodeVideo
  lib/util/periods.js
Labels: type: performance, priority: P1, component: DASH

#7262 chore: Sync conflicting translations
  ui/locales/ar-XB.json
  ui/locales/ar.json
  ui/locales/bg.json
  ui/locales/ca.json
  ui/locales/cs.json
  ui/locales/da.json
  ui/locales/de.json
  ui/locales/el.json
  ui/locales/en-GB.json
  ui/locales/en-XA.json
  ui/locales/es-419.json
  ui/locales/es.json
  ui/locales/fa.json
  ui/locales/fi.json
  ui/locales/fil.json
  ui/locales/fr.json
  ui/locales/hi.json
  ui/locales/hr.json
  ui/locales/hu.json
  ui/locales/id.json
  ui/locales/it.json
  ui/locales/iw.json
  ui/locales/ja.json
  ui/locales/ko.json
  ui/locales/lt.json
  ui/locales/lv.json
  ui/locales/nl.json
  ui/locales/no.json
  ui/locales/pl.json
  ui/locales/pt-BR.json
  ui/locales/pt-PT.json
  ui/locales/ro.json
  ui/locales/ru.json
  ui/locales/sk.json
  ui/locales/sl.json
  ui/locales/sr.json
  ui/locales/sv.json
  ui/locales/th.json
  ui/locales/tr.json
  ui/locales/uk.json
  ui/locales/vi.json
  ui/locales/zh-HK.json
  ui/locales/zh-TW.json
  ui/locales/zh.json
Labels: type: process

#7309 fix(DASH): Clone closedCaptions map in PeriodCombiner output stream
  lib/util/periods.js
Labels: type: bug, priority: P2, component: DASH

#7320 fix(UI): Remove spinner and client side ad container elements when calling destroy
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#7321 fix(HLS): Fix uncaught error in slow network scenario
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P2

#7322 feat(Offline): Allow store external thumbnails
  demo/common/assets.js
  demo/main.js
  externs/shaka/manifest.js
  externs/shaka/offline.js
  lib/media/segment_reference.js
  lib/offline/download_info.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  test/offline/manifest_convert_unit.js
Labels: type: enhancement, priority: P3, component: offline

#7328 feat(Offline): Allow store external text
  demo/common/asset.js
  demo/common/assets.js
  demo/main.js
  externs/shaka/player.js
  lib/offline/storage.js
Labels: type: enhancement, component: captions/subtitles, priority: P3, component: offline

#7332 fix: Avoid make HEAD request for image mime type
  lib/net/networking_utils.js
Labels: type: bug, priority: P2

#7333 fix: Fix external image track mime type
  lib/player.js
  test/player_integration.js
  test/player_src_equals_integration.js
Labels: type: bug, priority: P2

#7331 fix(Tizen): Adding gapPadding to gap manager to solve Tizen issue
  demo/config.js
  externs/shaka/player.js
  lib/media/gap_jumping_controller.js
  lib/util/player_configuration.js
  test/media/playhead_unit.js
Labels: type: bug, priority: P1, platform: Tizen

#7336 fix(offline): Text segments are downloaded before audio&video
  externs/shaka/player.js
  lib/offline/storage.js
Labels: type: bug, priority: P1, component: offline

#7339 fix(DASH): Fix HTTP redirect during manifest update
  lib/dash/dash_parser.js
Labels: type: bug, priority: P2, component: DASH

#7340 fix(HLS): Allow sync live streams without PROGRAM-DATE-TIME
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#7342 test: Don't fail tests when cast property can't be deleted
  test/polyfill/media_capabilities_unit.js
Labels: component: tests, platform: Cast

#7345 test: Fix uncaught errors while testing on Cast
  test/test/boot.js
Labels: component: tests

#7344 chore: Improve logging around test setup failures
  test/test/boot.js
  test/test/cast-boot.js
Labels: component: tests

#7343 feat(HLS): Make dummy streams for tags representing muxed audio
  externs/shaka/manifest.js
  externs/shaka/offline.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/mss/mss_parser.js
  lib/offline/indexeddb/v1_storage_cell.js
  lib/offline/indexeddb/v2_storage_cell.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  roadmap.md
  test/hls/hls_parser_unit.js
  test/media/adaptation_set_unit.js
  test/media/media_source_engine_integration.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
  test/test/util/offline_utils.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, component: HLS, priority: P4

#7347 fix(dash): live to vod transition seek start
  lib/media/presentation_timeline.js
  test/player_integration.js
  test/test/assets/3675/dash_0.mpd
  test/test/assets/3675/dash_1.mpd
  test/test/assets/3675/dash_2.mpd
  test/test/assets/3675/dash_3.mpd
  test/test/assets/3675/dash_4.mpd
Labels: type: bug, priority: P2, component: DASH

#7352 fix(UI): Fix missing tracks in resolution selector
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#7351 fix(HLS): Avoid disabling muxed audio streams
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#7355 fix: Disable Encryption Scheme Polyfil On Some Devices
  lib/polyfill/encryption_scheme.js
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, priority: P1, platform: Playstation 4

#7357 fix: Do not recognize Sky Q as Apple device
  lib/util/platform.js
Labels: type: bug, priority: P2

#7353 fix: Avoid notify buffered changes when segment appended is text
  lib/player.js
Labels: type: bug, priority: P2

#7360 fix: Evict text buffer when unload the text stream
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#7364 fix(DASH): Release period combiner info correctly
  lib/util/periods.js
Labels: type: bug, priority: P3

#7358 feat: Remove streaming.parsePrftBox config
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
  lib/util/player_configuration.js
  test/cast/cast_utils_unit.js
  test/media/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
Labels: type: enhancement, priority: P3

#7359 fix(preload): Set manifest before initializing DRM
  lib/media/preload_manager.js
  lib/player.js
  test/player_load_graph_integration.js
Labels: type: bug, priority: P2

#7366 ci: Test PR on Opera
  .github/workflows/build-and-test.yaml
  README.md
  build/test.py
Labels: type: CI

#7373 fix(Ads): Release interstitials timer correctly
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#7375 fix(UI): Fix mediaSession metadata update on Firefox
  demo/main.js
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#7380 fix(preload): Resolve manifest promise sooner
  lib/media/preload_manager.js
  lib/player.js
Labels: type: bug, priority: P2

#7374 fix: Reduce calls to EME by ignoring MIME type in MediaKeySystemAccess cache
  lib/polyfill/media_capabilities.js
Labels: type: bug, priority: P2
