Repository shaka-project/shaka-player, pull requests merged in 2025-06, with the labels that each got.

#8674 fix: Remove active audio channel count from default pref based criteria
  lib/media/preference_based_criteria.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: bug, priority: P2

#8676 test: Fix ad container position in ads tests
  test/ads_integration.js
Labels: component: tests

#8694 fix(UI): Hide player labels when More Settings menu is open
  ui/controls.js
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#8701 fix(UI): Only enable enableFullscreenOnRotation and forceLandscapeOnFullscreen on mobile
  ui/externs/ui.js
  ui/ui.js
Labels: type: bug, component: UI, priority: P2

#8700 fix(UI): Don't show loop button for live streams
  ui/loop_button.js
Labels: type: bug, component: UI, priority: P2

#8702 docs: Update docs api links to use Github pages
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  README.md
  demo/autoTemplate.txt
  maintained-branches.md
Labels: type: docs

#8704 docs: Fix texttrackvisibility and trackschanged documentation
  lib/player.js
Labels: type: docs

#8705 fix: Fix bad assert on DeviceFactory
  lib/device/device_factory.js
Labels: type: bug, priority: P2

#8710 perf(net): Do not parse headers twice in XHR plugin
  lib/net/http_xhr_plugin.js
Labels: type: performance

#8716 fix: Only change appendWindowStart and appendWindowEnd when necessary
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#8717 fix: Fix chopped playback in some DASH multiperiod streams
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1, component: DASH

#8718 test: Simplify Ads integration tests
  test/ads_integration.js
Labels: component: ads, component: tests

#8721 chore(DRM): DRM Engine init improvements
  lib/drm/drm_engine.js
Labels: type: code health, component: EME

#8723 chore(Demo): Simplify certificate setup
  demo/common/asset.js
  demo/main.js
Labels: component: demo page

#8724 fix(HLS): Fix APAC detection
  lib/media/media_source_engine.js
  lib/media/segment_utils.js
  lib/util/manifest_parser_utils.js
  project-words.txt
Labels: type: bug, component: HLS, priority: P2

#8728 feat(Demo): Add new VR streams from Apple
  demo/common/assets.js
  demo/main.js
  lib/media/media_source_engine.js
Labels: component: demo page

#8731 feat(HLS): Get info about projection from REQ-VIDEO-LAYOUT instead of parsing the init segment
  lib/media/streaming_engine.js
Labels: type: enhancement, component: HLS, priority: P4

#8732 fix: Fix Apple Vision Pro detection
  lib/device/apple_browser.js
Labels: type: bug, priority: P2

#8738 fix(HLS): Fix reset media source when using muxed content
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P1

#8736 feat: Allow switch between UITextDisplayer and NativeTextDisplayer on runtime
  docs/tutorials/text-displayer.md
  externs/shaka/player.js
  lib/player.js
Labels: type: enhancement, component: captions/subtitles, priority: P3

#8739 fix(UI): Update play button state when the player is loaded
  ui/play_button.js
Labels: type: bug, component: UI, priority: P2

#8740 fix(UI): Only show replay button when there is a duration in the media element
  ui/play_button.js
Labels: type: bug, component: UI, priority: P2

#8741 fix(HLS): Fix switching between muxed and alternate audios
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P1

#8742 fix(UI): Resize overflow and settings menus when necessary
  ui/overflow_menu.js
  ui/settings_menu.js
Labels: type: bug, component: UI, priority: P2

#8747 chore(Demo): Fix demo extraconfig configuration
  demo/main.js
Labels: type: bug, component: demo page, priority: P2

#8748 fix(CEA): INVALID_MP4_CEA error being thrown when shouldn't be
  lib/cea/mp4_cea_parser.js
Labels: type: bug, component: captions/subtitles, priority: P1

#8751 feat(UI): Add enableKeyboardPlaybackControlsInWindow config
  ui/controls.js
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#8756 chore: Remove session definition from SessionMetadata
  lib/drm/drm_engine.js
Labels: type: code health, priority: P3

#8757 fix(UI): Fix fullscreen doesn’t work on iPad (Edge/Chrome)
  ui/externs/ui.js
  ui/ui.js
Labels: type: bug, component: UI, priority: P2

#8761 chore(UI): Use shaka.ui.Utils.buildTimeString in seek_bar.js
  ui/seek_bar.js
Labels: type: code health

#8764 fix: Fix 4k stream support within browser env on Tizen
  lib/device/tizen.js
Labels: type: bug, priority: P2, platform: Tizen

#8765 fix(UI): Fix default value of enableKeyboardPlaybackControlsInWindow
  ui/ui.js
Labels: type: bug, component: UI, priority: P2

#8767 feat(UI): Add more keyboard shortcuts
  ui/controls.js
Labels: type: enhancement, component: UI, priority: P3

#8769 fix(UI): Fix PageDown and PageUp shortcuts
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8758 fix(UI): The playback time displayed in the seek bar is different from currentTime when click
  ui/range_element.js
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#8775 fix: Reset text visibility on unload
  lib/player.js
  test/player_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#8768 docs(UI): Add supported shortcuts
  docs/tutorials/ui.md
Labels: type: docs, component: UI

#8760 fix(DASH): Use the correct Representation ID for Uri substitution of media segments
  lib/dash/segment_template.js
  test/dash/dash_parser_segment_template_unit.js
Labels: type: bug, priority: P1, component: DASH

#8778 fix(UI): Fix unhandled rejection on remote button
  ui/remote_button.js
Labels: type: bug, component: UI, priority: P2

#8773 fix(UI): Make the overflow menu visually smoother
  ui/less/overflow_menu.less
Labels: type: bug, component: UI, priority: P2

#8777 fix(Demo): Fix keep custom config on page reload
  demo/main.js
  lib/util/object_utils.js
Labels: type: bug, component: demo page, priority: P2

#8779 feat(UI): Use Mbps notation in resolution selector
  test/ui/ui_unit.js
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#8784 fix(HLS): mediaSequenceToStartTime isn't maintained correctly for AUDIO manifest
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P1

#8788 feat: Add shaka.extern.DrmSessionMetadata to LICENSE_REQUEST_FAILED error
  lib/drm/drm_engine.js
  lib/util/error.js
  test/drm/drm_engine_unit.js
Labels: type: enhancement, component: EME, priority: P3

#8794 fix(HLS): Reset PTS/DTS reference at discontinuities when using TS
  lib/media/media_source_engine.js
  lib/transmuxer/mpeg_ts_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/ts_parser.js
Labels: type: bug, priority: P1, component: transmuxer

#8782 feat(CMCD): Add response mode for CMCDv2
  externs/shaka/player.js
  lib/net/networking_engine.js
  lib/player.js
  lib/util/cmcd_manager.js
  lib/util/player_configuration.js
  project-words.txt
  test/util/cmcd_manager_unit.js
Labels: type: enhancement, priority: P3, component: CMCD

#8792 feat: Add enableAudioGroups config
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: HLS, priority: P3, component: DASH

#8806 feat(UI): Enable preferVideoFullScreenInVisionOS by default
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P4

#8809 fix(UI): Fix volume slider control is not accessible by keyboard
  ui/less/range_elements.less
Labels: type: bug, component: UI, type: accessibility, priority: P3

#8810 fix(UI): Prevent override box-sizing style on range elements
  ui/less/range_elements.less
Labels: type: bug, component: UI, priority: P2

#8807 feat(UI): Add alwaysShowVolumeBar config
  ui/externs/ui.js
  ui/less/range_elements.less
  ui/ui.js
  ui/volume_bar.js
Labels: type: enhancement, component: UI, priority: P3

#8812 chore: Remove useless play listener when using delayLicenseRequestUntilPlayed as false
  lib/drm/drm_engine.js
Labels: type: code health

#8813 fix: Fix end-of-stream detection for VOD
  lib/player.js
Labels: type: bug, priority: P1
