Repository shaka-project/shaka-player, pull requests merged in 2025-05, with the labels that each got.

#8542 fix: Fix MediaCapabilities polyfill on Vizio
  lib/polyfill/media_capabilities.js
Labels: type: bug, platform: TV/STB, priority: P2

#8546 fix: Update eme-encryption-scheme-polyfill
  package-lock.json
  package.json
Labels: type: bug, component: EME, priority: P1

#8540 fix(UI): Fix seekbar allows seeking even when hidden
  project-words.txt
  ui/controls.js
  ui/range_element.js
Labels: type: bug, component: UI, priority: P2

#8544 fix(UI): Fix UI behaviour when switching between PiP and fullscreen and vice versa
  ui/controls.js
Labels: type: bug, component: UI, priority: P1

#8552 fix(Cast): Fix getChaptersTracks method while casting
  lib/cast/cast_utils.js
Labels: type: bug, priority: P2, platform: Cast

#8549 fix(Cast): Add response to async calls on cast proxy
  lib/cast/cast_receiver.js
  lib/cast/cast_sender.js
  test/cast/cast_receiver_unit.js
Labels: type: bug, priority: P1, platform: Cast

#8551 fix(UI): Create watermark element only when necessary
  demo/main.js
  ui/ui.js
Labels: type: bug, component: UI, priority: P2

#8553 feat(Cast): Transfer side-loaded text/thumbnail/chapter tracks
  lib/cast/cast_proxy.js
  lib/cast/cast_receiver.js
  lib/cast/cast_utils.js
Labels: type: enhancement, priority: P3, platform: Cast

#8554 fix: Add new parameters to thumbnails in order to work with cast proxy
  externs/shaka/player.js
  lib/player.js
  ui/seek_bar.js
Labels: type: bug, priority: P1

#8520 feat: new TextDisplayer implementation to allow selecting subtitles via native API and controls
  AUTHORS
  CONTRIBUTORS
  build/types/core
  build/types/ui
  demo/main.js
  docs/tutorials/plugins.md
  docs/tutorials/text-displayer.md
  lib/player.js
  lib/text/native_text_displayer.js
  lib/text/simple_text_displayer.js
  lib/text/text_utils.js
  test/player_integration.js
  test/player_src_equals_integration.js
  test/test/util/layout_tests.js
  test/test/util/simple_fakes.js
  test/text/native_text_displayer_unit.js
Labels: type: enhancement, component: captions/subtitles, priority: P3

#8555 fix(UI): Fix seek on the seekbar at the init
  ui/range_element.js
Labels: type: bug, component: UI, priority: P1

#8556 feat(Ads): Support latest spec of background in DASH overlays
  lib/ads/interstitial_ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: enhancement, component: ads, priority: P3

#8558 fix(UI): Fix erroneous current time when dragging
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#8560 fix: Fix cast proxy args for side-loaded tracks
  lib/cast/cast_proxy.js
Labels: type: bug, priority: P1

#8561 docs: Update Roadmap
  roadmap.md
Labels: type: docs

#8564 fix: Fix side-loaded track when resuming local and cast again
  lib/cast/cast_proxy.js
Labels: type: bug, priority: P2, platform: Cast

#8573 fix: Reset external tracks when unloading in cast proxy
  lib/cast/cast_proxy.js
Labels: type: bug, priority: P2, platform: Cast

#8574 fix(UI): Fix visibility events while casting
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8565 chore(Demo): Fix FairPlay Axinom assets
  demo/common/assets.js
Labels: component: demo page

#8577 fix: Sony Bravia TV Playready DRM Failure
  lib/drm/drm_engine.js
  lib/util/platform.js
  project-words.txt
Labels: type: bug, platform: TV/STB, priority: P2, component: PlayReady

#8575 feat: Add backToLiveWhenOutsideOfLiveWindow config
  demo/config.js
  externs/shaka/player.js
  lib/media/playhead.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#8572 fix: Fix text visibility when switching between stream with text and without text
  lib/player.js
Labels: type: bug, priority: P2

#8580 fix(UI): Only create VR canvas when necessary
  ui/ui.js
  ui/vr_manager.js
Labels: type: bug, component: UI, priority: P2

#8581 fix: Only create shaka-text-container when necessary
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
  ui/controls.js
Labels: type: bug, component: captions/subtitles, priority: P2

#8571 fix(UI): Keep the current position gradient when seeked
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#8570 fix: Fix memory leak on Metadata and EMSG timelines
  lib/media/region_timeline.js
  lib/player.js
Labels: type: bug, priority: P1

#8585 fix: Fix config failures with multiple references to an input array
  lib/util/config_utils.js
Labels: type: bug, priority: P1

#8569 fix: Make sure we are calling setLiveSeekableRange and clearLiveSeekableRange at the correct time
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#8598 docs: Fix typo
  docs/tutorials/errors.md
Labels: type: docs

#8599 fix: Fixes eme-encryption-scheme-polyfill, null encryptionScheme is valid
  package-lock.json
  package.json
Labels: type: bug, priority: P1

#8594 feat: Add useTrickPlayTrackIfAvailable method
  lib/cast/cast_utils.js
  lib/player.js
Labels: type: enhancement, priority: P3

#8593 fix: Avoid installing/uninstalling PatchedMediaKeysApple polyfill twice
  lib/polyfill/patchedmediakeys_apple.js
Labels: type: bug, priority: P1, component: FairPlay

#8592 chore: Simplify clearMediaKeySystemAccessMap
  lib/drm/drm_utils.js
Labels: type: code health

#8591 fix: Fix onUpdateEnd when the MSE engine has been destroyed
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1

#8589 fix: Only check key status changes when drm engine is available
  lib/player.js
Labels: type: bug, component: EME, priority: P2

#8602 fix(DASH): Inconsistent DRM across periods when using clearkeys
  lib/drm/drm_utils.js
Labels: type: bug, priority: P1, component: DASH

#8603 chore: Move isBufferedToEnd to Playhead
  lib/media/playhead.js
  lib/player.js
Labels: type: code health, priority: P3

#8604 feat: Add canupdatestarttime to allow update the startTime safely
  lib/player.js
  lib/util/fake_event.js
  project-words.txt
Labels: type: enhancement, priority: P2

#8605 fix(UI): Reset quality mark when switching from video stream to audio only stream
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#8606 fix: Detect screen change to update ABR according HDR vs SDR
  lib/media/adaptation_set_criteria.js
  lib/media/preference_based_criteria.js
  lib/player.js
Labels: type: bug, priority: P2

#8609 test: Enable HEVC tests on Firefox Windows
  test/test/util/util.js
Labels: component: tests

#8613 fix: Fix garbage-collection issue in safari on mediaCapabilities polyfill
  lib/polyfill/media_capabilities.js
Labels: type: bug, priority: P1, browser: Safari

#8617 fix: Do not fire metadataadded event for duplicated cues
  lib/player.js
Labels: type: bug, priority: P2

#8618 perf(net): Avoid parsing headers twice
  lib/net/http_fetch_plugin.js
Labels: type: performance, priority: P2, component: networking

#8621 chore(UI): Remove constants file
  build/types/ui
  ui/constants.js
  ui/seek_bar.js
Labels: type: code health, component: UI

#8597 feat: Add additional codec & channel count configs to Adaptation Set Criteria
  lib/media/adaptation_set_criteria.js
  lib/media/preference_based_criteria.js
  lib/media/preload_manager.js
  lib/player.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: enhancement, priority: P3

#8623 fix(WebOS): Do not throw error during parsing ID3
  build/types/polyfill
  lib/polyfill/typed_array.js
  shaka-player.uncompiled.js
Labels: type: bug, priority: P1, platform: WebOS

#8625 fix: Try to reset MSE on STREAMING_NOT_ALLOWED error
  lib/player.js
Labels: type: bug, priority: P2, browser: Safari

#8626 fix: Avoid reset MSE engine when using remote playback
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1, platform: AirPlay

#8628 fix(UI): Avoid show resolution selector when using remote playback
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2, platform: AirPlay

#8629 fix: Allow use isLive, seekRange and isAudioOnly when using remote playback
  lib/player.js
Labels: type: bug, priority: P1, platform: AirPlay

#8630 fix: Fix getAudioTracks when using remote playback
  lib/player.js
Labels: type: bug, priority: P2, platform: AirPlay

#8632 chore: Simplify metadata event handling
  lib/player.js
Labels: type: code health, priority: P3

#8636 fix: Disable translate of cues when using UITextDisplayer
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P2

#8637 chore: Useless warning on UITextDisplayer
  lib/text/ui_text_displayer.js
Labels: component: captions/subtitles, priority: P2

#8638 fix(HLS): Do not skip DateRanges based on ID
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#8639 fix(UI): Fix position of menus and tooltips when the seekbar is missing
  ui/controls.js
  ui/less/overflow_menu.less
  ui/less/tooltip.less
Labels: type: bug, component: UI, priority: P2

#8641 feat: Add isVideoOnly method
  lib/cast/cast_utils.js
  lib/player.js
  test/player_unit.js
  ui/mute_button.js
  ui/volume_bar.js
Labels: type: enhancement, priority: P3

#8642 fix(HLS): Fix disableAudio and disableVideo when loading a media playlist
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#8644 fix: Use proper method for checking is object an array
  lib/text/cue.js
  lib/util/object_utils.js
Labels: type: bug, priority: P3

#8648 fix(UI): Add missing replay icon to big play button
  ui/big_play_button.js
  ui/images/replay.svg
  ui/less/buttons.less
  ui/play_button.js
  ui/small_play_button.js
Labels: type: bug, component: UI, priority: P2

#8647 feat(Preload): Allow use custom config when creating a PreloadManager
  lib/player.js
Labels: type: enhancement, priority: P3

#8650 fix(UI): Filter audio qualities when bandwidth is missing
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#8652 perf: Optimize DRM compatibility check across streams
  lib/drm/drm_utils.js
Labels: type: code health, type: performance, priority: P2

#8657 chore(CMCD): Preparation for CMCDv2 response mode
  lib/player.js
  lib/util/cmcd_manager.js
  test/util/cmcd_manager_unit.js
Labels: type: code health, priority: P2, component: CMCD

#8658 fix(Demo): Fix bad tooltip position of last control panel element
  demo/main.js
Labels: type: bug, component: demo page

#8661 chore(DRM): Remove getMediaKeySessions()
  lib/drm/drm_engine.js
Labels: type: code health, component: EME

#8659 chore(CMCD): Preparation for CMCDv2 response mode
  lib/util/cmcd_manager.js
Labels: type: code health, priority: P2, component: CMCD

#8649 feat: Add queue manager
  build/all.py
  build/types/complete
  build/types/core
  build/types/queue
  build/types/ui
  demo/asset_card.js
  demo/common/asset.js
  demo/common/assets.js
  demo/config.js
  demo/main.js
  externs/shaka/player.js
  externs/shaka/queue.js
  lib/cast/cast_proxy.js
  lib/config/repeat_mode.js
  lib/player.js
  lib/queue/queue_manager.js
  lib/util/error.js
  lib/util/fake_event.js
  lib/util/player_configuration.js
  project-words.txt
  roadmap.md
  shaka-player.uncompiled.js
  test/cast/cast_receiver_integration.js
  test/cast/cast_utils_unit.js
  test/queue/queue_manager_unit.js
  ui/enums.js
  ui/locales/en.json
  ui/locales/es.json
  ui/locales/fr.json
  ui/locales/pl.json
  ui/locales/source.json
  ui/skip_next_button.js
  ui/ui.js
Labels: type: enhancement, priority: P3

#8669 chore(Demo): Check if advanced configuration has items before set anything
  demo/main.js
Labels: component: demo page

#8662 build: Move compiler command line arguments to a file
  build/compiler.py
  build/shakaBuildHelpers.py
Labels: component: build system

#8667 ci: Add job to deploy nightly demo on GitHub Pages
  .github/workflows/github-pages-nightly-demo.yaml
Labels: type: CI
