Repository shaka-project/shaka-player, pull requests merged in 2025-03, with the labels that each got.

#8193 feat(UI): Close submenu or context menu on option click
  ui/ad_statistics_button.js
  ui/context_menu.js
  ui/settings_menu.js
  ui/statistics_button.js
Labels: type: enhancement, component: UI, priority: P4

#8196 chore: Remove not existing file from conformance
  build/conformance.textproto
Labels: type: code health

#8197 fix: Fix codec selection
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P1

#8198 fix: Clear some caches when install/uninstall PatchedMediaKeysApple
  lib/polyfill/patchedmediakeys_apple.js
Labels: type: bug, priority: P1, component: FairPlay

#8201 feat(FairPlay): Add support for Mux
  AUTHORS
  CONTRIBUTORS
  docs/tutorials/fairplay.md
  lib/util/fairplay_utils.js
Labels: type: enhancement, priority: P3, component: FairPlay

#8203 perf: Region timeline improvements
  lib/media/region_timeline.js
Labels: type: performance

#8205 fix(UI): Update UI in order to support AC-4
  lib/util/mime_utils.js
  ui/language_utils.js
Labels: type: bug, component: UI, priority: P3

#8206 fix(UI): Allow play/pause when seekOnTaps is enabled
  ui/controls.js
  ui/hidden_seek_button.js
  ui/play_button.js
Labels: type: bug, component: UI, priority: P2

#8207 fix(HLS): Only apply compensation if the difference is greater than 150ms
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2, browser: Safari

#8216 chore: Move isMediaKeysPolyfilled to DrmUtils
  lib/dash/content_protection.js
  lib/drm/drm_engine.js
  lib/drm/drm_utils.js
  lib/hls/hls_parser.js
  lib/media/preload_manager.js
  lib/player.js
  lib/util/platform.js
  lib/util/player_configuration.js
  test/drm/drm_utils_unit.js
  test/player_unit.js
  test/util/platform_unit.js
Labels: type: code health

#8217 feat: Move shaka.util.FairPlayUtils to shaka.drm.FairPlay
  build/types/core
  docs/tutorials/fairplay.md
  docs/tutorials/upgrade.md
  lib/drm/fairplay.js
  lib/util/fairplay_utils.js
  lib/util/player_configuration.js
  shaka-player.uncompiled.js
Labels: type: enhancement, type: code health, priority: P3, component: FairPlay

#8215 feat: Text font scaling customisation ability
  docs/tutorials/text-displayer.md
  lib/text/ui_text_displayer.js
  test/text/ui_text_displayer_unit.js
  ui/less/containers.less
Labels: type: enhancement, component: captions/subtitles, priority: P3

#8220 chore: Remove unnecessary code
  lib/player.js
Labels: type: code health

#8219 fix: When standard load, do not wait for pending license requests to finish.
  lib/media/preload_manager.js
Labels: type: bug, priority: P1

#8225 fix(UI): Improve seekOnTaps behavior on tap and scroll
  ui/hidden_seek_button.js
Labels: type: bug, component: UI, priority: P2

#8240 fix: Text tracks disappear when crossing a boundary in RESET mode.
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#8230 fix(UI): Don't sort playback rates
  ui/playback_rate_selection.js
Labels: type: bug, component: UI, priority: P2

#8237 perf(UI): Improve VR performance
  ui/vr_manager.js
  ui/vr_webgl.js
Labels: component: UI, type: performance, priority: P2

#8236 fix: Only dispatch spatialvideoinfo and nospatialvideoinfo for video streams
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#8233 fix(UI): Allow use hideUI on mobile devices
  ui/controls.js
Labels: type: bug, component: UI, priority: P1

#8234 fix(UI): Close context menu when hide the UI
  ui/context_menu.js
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8244 test: Replace failing Axinom mixed-encryption asset
  demo/common/assets.js
  test/media/content_workarounds_integration.js
  test/player_cross_boundary_integration.js
  test/test/assets/clear-encrypted/0001.m4s
  test/test/assets/clear-encrypted/0002.m4s
  test/test/assets/clear-encrypted/clear-a-init.mp4
  test/test/assets/clear-encrypted/clear-a-s1.mp4
  test/test/assets/clear-encrypted/clear-a-s2.mp4
  test/test/assets/clear-encrypted/clear-v-init.mp4
  test/test/assets/clear-encrypted/clear-v-s1.mp4
  test/test/assets/clear-encrypted/clear-v-s2.mp4
  test/test/assets/clear-encrypted/enc-a-init.mp4
  test/test/assets/clear-encrypted/enc-a-s1.mp4
  test/test/assets/clear-encrypted/enc-a-s2.mp4
  test/test/assets/clear-encrypted/enc-v-init.mp4
  test/test/assets/clear-encrypted/enc-v-s1.mp4
  test/test/assets/clear-encrypted/enc-v-s2.mp4
  test/test/assets/clear-encrypted/init-1.mp4
  test/test/assets/clear-encrypted/init-2.mp4
  test/test/assets/clear-encrypted/manifest.mpd
Labels: component: tests

#8238 feat(UI): Add halfequirectangular (180) VR support
  README.md
  project-words.txt
  ui/externs/ui.js
  ui/vr_manager.js
  ui/vr_utils.js
  ui/vr_webgl.js
Labels: type: enhancement, component: UI, priority: P3

#8223 fix(HLS): Detect spatial audio when using Dolby AC-4
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#8253 fix(hls): Removing Possible encoding problem detected
  lib/hls/hls_parser.js
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P1

#8250 docs: Update docs for v4.14 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#8242 feat: Move caption scaling from css to new textDisplayer.fontScaleFactor config
  demo/config.js
  docs/tutorials/text-displayer.md
  externs/shaka/player.js
  lib/text/ui_text_displayer.js
  lib/util/player_configuration.js
  test/text/ui_text_displayer_unit.js
  ui/less/containers.less
Labels: type: enhancement, component: captions/subtitles, priority: P3

#8259 fix(changelog): Add missing ref to PR #8156 in v4.14.0
  CHANGELOG.md
Labels: type: bug, priority: P1

#8249 fix: Persist selected audio track role after variant update in `selectVariantTrack`
  lib/media/example_based_criteria.js
Labels: type: bug, priority: P1

#8258 fix(UI): Disable save video frame button while casting
  ui/save_video_frame_button.js
Labels: type: bug, component: UI, priority: P2

#8257 chore(Demo): Disable visualizer while casting
  demo/visualizer_button.js
Labels: component: demo page

#8261 fix: Closure compiler removes call to modifyCueCallback in src= mode
  lib/player.js
Labels: type: bug, priority: P1

#8263 ci: Fix Firefox macOS hang
  package-lock.json
  package.json
Labels: type: CI

#8264 feat: Simplicate Text and Chapters APIs
  externs/shaka/player.js
  lib/media/preload_manager.js
  lib/player.js
  lib/util/stream_utils.js
  test/player_unit.js
  ui/language_utils.js
  ui/text_selection.js
Labels: type: enhancement, priority: P3

#8266 feat: Simplicate Image/Thumbnails API
  externs/shaka/player.js
  lib/player.js
  lib/util/stream_utils.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#8267 fix: Make shaka.util.Lazy work with null
  lib/util/lazy.js
  test/util/lazy_unit.js
Labels: type: bug, priority: P3

#8268 fix(Ads): Destroy preloadManagers on stop interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#8269 perf(Ads): Preload images on interstitials
  demo/config.js
  externs/shaka/player.js
  lib/ads/interstitial_ad_manager.js
  lib/util/player_configuration.js
Labels: type: performance, component: ads, priority: P1

#8275 fix: Update region observer with new rules for small regions
  lib/media/region_observer.js
  test/media/region_observer_unit.js
Labels: type: bug, priority: P1

#8274 fix(UI): Optimize portrait thumbnail display
  ui/less/thumbnails.less
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#8282 feat: Added MetadataAdded event
  lib/player.js
  lib/util/fake_event.js
  project-words.txt
Labels: type: enhancement, priority: P3

#8285 chore(Demo): Improve ad behavior
  demo/common/asset.js
  demo/custom.js
  demo/main.js
Labels: component: demo page

#8286 fix: Fix audio selection by channel count
  lib/media/preference_based_criteria.js
  test/media/adaptation_set_criteria_unit.js
Labels: type: bug, priority: P2

#8287 perf: AdaptationSetCriteria improvements
  lib/media/preference_based_criteria.js
Labels: type: performance

#8288 fix(Ads): Fix overlay interstitial when the seeked is outside of the current window
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#8290 chore: Remove ExampleBasedCriteria
  build/types/core
  lib/media/example_based_criteria.js
  lib/player.js
Labels: type: code health

#8289 feat(Ads): Add allowStartInMiddleOfInterstitial config
  demo/config.js
  externs/shaka/player.js
  lib/ads/interstitial_ad_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: ads, priority: P3

#8291 chore: Remove few lines in pref based criteria call
  lib/player.js
Labels: type: code health

#8292 chore(Ads): Rename preloadImages to preloadOnDomElements
  lib/ads/interstitial_ad_manager.js
Labels: component: ads, priority: P3

#8294 fix: Fix destroy CastProxy on browser without Cast support
  lib/cast/cast_proxy.js
Labels: type: bug, priority: P1

#8256 fix: Text tracks with src= on Safari & UITextDisplayer are sometimes rendered natively
  lib/player.js
Labels: type: bug, priority: P2, browser: Safari

#8298 build: Migrate to stylistic eslint plugin
  build/check.py
  demo/common/assets.js
  eslint.config.mjs
  karma.conf.js
  lib/dash/mpd_utils.js
  lib/text/vtt_text_parser.js
  lib/transmuxer/adts.js
  package-lock.json
  package.json
  test/ads/ad_manager_unit.js
  test/dash/dash_parser_manifest_unit.js
  test/dash/mpd_utils_unit.js
  test/drm/drm_engine_unit.js
  test/hls/hls_live_unit.js
  test/hls/hls_parser_integration.js
  test/text/text_displayer_layout_unit.js
  test/text/web_vtt_layout_integration.js
  test/transmuxer/transmuxer_integration.js
  test/util/platform_unit.js
Labels: type: code health, component: build system

#8299 feat: Add more info on src= tracks when the browser support it
  externs/audiotrack.js
  externs/videotrack.js
  lib/player.js
  lib/util/stream_utils.js
Labels: type: enhancement, priority: P3

#8303 fix(UI): Avoid hide controls when seeking
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8302 feat: Add more info on src= tracks when the browser support it
  lib/player.js
  lib/util/stream_utils.js
Labels: type: enhancement, priority: P3

#8305 fix(UI): Display max segment duration in seconds
  ui/statistics_button.js
Labels: type: bug, component: UI, priority: P3

#8304 feat: Improve stats when using src= in Safari
  lib/player.js
Labels: type: enhancement, priority: P3, browser: Safari

#8310 fix: Fix buffering event on native playback
  lib/player.js
Labels: type: bug, priority: P1

#8306 feat(net): Add networking config
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/net/networking_engine.js
  lib/offline/storage.js
  lib/player.js
  lib/util/player_configuration.js
  test/drm/drm_engine_integration.js
  test/net/networking_engine_unit.js
  test/test/util/fake_networking_engine.js
  test/util/cmcd_manager_unit.js
Labels: type: enhancement, priority: P3

#8313 fix: Prevent unhandled rejections on segment fetch failures
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#8309 feat: Simplify getStats to support MSE-AirPlay
  lib/player.js
  lib/util/stream_utils.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#8311 test: Added platform unit tests for Chromecast devices
  test/util/platform_unit.js
Labels: component: tests, platform: Cast

#8315 chore(UI): Remove useless loop on language utils
  ui/language_utils.js
Labels: type: code health, component: UI

#8318 fix(UI): Fix thumbnail exception when the thumbnails doesn't exist
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P2

#8322 fix(UI): Don't cover useless space with the position in the thumbnail image
  ui/less/thumbnails.less
  ui/seek_bar.js
Labels: type: bug, component: UI, priority: P3

#8323 fix(HLS): Supports SUPPLEMENTAL-CODECS with muxed audio
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#8316 feat: Provide Segment Reference to ABR Manager (via the request context)
  externs/shaka/abr_manager.js
  externs/shaka/net.js
  lib/abr/simple_abr_manager.js
  lib/net/networking_engine.js
  lib/player.js
  test/net/networking_engine_unit.js
Labels: type: enhancement, priority: P3

#8325 fix(HLS): Fix HLS live playback on older Webkit STBs
  lib/util/platform.js
Labels: type: bug, component: HLS, platform: TV/STB, priority: P2

#8328 test: Update Chrome Android lab screenshots
  test/test/assets/screenshots/chrome-Android/webvtt-native-align-center-long.png
  test/test/assets/screenshots/chrome-Android/webvtt-native-align-end-long.png
  test/test/assets/screenshots/chrome-Android/webvtt-native-align-start-long.png
  test/test/assets/screenshots/chrome-Android/webvtt-native-italic-long.png
  test/test/assets/screenshots/chrome-Android/webvtt-native-underline-long.png
  test/test/assets/screenshots/chrome-Android/webvtt-ui-align-end-long.png
Labels: component: tests

#8329 ci: Add new shaka-bot argument to test on Android only
  .github/workflows/shaka-bot-commands/command-help.sh
  .github/workflows/shaka-bot-commands/command-test.sh
Labels: type: CI

#8330 chore: Remove some artificial limitations in probeSupport
  lib/drm/drm_engine.js
Labels: type: code health

#8331 fix(HLS): Handle redirect URLs correctly
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#8333 perf(HLS): Reduce load time when loading in the player a media playlist
  lib/hls/hls_parser.js
  lib/media/segment_prefetch.js
  lib/media/segment_reference.js
  lib/offline/download_info.js
  lib/offline/storage.js
  test/hls/hls_parser_unit.js
  test/test/util/manifest_parser_util.js
  test/test/util/util.js
Labels: component: HLS, type: performance, priority: P1

#8337 perf(HLS): Make initial segment requests in parallel
  lib/hls/hls_parser.js
Labels: component: HLS, type: performance

#8338 fix: Don't allow MSE reset in middle of a reset
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1

#8339 fix: Reset lastMediaSourceReset when seeking to unbuffered part
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#8340 fix: Only schedule an update on reset when we are not clearing the buffer
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#8341 fix: Fix MSE recovery on Apple platform
  lib/player.js
Labels: type: bug, priority: P1, browser: Safari

#8343 fix: Add support to crossBoundaryStrategy when using HLS
  lib/hls/hls_parser.js
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P2

#8345 fix: Add new crossBoundaryStrategy for Apple browsers
  demo/config.js
  lib/config/cross_boundary_strategy.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
Labels: type: bug, priority: P1, browser: Safari, component: FairPlay

#8346 fix(HLS): Fix queryData to prevent url params percent encoding
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#8350 fix(HLS): Fix variable substitution when using relative paths
  lib/hls/hls_utils.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#8344 fix: Improve boundary gap mitigation at DASH period transitions
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/player.js
Labels: type: bug, priority: P1

#8353 perf: Stop parsing the mp4 when the init segment is encrypted on ContentWorkarounds
  lib/media/content_workarounds.js
Labels: type: performance, priority: P1

#8352 chore: Re-use Mp4Generator in ContentWorkarounds
  build/types/core
  build/types/transmuxer
  lib/media/content_workarounds.js
  lib/media/media_source_engine.js
  lib/mss/mss_parser.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/mp4_generator.js
  test/media/content_workarounds_unit.js
  test/media/media_source_engine_unit.js
Labels: type: code health

#8358 perf(ContentWorkarounds): Do not override codec twice
  lib/media/content_workarounds.js
Labels: type: performance

#8359 fix(UI): Make UI display 4096x2160 (DCI 4k) video as also being "4k"
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#8361 fix(HLS): Avoid duplicate init segment request when using SAMPLE-AES
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#8365 fix: Improve maxResolution detection on Tizen
  lib/util/platform.js
Labels: type: bug, priority: P2, platform: Tizen

#8364 feat(DASH): Add support for "Spoken Subtitles" in tva:metadata:cs:AudioPurpose
  lib/dash/dash_parser.js
  lib/media/manifest_parser.js
Labels: type: enhancement, priority: P3, component: DASH
