Repository shaka-project/shaka-player, pull requests merged in 2025-09, with the labels that each got.

#9041 fix(HLS): Improve abort decision logic
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P1

#9043 fix(HLS): Allow get better segment size estimations
  lib/hls/hls_parser.js
  lib/media/segment_reference.js
Labels: type: bug, component: HLS, priority: P2

#9042 fix: Avoid download init segments again when not necessary
  lib/media/segment_prefetch.js
  test/media/segment_prefetch_unit.js
Labels: type: bug, priority: P2

#9046 fix: Make sure that all variants are either: audio-only, video-only, or audio-video when preload
  lib/media/preload_manager.js
Labels: type: bug, priority: P2

#9049 perf(UI): Combine consecutive configure calls
  ui/audio_language_selection.js
  ui/text_selection.js
Labels: component: UI, type: performance, priority: P2

#9057 fix(UI): Respect prefers-reduced-transparency for tooltips and seekbar times
  ui/less/general.less
  ui/less/thumbnails.less
  ui/less/tooltip.less
Labels: type: bug, component: UI, type: accessibility, priority: P2

#9055 fix: prevent infinite loop when constructing CMCD relative urls
  lib/util/cmcd_manager.js
  test/util/cmcd_manager_unit.js
Labels: type: bug, priority: P1, component: CMCD

#9060 fix(Ads): Fix TypeError: null is not an object (evaluating 'b.mimeType.startsWith')
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#9059 fix: Attach mediaKeys when the device does not force us to wait for the encrypted event
  lib/drm/drm_engine.js
Labels: type: bug, component: EME, priority: P1

#9061 test: Update Safari screenshot
  test/test/assets/screenshots/safari-Mac/webvtt-ui-align-center-position-10-size-10.png
Labels: component: tests

#9064 fix: Fix some EMSG events missing
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#9070 fix(HLS): closeSegmentIndex of EXT-X-IMAGE-STREAM-INF when not necessary
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#9088 perf(HLS): Optimize mimetype resolution during parsing
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: component: HLS, type: performance, priority: P1

#9091 fix: Fix audio/video bandwidth calculation when only one of them is provided
  lib/util/stream_utils.js
Labels: type: bug, priority: P2

#9092 fix: Bad init segment size calculation when using byte ranges
  lib/media/segment_reference.js
Labels: type: bug, priority: P2

#9093 fix(HLS): Allow calculate stream bandwidth using segment size
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2

#9096 docs: Update MediaQualityChangedEvent description
  lib/player.js
Labels: type: docs

#9095 perf: Speed up `shaka.Player.probeSupport()`
  lib/drm/drm_engine.js
Labels: type: performance, priority: P1

#9101 feat: Change dvvC box to free box for Dolby Vision workarounds
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/device/abstract_device.js
  lib/device/i_device.js
  lib/hls/hls_parser.js
  lib/hls/hls_utils.js
  lib/media/content_workarounds.js
  lib/media/media_source_engine.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  lib/util/stream_utils.js
  test/media/adaptation_set_unit.js
  test/media/content_workarounds_unit.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P3

#9106 fix(UI): Change PiP icons to non filled variant
  ui/enums.js
Labels: type: bug, component: UI, priority: P1

#9107 feat(UI): Add video type button
  build/types/ui
  docs/tutorials/ui-customization.md
  shaka-player.uncompiled.js
  test/ui/ui_integration.js
  ui/enums.js
  ui/locales/en.json
  ui/locales/es.json
  ui/locales/fr.json
  ui/locales/nl.json
  ui/locales/source.json
  ui/resolution_selection.js
  ui/ui.js
  ui/video_type_selection.js
Labels: type: enhancement, component: UI, priority: P3

#9113 fix(UI): Change AirPlay icon to unfilled variant
  ui/enums.js
Labels: type: bug, component: UI, priority: P2

#9115 feat(UI): Ability to change UI icons
  build/types/ui
  demo/close_button.js
  demo/visualizer_button.js
  shaka-player.uncompiled.js
  ui/ad_statistics_button.js
  ui/airplay_button.js
  ui/audio_language_selection.js
  ui/cast_button.js
  ui/chapter_selection.js
  ui/enums.js
  ui/externs/ui.js
  ui/fast_forward_button.js
  ui/fullscreen_button.js
  ui/hidden_fast_forward_button.js
  ui/hidden_rewind_button.js
  ui/hidden_seek_button.js
  ui/icon.js
  ui/icon_registry.js
  ui/less/containers.less
  ui/less/material_svg_icon.less
  ui/less/overflow_menu.less
  ui/loop_button.js
  ui/material_svg_icon.js
  ui/mute_button.js
  ui/overflow_menu.js
  ui/pip_button.js
  ui/play_button.js
  ui/playback_rate_selection.js
  ui/recenter_vr.js
  ui/remote_button.js
  ui/resolution_selection.js
  ui/rewind_button.js
  ui/save_video_frame_button.js
  ui/settings_menu.js
  ui/skip_next_button.js
  ui/skip_previous_button.js
  ui/statistics_button.js
  ui/text_selection.js
  ui/toggle_stereoscopic.js
  ui/ui_utils.js
  ui/video_type_selection.js
Labels: type: enhancement, component: UI, priority: P3

#9105 feat(UI): Allow configure the key name for shortcuts and add some new ones
  ui/controls.js
  ui/externs/ui.js
  ui/save_video_frame_button.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#9121 fix(UI): apply background color only for configured icons
  ui/icon.js
  ui/less/material_svg_icon.less
Labels: type: bug, component: UI, priority: P1

#9122 fix: Support use addTextTrackAsync with NativeTextDisplayer
  lib/player.js
  test/player_integration.js
  test/player_src_equals_integration.js
Labels: type: bug, component: captions/subtitles, priority: P2

#9126 fix(MSS): Fix originalId creation in order to avoid duplicated originalId
  lib/mss/mss_parser.js
Labels: type: bug, priority: P2, component: MSS

#9133 fix: Always detect framerate as positive
  lib/util/ts_parser.js
Labels: type: bug, component: HLS, priority: P1

#9135 fix(HLS): Keep syncTime continuous by using previous value, if available
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#9138 fix: Fix CANNOT_ADD_EXTERNAL_CHAPTERS_TO_LIVE_STREAM error code
  lib/util/error.js
Labels: type: bug, priority: P1

#9131 perf(HLS): Optimise manifest text parser
  lib/hls/hls_utils.js
  lib/hls/manifest_text_parser.js
Labels: component: HLS, type: performance, priority: P1

#9145 fix(Ads): Fix bad detection of support multiple media elements on interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#9153 fix(HLS): Determine the duration of an HLS content when it ends live
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2
