Repository shaka-project/shaka-player, pull requests merged in 2025-04, with the labels that each got.

#8367 fix: FRMA generation
  lib/util/mp4_generator.js
Labels: type: bug, priority: P1

#8369 test: Change MSS URL for tests
  demo/common/assets.js
  test/mss/mss_player_integration.js
Labels: component: tests, component: MSS

#8366 feat(Offline): Make timeout for opening IndexedDB configurable
  docs/tutorials/offline.md
  lib/offline/indexeddb/storage_mechanism.js
Labels: type: enhancement, priority: P3, component: offline

#8368 test: Disable MSE recoveries in ContentWorkarounds integration
  test/media/content_workarounds_integration.js
Labels: component: tests

#8370 test: Use local assets in MSS tests
  karma.conf.js
  test/mss/mss_player_integration.js
  test/test/assets/mss-clear/Fragments(audio=0)
  test/test/assets/mss-clear/Fragments(audio=20201360)
  test/test/assets/mss-clear/Fragments(audio=40170521)
  test/test/assets/mss-clear/Fragments(audio=60139682)
  test/test/assets/mss-clear/Fragments(video=0)
  test/test/assets/mss-clear/Fragments(video=20020000)
  test/test/assets/mss-clear/Fragments(video=40040000)
  test/test/assets/mss-clear/Fragments(video=60060000)
  test/test/assets/mss-clear/Manifest
  test/test/assets/mss-playready/Fragments(audio=0)
  test/test/assets/mss-playready/Fragments(audio=20201360)
  test/test/assets/mss-playready/Fragments(audio=40170521)
  test/test/assets/mss-playready/Fragments(audio=60139682)
  test/test/assets/mss-playready/Fragments(video=0)
  test/test/assets/mss-playready/Fragments(video=20020000)
  test/test/assets/mss-playready/Fragments(video=40040000)
  test/test/assets/mss-playready/Fragments(video=60060000)
  test/test/assets/mss-playready/Fragments(video=80080000)
  test/test/assets/mss-playready/Manifest
Labels: component: tests, component: MSS

#8371 fix(HLS): Add key ids to Fairplay DRM parser
  lib/drm/fairplay.js
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P2, browser: Safari, component: FairPlay

#8375 test: Remove timeout on Tizen tests
  test/test/boot.js
Labels: component: tests, platform: Tizen

#8376 fix: Count line break characters as ASCII
  lib/util/string_utils.js
  test/util/string_utils_unit.js
Labels: type: bug, component: networking

#8380 ci: Allow detect when running in VM
  .github/workflows/build-and-test.yaml
  .github/workflows/selenium-lab-tests.yaml
  build/test.py
  karma.conf.js
  test/test/util/layout_tests.js
Labels: type: CI

#8381 test: Disable flaky test on Chromecast
  test/offline/storage_playback_integration.js
Labels: component: tests, platform: Cast

#8383 fix: Read TRUN data_offset as signed int
  lib/util/mp4_box_parsers.js
Labels: type: bug, priority: P3

#8387 fix: Support more Dolby codec notations
  lib/util/manifest_parser_utils.js
  lib/util/mime_utils.js
  test/util/mime_utils_unit.js
Labels: type: bug, priority: P2

#8385 fix: Handle missing window.matchMedia API
  lib/media/preference_based_criteria.js
Labels: type: bug, priority: P2

#8388 fix: Check addTextTrack in video
  lib/player.js
Labels: type: bug, priority: P1

#8384 fix: Handle null response body for fetch responses
  lib/net/http_fetch_plugin.js
Labels: type: bug, priority: P2, component: networking

#8392 fix: Fix cross boundary when playing at higher playbackRates
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#8393 fix(UI): honors singleClickForPlayAndPause when made a single tap with seekOnTaps = true
  ui/controls.js
  ui/hidden_seek_button.js
Labels: type: bug, component: UI, priority: P2

#8394 chore: Simplify timer for crossing boundaries
  lib/media/streaming_engine.js
  lib/player.js
Labels: type: code health

#8396 fix(UI): Don't allow click on the buttons when the UI is not visible
  demo/close_button.js
  ui/ad_statistics_button.js
  ui/airplay_button.js
  ui/cast_button.js
  ui/chapter_selection.js
  ui/controls.js
  ui/fast_forward_button.js
  ui/fullscreen_button.js
  ui/loop_button.js
  ui/mute_button.js
  ui/overflow_menu.js
  ui/pip_button.js
  ui/play_button.js
  ui/presentation_time.js
  ui/recenter_vr.js
  ui/remote_button.js
  ui/rewind_button.js
  ui/settings_menu.js
  ui/toggle_stereoscopic.js
Labels: type: bug, component: UI, priority: P1

#8386 feat: provide option to disable usage of source elements in MSE
  demo/config.js
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/player.js
  lib/util/player_configuration.js
  test/cast/cast_utils_unit.js
  test/drm/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
Labels: type: enhancement, priority: P3

#8401 fix(preload): Fix preload segments in some cases
  lib/media/preload_manager.js
Labels: type: bug, priority: P1

#8407 fix(UI): Show the video codec only when there are two codecs for the same resolution
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P1

#8410 fix: Cancel trick play when current time catch the seek range
  lib/player.js
  ui/fast_forward_button.js
  ui/rewind_button.js
Labels: type: bug, priority: P2

#8412 fix(UI): Improve layout of current time container above hovered seek bar
  ui/less/thumbnails.less
Labels: type: bug, component: UI, priority: P2

#8417 chore(Demo): Increase video container width
  demo/demo.less
Labels: component: demo page

#8415 feat: Use Date for playback start time
  lib/media/playhead.js
  lib/media/preload_manager.js
  lib/player.js
  test/media/playhead_unit.js
  test/test/util/simple_fakes.js
Labels: type: enhancement, priority: P3

#8420 fix(UI): Fix a11y issue with shaka.ui.AdInfo
  ui/ad_info.js
Labels: type: bug, component: UI, type: accessibility, priority: P2

#8418 feat(Stats): Add current codecs to stats
  externs/shaka/player.js
  lib/player.js
  lib/util/stats.js
  test/player_integration.js
  ui/statistics_button.js
  ui/ui.js
Labels: type: enhancement, priority: P3

#8419 feat(UI): Customize scrollbar style
  ui/less/overflow_menu.less
Labels: type: enhancement, component: UI, priority: P3

#8209 test: Add LCEVC SEI tests
  demo/common/assets.js
  demo/config.js
  docs/tutorials/lcevc.md
  externs/lcevc.js
  externs/shaka/player.js
  karma.conf.js
  lib/util/player_configuration.js
  package-lock.json
  package.json
  project-words.txt
  test/lcevc/lcevc_integration.js
  test/test/assets/lcevc-sei/lcevc-sei-1.mp4
  test/test/assets/lcevc-sei/lcevc-sei.mpd
Labels: component: tests

#8421 feat: Add oldEncrypted and newEncrypted to boundarycrossed event
  lib/media/streaming_engine.js
  lib/player.js
Labels: type: enhancement, priority: P3

#8424 feat(UI): Add scrollbar if necessary to statistics container
  ui/less/containers.less
Labels: type: enhancement, component: UI, priority: P3

#8425 fix(UI): Don't hide the UI when using the wheel over the UI
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8426 feat(UI): Hide volume slider when not hovering over the mute button
  ui/less/range_elements.less
Labels: type: enhancement, component: UI, priority: P3

#8428 chore(Demo): Disable visualizer button on full screen
  demo/visualizer_button.js
Labels: component: demo page

#8427 feat: Handle audio focus events
  lib/media/gap_jumping_controller.js
  project-words.txt
  test/media/stall_detector_unit.js
Labels: type: enhancement, priority: P3

#8429 feat(UI): Optimize the buttons that appear when using a Smart TV
  ui/ui.js
Labels: type: enhancement, platform: TV/STB, component: UI, priority: P3

#8433 fix(UI): Only show the volume bar on hover
  ui/less/range_elements.less
Labels: type: bug, component: UI, priority: P2

#8435 test: Fix UI tests on lab
  test/ui/ui_unit.js
Labels: component: UI, component: tests

#8436 feat(UI): Optimize default UI for small screens
  ui/less/ad_controls.less
  ui/less/range_elements.less
Labels: type: enhancement, component: UI, priority: P3

#8437 feat(UI): Show current playback rate and quality without hover
  ui/less/overflow_menu.less
  ui/playback_rate_selection.js
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P3

#8439 feat(DASH): Parse ProducerReferenceTime nodes
  build/check.py
  build/types/core
  cspell.config.yaml
  eslint.config.mjs
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/media/media_source_engine.js
  lib/util/time_utils.js
  test/dash/dash_parser_manifest_unit.js
  test/util/time_utils_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#8440 fix(UI): Avoid show resolution bandwidth when it's not necessary
  ui/resolution_selection.js
Labels: type: bug, component: UI, priority: P2

#8442 fix(Offline): Handle missing window.matchMedia API
  lib/util/player_configuration.js
Labels: type: bug, priority: P2, component: offline

#8443 perf(DASH): Release period combiner after parsing a VOD
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: performance, priority: P1, component: DASH

#8444 fix: Fix NTP conversion on Tizen 3
  lib/util/time_utils.js
  test/util/time_utils_unit.js
Labels: type: bug, priority: P2, platform: Tizen

#8445 chore: Unify HDR level detection
  lib/media/preference_based_criteria.js
  lib/util/platform.js
  lib/util/player_configuration.js
Labels: type: code health

#8446 feat(ABR): Add abr.removeLatencyFromFirstPacketTime config
  demo/config.js
  externs/shaka/player.js
  lib/abr/simple_abr_manager.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P3

#8451 feat(UI): Fix style of cast button on modern UI
  ui/cast_button.js
Labels: type: enhancement, component: UI, priority: P3

#8449 feat(UI): Disable add a cast button automatically on new UI
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3, platform: Cast

#8453 fix(UI): Check remote availability on remote button
  ui/remote_button.js
Labels: type: bug, component: UI, priority: P1

#8458 fix: Only expand robustness on each stream once
  lib/drm/drm_engine.js
Labels: type: bug, priority: P1

#8459 fix(HLS): Fix mp4 detection when the mimetype is application/octet-stream
  demo/common/assets.js
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#8460 fix: Keep unique references in getAudioTracks
  lib/player.js
Labels: type: bug, priority: P1

#8465 feat(UI): Update some selectors after loading content always
  ui/audio_language_selection.js
  ui/resolution_selection.js
  ui/text_selection.js
Labels: type: enhancement, component: UI, priority: P3

#8463 fix: Fix getVideoTracks when videoId is null but exists originalVideoId
  lib/player.js
Labels: type: bug, priority: P2

#8462 fix: Fix getAudioTracks when audioId is null but exists originalAudioId
  lib/player.js
Labels: type: bug, priority: P1

#8461 fix(UI): Show the remote button when we already connected
  ui/remote_button.js
Labels: type: bug, component: UI, priority: P2, platform: AirPlay

#8470 fix: Add a small fudge to prefetch eviction
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#8472 feat(UI): Allow forceDisconnect when destroy the UI
  lib/cast/cast_proxy.js
  ui/controls.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#8473 test: Fix LCEVC test
  test/lcevc/lcevc_integration.js
Labels: component: tests

#8476 fix: Subtitles appearing twice when switching to Fullscreen on iOS
  lib/player.js
Labels: type: bug, component: captions/subtitles, priority: P2, platform: iOS

#8477 feat: Expose Vast ad ID
  externs/mediatailor.js
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_static_ad.js
  lib/ads/media_tailor_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
Labels: type: enhancement, component: ads, priority: P2

#8489 fix(UI): Save track preferences for casting purposes
  ui/audio_language_selection.js
  ui/text_selection.js
Labels: type: bug, component: UI, priority: P2, platform: Cast

#8488 fix(UI): Disable doubleClickForFullscreen while casting
  ui/controls.js
Labels: type: bug, component: UI, priority: P2, platform: Cast

#8487 fix(UI): Sync volume and mute values when loading a new content or casting
  ui/mute_button.js
  ui/volume_bar.js
Labels: type: bug, component: UI, priority: P1

#8486 chore(Demo): Set chapter demo asset language to und
  demo/common/assets.js
Labels: component: demo page

#8484 feat(Demo): Modernize cast receiver demo
  demo/cast_receiver/idle1.jpg
  demo/cast_receiver/idle2.jpg
  demo/cast_receiver/idle3.jpg
  demo/cast_receiver/index.html
  demo/cast_receiver/receiver_app.css
  demo/cast_receiver/receiver_app.js
  demo/cast_receiver/shaka-player-logo.png
Labels: component: demo page, platform: Cast

#8485 feat(UI): Allow config cast sender URL
  demo/index.html
  ui/externs/ui.js
  ui/ui.js
Labels: type: enhancement, component: UI, priority: P3

#8494 fix(HLS): Fix text tracks disappear after seek
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, component: captions/subtitles, priority: P1

#8495 chore: Add more PlayReady keysystems
  lib/drm/drm_engine.js
  project-words.txt
Labels: component: PlayReady

#8496 test: Check recommendation keysystem to check PlayReady support
  test/drm/drm_engine_integration.js
  test/mss/mss_player_integration.js
  test/offline/offline_integration.js
  test/player_cross_boundary_integration.js
  test/player_integration.js
Labels: component: tests, component: PlayReady

#8499 chore(Demo): Avoid show available Dolby Vision P5 asset on unsupported platforms
  demo/common/assets.js
Labels: component: demo page

#8498 chore(Demo): Fix check DRM support
  demo/common/assets.js
  demo/main.js
  test/player_external.js
Labels: component: demo page

#8403 fix: Handle updateend event on duration reduction
  demo/config.js
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/util/player_configuration.js
Labels: type: bug, priority: P2

#8378 fix(CEA): cache and restore cea decoders based on the period continuity for dash content that uses SegmentTemplate
  lib/dash/dash_parser.js
  lib/dash/segment_base.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
  lib/media/closed_caption_parser.js
  lib/media/media_source_engine.js
  lib/media/segment_index.js
  lib/media/streaming_engine.js
  test/dash/dash_parser_manifest_unit.js
  test/media/closed_caption_parser_unit.js
  test/media/media_source_engine_unit.js
  test/media/segment_index_unit.js
  test/media/streaming_engine_unit.js
  test/test/externs/jasmine.js
  test/test/util/fake_media_source_engine.js
  test/test/util/simple_fakes.js
Labels: type: bug, component: captions/subtitles, priority: P2, component: DASH

#8500 fix: Fix initial buffering state when we load a stream
  lib/player.js
  test/player_integration.js
Labels: type: bug, priority: P1

#8502 feat(UI): Resolution selector should display width for vertical videos
  ui/resolution_selection.js
Labels: type: enhancement, component: UI, priority: P2

#8503 feat(Ads): Update DASH overlay implementation
  lib/ads/interstitial_ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: enhancement, component: ads, priority: P3

#8505 perf: Do not process stream DRM info several times
  lib/media/manifest_filterer.js
Labels: type: performance, priority: P1

#8507 perf: Remove extendedType when checking isTypeSupported on Tizen
  lib/polyfill/media_capabilities.js
Labels: type: performance, priority: P1, platform: Tizen

#8509 fix(UI): Fix get thumbnails while casting
  lib/cast/cast_utils.js
Labels: type: bug, component: UI, priority: P2, platform: Cast

#8504 test: Unify DRM checking in tests
  test/cast/cast_receiver_integration.js
  test/dash/dash_parser_integration.js
  test/drm/drm_engine_integration.js
  test/hls/hls_parser_integration.js
  test/mss/mss_player_integration.js
  test/offline/offline_integration.js
  test/offline/storage_integration.js
  test/offline/storage_playback_integration.js
  test/player_cross_boundary_integration.js
  test/player_integration.js
  test/test/boot.js
Labels: component: tests

#8512 fix: Fix exception updating partial config with deprecated fields
  lib/player.js
Labels: type: bug, priority: P1

#8513 fix(cast): Fix proxying of Player methods in CastProxy
  lib/cast/cast_proxy.js
  lib/cast/cast_utils.js
  test/cast/cast_utils_unit.js
Labels: type: bug, priority: P1, platform: Cast

#8515 fix: Allow use Chapter API on browsers without track element support
  lib/cast/cast_proxy.js
  lib/player.js
  lib/util/error.js
Labels: type: bug, priority: P2

#8516 feat(LCEVC): Add buffering support to dual track implementation
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3

#8497 fix: Fix Firefox PlayReady support
  lib/drm/drm_engine.js
  lib/util/player_configuration.js
  test/cast/cast_receiver_integration.js
Labels: type: bug, priority: P2, browser: Firefox, component: PlayReady

#8525 perf: Optimize getAllThumbnails()
  lib/player.js
Labels: type: performance, priority: P2

#8523 fix: Make sure we are calling setLiveSeekableRange and clearLiveSeekableRange at the correct time
  lib/media/media_source_engine.js
Labels: type: bug, priority: P1

#8517 fix: Add optional content workaround to force ENCA.ChannelCount to 2 for EAC-3 Audio init segments
  demo/config.js
  externs/shaka/player.js
  lib/media/content_workarounds.js
  lib/media/media_source_engine.js
  lib/util/player_configuration.js
  test/media/content_workarounds_unit.js
  test/test/assets/incorrect-enca-init.mp4
Labels: type: bug, priority: P2

#8527 fix: External text tracks in src mode related issues
  lib/player.js
  lib/util/dom_utils.js
Labels: type: bug, component: captions/subtitles, priority: P1

#8530 fix: Fix race condition stoping timers
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#8533 chore: Move addFont to DOM Utils
  lib/player.js
  lib/util/dom_utils.js
Labels: type: code health
