Repository shaka-project/shaka-player, pull requests merged in 2025-07, with the labels that each got.

#8818 chore: Move eme-encryption-scheme-polyfill to the Shaka Player repo
  build/types/polyfill
  demo/cast_receiver/index.html
  demo/index.html
  externs/polyfill.js
  karma.conf.js
  lib/device/abstract_device.js
  lib/device/chromecast.js
  lib/device/default_browser.js
  lib/device/i_device.js
  lib/device/webos.js
  lib/polyfill/eme_encryption_scheme.js
  lib/polyfill/encryption_scheme.js
  lib/polyfill/encryption_scheme_media_key_system_access.js
  lib/polyfill/encryption_scheme_utils.js
  lib/polyfill/mcap_encryption_scheme.js
  package-lock.json
  package.json
  project-words.txt
  shaka-player.uncompiled.js
Labels: type: code health

#8825 fix(DASH): Always fit segments to period boundaries on VOD
  lib/dash/segment_template.js
Labels: type: bug, priority: P2, component: DASH

#8833 chore: Move wait for encrypted event check to device API
  lib/device/abstract_device.js
  lib/device/default_browser.js
  lib/device/i_device.js
  lib/drm/drm_engine.js
Labels: type: code health, component: EME

#8834 chore: Simplify the call to attachAbrManager when allowMakeAbrManager is false
  lib/player.js
Labels: type: code health

#8837 fix(HLS): Fix playback of content with mixed containers (mp4 and ts)
  lib/hls/hls_parser.js
  test/hls/hls_parser_unit.js
Labels: type: bug, component: HLS, priority: P1

#8838 fix(LCEVC): Create segmentIndex on makeAbortDecision_
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#8842 fix(DASH): Consider codec profile when matching multi-period renditions
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P1, component: DASH

#8846 chore(Demo): Simplify the management of license headers
  demo/common/asset.js
Labels: component: demo page

#8852 feat(UI): Add Polish translation to skip previous button
  ui/locales/pl.json
Labels: type: enhancement, component: UI

#8855 feat(Transmuxer): Split init segment and segment data when appending to MSE
  externs/shaka/transmuxer.js
  lib/media/media_source_engine.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/h265.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
Labels: type: enhancement, priority: P2, component: transmuxer

#8861 chore: Add shouldUseCrossBoundaryLogic_ to simplify the streaming engine management
  lib/media/streaming_engine.js
Labels: type: code health

#8862 fix: Allow preload segments when we discard the reference by cross boundary logic
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#8863 fix: Live to VOD discards the wrong segments when crossBoundaryStrategy is not KEEP
  lib/dash/segment_base.js
  lib/dash/segment_template.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#8868 fix(Transmuxer): Fix width calculation when using HEVC-TS
  lib/transmuxer/h265.js
Labels: type: bug, priority: P2, component: transmuxer

#8869 fix(DASH): Update timeline on PTO change
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#8873 fix(HLS): Fix preload initial variant on Tizen
  lib/media/preload_manager.js
Labels: type: bug, priority: P1, platform: Tizen

#8876 feat(DASH): Change from L3D to non-L3D after the successful playback
  externs/shaka/abr_manager.js
  lib/abr/simple_abr_manager.js
  lib/media/preload_manager.js
  lib/media/segment_prefetch.js
  lib/media/streaming_engine.js
  lib/player.js
  test/media/streaming_engine_integration.js
  test/media/streaming_engine_unit.js
Labels: type: enhancement, priority: P3, component: DASH

#8879 fix(UI): Don't exit Fullscreen and PiP when unloading an ad
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8881 test: Fix msedgedriver install
  package-lock.json
  package.json
Labels: component: tests

#8880 fix(Ads): Fix AD_STARTED delayed when using the base video
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#8883 chore(Demo): Add new Dolby Vision assets
  demo/common/assets.js
  demo/main.js
  lib/media/media_source_engine.js
Labels: component: demo page

#8884 fix(DASH): Prevent memory leak in uncompiled mode
  lib/dash/dash_parser.js
Labels: type: bug, priority: P3, component: DASH

#8888 chore(DASH): Add comments to latest DashParser changes
  lib/dash/dash_parser.js
Labels: type: code health, component: DASH

#8890 chore: Simplify ABR management between player and preload manager
  lib/abr/simple_abr_manager.js
  lib/media/preload_manager.js
  lib/player.js
Labels: type: code health

#8894 fix(Demo): Interact with queueManager before do any adManager operation
  demo/main.js
Labels: type: bug, component: demo page, priority: P1

#8896 fix: Fix default value of defaultAudioRobustnessForWidevine and defaultVideoRobustnessForWidevine on Android
  externs/shaka/player.js
  lib/device/default_browser.js
Labels: type: bug, priority: P2, platform: Android

#8897 perf(Ads): Reduce VMAP processing time
  lib/ads/interstitial_ad_manager.js
Labels: type: performance, component: ads, priority: P1

#8899 perf(Ads): Improve the startup of interstitials when the starttime is 0
  lib/ads/interstitial_ad_manager.js
Labels: type: performance, component: ads, priority: P1

#8900 chore(CMCD): Improvements to the CMCD manager code
  lib/util/cmcd_manager.js
Labels: type: code health, component: CMCD

#8901 build: Require jsdoc for classes and methods
  eslint.config.mjs
Labels: type: code health, component: build system

#8902 chore(CMCD): Create two new functions that simplify the code
  lib/util/cmcd_manager.js
Labels: type: code health, component: CMCD

#8903 feat(Ads): Support clickThroughUrl on interstitials ad manager
  docs/tutorials/ad_monetization.md
  externs/shaka/ads.js
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
  lib/ads/interstitial_static_ad.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: enhancement, component: ads, priority: P3

#8906 feat(Queue): Allow include preloadManager in QueueItem
  demo/main.js
  externs/shaka/queue.js
  lib/queue/queue_manager.js
  test/queue/queue_manager_unit.js
Labels: type: enhancement, priority: P3

#8913 chore(CMCD): Remove useless default params in some methods
  lib/util/cmcd_manager.js
Labels: type: code health, component: CMCD

#8916 fix: Fix URI encoding with plus characters
  third_party/closure-uri/uri.js
Labels: type: bug, priority: P2

#8909 fix(DASH): Update SegmentSequenceProperties according to latest spec
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#8915 fix: Fix Apple Vision Pro integration with some features
  lib/ads/interstitial_ad_manager.js
  lib/player.js
Labels: type: bug, priority: P2, browser: Safari

#8918 fix: Session Update Error Handling For Youview Platform
  lib/drm/drm_engine.js
Labels: type: bug, component: EME, platform: TV/STB, priority: P2

#8921 perf: Simplify region timeline buffer management
  lib/player.js
Labels: type: performance, priority: P3

#8929 chore: Simplify back to play after MSE reset
  lib/media/streaming_engine.js
Labels: type: code health

#8925 chore: Update to the latest Closure Compiler
  .github/workflows/build-and-test.yaml
  .github/workflows/selenium-lab-tests.yaml
  build/README.md
  build/build.py
  build/docker/Dockerfile
  build/install-linux-prereqs.sh
  docs/tutorials/welcome.md
  externs/media_remote.js
  externs/pictureinpicture.js
  externs/trackevent.js
  lib/polyfill/patchedmediakeys_apple.js
  lib/polyfill/patchedmediakeys_webkit.js
  package-lock.json
  package.json
Labels: component: build system

#8930 fix: Reset MSE when the current readyState is closed
  lib/media/streaming_engine.js
  test/test/util/fake_media_source_engine.js
Labels: type: bug, priority: P1, browser: Safari

#8935 chore: Simplify onKeyStatus_ method
  lib/player.js
Labels: type: code health

#8936 fix(DASH): Fix Playback Fails on Widevine L1/L3 Streams
  lib/player.js
Labels: type: bug, priority: P1

#8937 docs: Add missing UI events
  ui/controls.js
Labels: type: docs

#8940 chore: Fix ad definition on UI extern
  ui/externs/ui.js
Labels: type: code health

#8939 chore: Fix isoboxer extern
  externs/isoboxer.js
Labels: type: code health

#8941 chore: Fix some extends definitions
  lib/dash/segment_template.js
  lib/media/segment_index.js
Labels: type: code health

#8944 feat: Expose video roles in Track and VideoTrack
  externs/shaka/player.js
  lib/player.js
  lib/util/stream_utils.js
  test/offline/storage_integration.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#8945 feat: Support videoRole in AdaptationSetCriteria
  demo/config.js
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/media/adaptation_set_criteria.js
  lib/media/preference_based_criteria.js
  lib/media/preload_manager.js
  lib/player.js
  lib/util/player_configuration.js
  test/media/adaptation_set_criteria_unit.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#8947 feat: Expose video label in Track and VideoTrack
  externs/shaka/player.js
  lib/player.js
  lib/util/stream_utils.js
  test/offline/storage_integration.js
  test/player_unit.js
Labels: type: enhancement, priority: P3
