Repository shaka-project/shaka-player, pull requests merged in 2025-02, with the labels that each got.

#8003 fix(HLS): Populate originalVideoId in HLS with the URI
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#8002 fix: Add more info in getVariantTracks for muxed streams
  lib/util/stream_utils.js
Labels: type: bug, priority: P2

#8006 docs: Update Roadmap
  roadmap.md
Labels: type: docs

#8011 fix(CMCD): Only report ltc if playing; round to int
  CONTRIBUTORS
  lib/player.js
  test/player_unit.js
Labels: type: bug, priority: P2, component: CMCD

#8015 ci: Add Google TV Streamer in the lab
  .github/workflows/shaka-bot-commands/command-test.sh
  build/shaka-lab.yaml
Labels: type: CI, platform: Cast

#8005 feat: Create a new simple API for Audio
  docs/tutorials/upgrade.md
  externs/shaka/player.js
  lib/cast/cast_utils.js
  lib/player.js
  lib/util/array_utils.js
  lib/util/fake_event.js
  lib/util/stream_utils.js
  project-words.txt
  roadmap.md
  test/codec_switching/codec_switching_integration.js
  test/offline/storage_integration.js
  test/player_unit.js
  ui/audio_language_selection.js
  ui/language_utils.js
  ui/text_selection.js
Labels: type: enhancement, priority: P3

#8013 fix: Duplicate timelineregion* events fired for the same event id
  lib/media/region_timeline.js
Labels: type: bug, priority: P2

#8014 fix: Avoid launch RESTRICTIONS_CANNOT_BE_MET when it's not necessary
  lib/player.js
Labels: type: bug, priority: P1

#8018 fix(Subtitles): Prevent rounding errors when filtering duplicated cues
  lib/text/cue.js
Labels: type: bug, component: captions/subtitles, priority: P2

#8026 fix: Evict the buffer against seekRangeStart
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  test/media/streaming_engine_unit.js
Labels: type: bug, priority: P1

#8030 chore: Simplify StallDetector creation to a single place
  lib/media/gap_jumping_controller.js
  lib/media/playhead.js
  lib/media/stall_detector.js
Labels: type: code health

#8031 feat: Add avoidEvictionOnQuotaExceededError config
  demo/config.js
  externs/shaka/player.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P4

#8012 feat: Time ID3, emsg, and metadata events to the presentation timeline
  externs/shaka/player.js
  lib/media/media_source_engine.js
  lib/player.js
  test/cast/cast_utils_unit.js
  test/drm/drm_engine_integration.js
  test/media/media_source_engine_integration.js
  test/media/media_source_engine_unit.js
  test/media/streaming_engine_integration.js
Labels: type: enhancement, priority: P3

#8033 feat: Change the way to handle the STREAMING_NOT_ALLOWED error
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3

#8028 chore: Simplify the logic of the playback rate button
  ui/playback_rate_selection.js
Labels: type: code health

#8035 chore: Simplify Apple detection
  lib/polyfill/media_capabilities.js
  lib/util/platform.js
  test/util/platform_unit.js
Labels: type: code health, priority: P2, platform: macOS, platform: iOS

#8036 build: Add new builds with only HLS or DASH
  .github/workflows/build-and-test.yaml
  README.md
  build/all.py
  build/types/complete
  build/types/optionalText
  build/types/text
Labels: component: build system

#8038 fix: audio label when selecting variants by label
  lib/player.js
Labels: type: bug, priority: P1

#8043 test: Fix new platform tests on Android
  test/util/platform_unit.js
Labels: priority: P1, component: tests

#8044 docs: Fix design links
  README.md
  docs/tutorials/architecture.md
  docs/tutorials/lcevc.md
Labels: type: docs

#8047 chore: Update LCEVC decoder to latest version 1.2.0
  docs/tutorials/lcevc.md
  package-lock.json
  package.json
Labels: dependencies

#8046 fix: Throw preload destroyed error when re-using same preloadManager
  lib/player.js
  lib/util/error.js
Labels: type: bug, priority: P2

#8049 feat: Add Vizio as community support
  README.md
  externs/shaka/player.js
  lib/util/platform.js
  project-words.txt
  test/util/platform_unit.js
Labels: type: enhancement, platform: TV/STB, priority: P4

#8053 feat: Do not make corrective seeks when setLiveSeekableRange is used
  lib/media/playhead.js
  test/media/playhead_unit.js
Labels: type: enhancement, priority: P3

#8051 feat(Ads): Add support for L-Shape ad experience
  docs/tutorials/ad_monetization.md
  externs/shaka/ads.js
  lib/ads/ad_utils.js
  lib/ads/interstitial_ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: enhancement, component: ads, priority: P3

#8055 fix(DASH): Fix playback of ClearKey when only part of keys are defined
  lib/util/periods.js
  test/util/periods_unit.js
Labels: type: bug, priority: P1, component: DASH, component: ClearKey

#8057 feat(DASH): Add dependencyVideo to video streams
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  test/dash/dash_parser_manifest_unit.js
  test/media/adaptation_set_unit.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
Labels: type: enhancement, priority: P3, component: DASH

#8058 fix(net): Allow preventDefault() on retry event
  lib/net/networking_engine.js
  test/net/networking_engine_unit.js
Labels: type: bug, priority: P1, component: networking

#8064 fix(tXml): Allow case insensitive in parseDuration
  lib/util/tXml.js
  test/util/tXml_unit.js
Labels: type: bug, priority: P3

#8065 feat(Ads): Update DASH Media Presentation Insertion according to the latest draft
  externs/shaka/player.js
  lib/ads/interstitial_ad_manager.js
  lib/dash/dash_parser.js
  lib/player.js
  test/ads/interstitial_ad_manager_unit.js
  test/dash/dash_parser_live_unit.js
  test/media/region_observer_unit.js
  test/media/region_timeline_unit.js
  test/test/assets/dash-mpd-alternate/dash.mpd
Labels: type: enhancement, component: ads, priority: P3, component: DASH

#8070 fix: Fix DRM workaround with fLaC and Opus boxes
  lib/media/content_workarounds.js
  test/media/content_workarounds_unit.js
Labels: type: bug, component: EME, platform: Tizen

#8069 ci: Deploy nightly after push on main branch
  .github/workflows/nightly-demo.yaml
Labels: type: CI

#8076 docs: Update retry documentation
  docs/tutorials/errors.md
Labels: type: docs

#8078 docs: Remove shaka-player-user group info
  README.md
  docs/announcement-list-join-group.png
Labels: type: docs

#8075 fix(Ads): Only set ad-active in the controls-container when the ad has custom clicks
  externs/shaka/ads.js
  lib/ads/client_side_ad.js
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_static_ad.js
  lib/ads/media_tailor_ad.js
  lib/ads/server_side_ad.js
  test/test/util/fake_ad.js
  ui/controls.js
Labels: type: bug, component: ads, priority: P3

#8079 docs: Update maintainers list on package.json
  package.json
Labels: type: docs

#8082 fix(Ads): Reset playRangeEnd value between interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P1

#8084 fix(HLS): Fix duplicate segments on some inaccurate live streams
  lib/media/streaming_engine.js
Labels: type: bug, component: HLS, priority: P1

#8085 fix(Ads): Remove default background color on interstitial overlay
  lib/ads/interstitial_ad_manager.js
Labels: type: bug, component: ads, priority: P2

#8086 fix(Ads): Support urn:scte:dash:scte214-events schemeIdUri for overlays
  lib/ads/ad_manager.js
  test/ads/interstitial_ad_manager_unit.js
Labels: type: bug, component: ads, priority: P2

#8089 fix(UI): Fix thumbnail sometimes not disappearing due to mouse hover
  ui/less/thumbnails.less
Labels: type: bug, component: UI, priority: P2

#8088 fix(TTML): Correctly handle multiple samples in a segment
  AUTHORS
  CONTRIBUTORS
  lib/text/mp4_ttml_parser.js
  test/test/assets/ttml-segment-multiple-mdat.mp4
  test/test/assets/ttml-segment-multiple-sample.mp4
  test/text/mp4_ttml_parser_unit.js
Labels: type: bug, component: TTML, priority: P1

#8083 fix(WebOS): Do not preload DRM on legacy EME
  lib/drm/drm_engine.js
  lib/media/preload_manager.js
  lib/player.js
Labels: type: bug, priority: P1, component: PlayReady, platform: WebOS

#8095 feat: Deprecate selectVariantsByLabel because the same can be done with the new Audio API
  lib/player.js
Labels: type: enhancement, priority: P3

#8099 chore(Demo): Fix broken demo search
  demo/search.js
Labels: component: demo page, priority: P1

#8100 fix(UI): Improve performance and compatibility with MediaSession
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8096 build: Move some types to improve the build size
  build/types/core
  build/types/dash
  build/types/transmuxer
  lib/dash/mp4_segment_index_parser.js
  lib/dash/segment_base.js
  lib/dash/webm_segment_index_parser.js
  lib/mss/mss_parser.js
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/mp4_generator.js
  lib/transmuxer/ts_transmuxer.js
  test/dash/mp4_segment_index_parser_unit.js
  test/dash/webm_segment_index_parser_unit.js
Labels: priority: P1, component: build system

#8102 perf: Use navigator.userAgentData.platform to detect Android and Fuchsia
  lib/util/platform.js
  test/polyfill/media_capabilities_unit.js
Labels: type: performance, priority: P3

#8101 build: Add polyfillForUI type
  build/all.py
  build/types/complete
  build/types/polyfill
  build/types/polyfillForUI
Labels: component: build system

#8103 fix: Install Safari workarounds on WPE STBs
  README.md
  lib/drm/drm_engine.js
  lib/player.js
  lib/polyfill/mediasource.js
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, browser: Safari

#8105 chore: Simplify older Chromecast detection
  lib/polyfill/media_capabilities.js
  lib/util/platform.js
  test/polyfill/media_capabilities_unit.js
Labels: priority: P3, platform: Cast

#8107 docs: Update DRM tutorial with latest features
  docs/tutorials/drm-config.md
  docs/tutorials/license-server-auth.md
Labels: type: docs

#8104 fix: Remove isSafari and always use isApple
  lib/util/platform.js
  lib/util/stream_utils.js
  ui/remote_button.js
Labels: type: bug, priority: P2

#8106 fix(FairPlay): Install by default shaka.polyfill.PatchedMediaKeysApple on older Safari versions
  docs/tutorials/fairplay.md
  lib/polyfill/patchedmediakeys_apple.js
Labels: type: bug, component: EME, priority: P2, component: FairPlay

#8114 perf: Only set the timers on UITextDisplayer when there are cues
  lib/text/ui_text_displayer.js
Labels: type: performance, component: captions/subtitles, priority: P1

#8115 perf(UI): Reduce configure calls to use shakaPlayerCastReceiverId
  ui/ui.js
Labels: component: UI, type: performance, priority: P1

#8113 perf(Ads): Only create the listeners/timers when there are interstitials
  lib/ads/interstitial_ad_manager.js
Labels: type: performance, component: ads, priority: P1

#8119 ci: Check if screenshot PR exists before creating new one
  .github/workflows/update-screenshots.yaml
Labels: type: CI

#8118 perf: Remove promises from getAllThumbnails loop
  lib/player.js
Labels: type: performance, priority: P1

#8127 chore: Improve karma launcher error resiliency
  package-lock.json
  package.json
Labels: dependencies

#8126 fix(DASH): ContentSteering promise is resolved too late for fetching of init segment
  lib/dash/dash_parser.js
Labels: type: bug, priority: P2, component: DASH

#8128 perf: Close segmentIndex after getAllThumbnails
  lib/player.js
Labels: type: performance, priority: P1

#8132 fix(DASH): Revert Dolby Atmos detection when there is not SupplementalProperty
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#8129 feat: Allow acquire thumbnails without track ID
  externs/shaka/player.js
  lib/player.js
  test/player_integration.js
  test/player_src_equals_integration.js
  ui/seek_bar.js
Labels: type: enhancement, priority: P3

#8133 fix: Fix Hisense 4K detection
  lib/util/platform.js
Labels: type: bug, platform: TV/STB, priority: P1

#8125 fix: Check bandwidth when filtering streams
  lib/util/stream_utils.js
  test/util/stream_utils_unit.js
Labels: type: bug, priority: P2

#8122 test: Reject all FF+Windows ClearKey testing
  lib/drm/drm_engine.js
Labels: browser: Firefox, component: tests

#8135 ci: Handle screenshot updates with no changes
  .github/workflows/update-screenshots.yaml
Labels: type: CI

#8134 feat(LCEVC): Detect as supported dual track content with LCEVC
  demo/common/assets.js
  externs/lcevc.js
  externs/shaka/manifest.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/lcevc/lcevc_dec.js
  lib/media/media_source_engine.js
  lib/mss/mss_parser.js
  lib/offline/manifest_converter.js
  lib/offline/storage.js
  lib/player.js
  lib/util/periods.js
  lib/util/stream_utils.js
  test/dash/dash_parser_manifest_unit.js
  test/media/adaptation_set_unit.js
  test/offline/manifest_convert_unit.js
  test/test/util/manifest_generator.js
  test/test/util/streaming_engine_util.js
Labels: type: enhancement, priority: P3

#8140 test: Disable HEVC tests on Firefox Windows
  test/test/util/util.js
Labels: browser: Firefox, component: tests

#8141 chore: Simplify StallDetector
  lib/media/gap_jumping_controller.js
  lib/media/stall_detector.js
  test/media/stall_detector_unit.js
Labels: type: code health

#8147 test: Disable DV-P8 tests on Safari
  test/player_dolby_vision_integration.js
Labels: browser: Safari, component: tests

#8148 chore: Unify GapJumpingController and StallDetector in the same file
  build/types/core
  lib/media/gap_jumping_controller.js
  lib/media/stall_detector.js
Labels: type: code health

#8149 fix(CMCD): Do not call play() if CMCD is not enabled
  lib/util/cmcd_manager.js
Labels: type: bug, priority: P2, component: CMCD

#8150 chore: Simplify gapPadding config
  lib/media/gap_jumping_controller.js
  lib/util/player_configuration.js
Labels: type: code health

#8151 test: Enable stall detector on gap jumping tests
  test/media/streaming_engine_integration.js
Labels: component: tests

#8153 fix(HLS): Populate encrypted info correctly on updates
  lib/hls/hls_parser.js
  test/hls/hls_live_unit.js
Labels: type: bug, component: HLS, priority: P2

#8152 test: Increase playback time on HLS integration test
  test/hls/hls_parser_integration.js
Labels: component: tests

#8157 chore: Create a new method appendDependency in MediaSourceEngine
  lib/media/media_source_engine.js
Labels: type: code health

#8158 docs: Update Roadmap
  roadmap.md
Labels: type: docs

#8162 fix: Fit template check template info
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#8168 feat: Add LCEVC dual track rendering
  lib/media/streaming_engine.js
Labels: type: enhancement, priority: P3

#8170 ci: Enable Widevine on Firefox
  build/shaka-lab.yaml
Labels: type: CI

#8171 chore: Update karma-local-wd-launcher
  package-lock.json
  package.json
Labels: dependencies

#8172 fix: Remove timeout for decodingInfo in some platforms and increase the timeout
  lib/drm/drm_engine.js
  lib/util/stream_utils.js
Labels: type: bug, priority: P1

#8173 test: Fix crash of Firefox on Windows
  lib/drm/drm_engine.js
Labels: browser: Firefox, component: tests

#8177 chore(Demo): Add new FairPlay asset from Axinom
  demo/common/assets.js
Labels: component: demo page

#8178 chore(Demo): Simplify low latency assets config
  demo/common/asset.js
  demo/common/assets.js
Labels: type: code health, component: demo page

#8180 fix(UI): Use touchend to show the controls
  ui/controls.js
Labels: type: bug, component: UI, priority: P2

#8181 fix: Fix seek to initial live position on slow devices
  lib/media/gap_jumping_controller.js
Labels: type: bug, priority: P1

#8160 test: Add integration test for mixed clear+encrypted content
  karma.conf.js
  test/media/content_workarounds_integration.js
  test/test/assets/clear-encrypted/0001.m4s
  test/test/assets/clear-encrypted/0002.m4s
  test/test/assets/clear-encrypted/init-1.mp4
  test/test/assets/clear-encrypted/init-2.mp4
  test/test/assets/clear-encrypted/manifest.mpd
Labels: component: tests

#8186 fix(UI): Fix weird behaviour when volume was 0, and we unmute
  ui/mute_button.js
  ui/volume_bar.js
Labels: type: bug, component: UI, priority: P2

#8183 perf: Pause PlayheadObserverManager operations on pause event
  lib/media/playhead_observer.js
Labels: type: performance, priority: P1

#8188 fix: Prevent race condition when seeking backwards during load
  lib/player.js
Labels: type: bug, priority: P2

#8187 feat: Allow preload text tracks and expose the preloaded variant and text tracks
  lib/media/preload_manager.js
  lib/player.js
  lib/util/stream_utils.js
Labels: type: enhancement, priority: P3

#8189 build: Move EBML parser to dash to improve the build size
  build/types/core
  build/types/dash
  lib/dash/ebml_parser.js
  lib/dash/webm_segment_index_parser.js
  test/dash/ebml_parser_unit.js
Labels: component: build system
