Repository shaka-project/shaka-player, pull requests merged in 2025-01, with the labels that each got.

#7817 fix: Remove useless calls to isTypeSupported
  lib/media/media_source_engine.js
  lib/util/stream_utils.js
  test/transmuxer/transmuxer_integration.js
Labels: type: bug, priority: P2

#7813 fix(Transmuxer): Fix transmuxer with overflow data (video nalus and aac samples) between PES
  externs/shaka/codecs.js
  karma.conf.js
  lib/transmuxer/h264.js
  lib/transmuxer/ts_transmuxer.js
  lib/util/ts_parser.js
  test/test/assets/hls-ts-muxed-aac-h264-with-overflow-nalus/fileSequence0.ts
  test/test/assets/hls-ts-muxed-aac-h264-with-overflow-nalus/media.m3u8
  test/test/assets/hls-ts-muxed-aac-h264-with-overflow-samples/fileSequence0.ts
  test/test/assets/hls-ts-muxed-aac-h264-with-overflow-samples/media.m3u8
  test/transmuxer/transmuxer_integration.js
Labels: type: bug, priority: P1, component: transmuxer

#7818 fix: Avoid useless MSE reset when transmuxing muxed content
  lib/media/media_source_engine.js
  test/transmuxer/transmuxer_integration.js
Labels: type: bug, priority: P1

#7823 fix: Fix change timestampOffset on discontinuities when not necessary
  lib/media/media_source_engine.js
Labels: type: bug, component: HLS, priority: P2, browser: Safari

#7822 fix: Fix gaps produced by the transmuxer
  lib/transmuxer/aac_transmuxer.js
  lib/transmuxer/ac3_transmuxer.js
  lib/transmuxer/ec3_transmuxer.js
  lib/transmuxer/mp3_transmuxer.js
  lib/transmuxer/ts_transmuxer.js
  test/transmuxer/transmuxer_integration.js
Labels: type: bug, priority: P1, component: transmuxer

#7821 test: Enable some Tizen test
  test/transmuxer/transmuxer_integration.js
Labels: component: tests, platform: Tizen

#7820 test: Enable disabled test for Chromecast
  lib/polyfill/media_capabilities.js
  test/transmuxer/transmuxer_integration.js
Labels: component: tests, platform: Cast

#7825 fix: Follow the configured playRange for src=
  lib/cast/cast_utils.js
  lib/player.js
  ui/controls.js
  ui/play_button.js
Labels: type: bug, priority: P2

#7828 chore(Demo): Allow set defaultPresentationDelay with decimal values
  demo/config.js
Labels: component: demo page

#7827 fix(Offline): Allow downloading AES content
  externs/shaka/manifest.js
  lib/hls/hls_parser.js
  lib/offline/download_info.js
  lib/offline/storage.js
  test/offline/storage_playback_integration.js
Labels: type: bug, priority: P2, component: offline

#7836 chore(Demo): Add new DRM assets from livesim2
  demo/common/assets.js
Labels: component: demo page

#7837 fix(CEA): Fix multi byte language support in CEA-708
  lib/cea/cea708_service.js
  lib/cea/dtvcc_packet_builder.js
  test/cea/cea708_service_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7838 fix(HLS): Fix audio detection when there is no audio data but it appears in PMT
  lib/media/segment_utils.js
Labels: type: bug, component: HLS, priority: P2

#7840 fix(HLS): Disable text correctly when loading a media playlist
  lib/hls/hls_parser.js
  lib/media/segment_utils.js
Labels: type: bug, component: HLS, priority: P2

#7841 fix(HLS): Omit daterange without START-DATE in order to avoid errors
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#7842 fix(Offline): Fix some aborted downloads continue to download
  lib/offline/download_manager.js
  lib/offline/storage.js
Labels: type: bug, priority: P2, component: offline

#7843 chore(Demo): Fix "Custom DRM System" field when set to known drm system
  demo/custom.js
Labels: component: demo page, priority: P2

#7846 fix: Fix select spatial audio when using selectAudioLanguage
  lib/player.js
  ui/audio_language_selection.js
Labels: type: bug, priority: P2

#7847 fix(DASH): Fix Dolby Atmos detection when there is not SupplementalProperty
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#7845 chore(Demo): Add keysystem suggestions in "Custom DRM System" field
  demo/custom.js
Labels: type: enhancement, component: demo page

#7850 ci: Increase "Build Player" timeout
  .github/workflows/build-and-test.yaml
Labels: type: CI

#7848 fix(UI): Show Dolby Atmos name in the UI
  ui/language_utils.js
Labels: type: bug, component: UI, priority: P2

#7849 fix(dash): Fix $Time$ usage with SegmentTemplate
  lib/dash/mpd_utils.js
  lib/dash/segment_template.js
  test/dash/dash_parser_segment_template_unit.js
  test/test/util/manifest_parser_util.js
Labels: type: bug, priority: P1, component: DASH

#7851 fix: Fix SEGMENT HEAD requests, compatibility with Cast SDK
  lib/net/http_fetch_plugin.js
  lib/net/http_plugin_utils.js
Labels: type: bug, component: HLS, priority: P1, platform: Cast

#7854 feat: Add support for WisePlay DRM
  README.md
  lib/drm/drm_engine.js
  lib/hls/hls_parser.js
  lib/offline/storage.js
  lib/util/player_configuration.js
  package-lock.json
  package.json
  project-words.txt
  test/dash/dash_parser_content_protection_unit.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, priority: P3, component: WisePlay

#7858 test: Update screenshots
  test/test/assets/screenshots/firefox-Mac/webvtt-ui-underline-long.png
  test/test/assets/screenshots/safari-Mac/webvtt-ui-underline-long.png
Labels: component: tests

#7857 feat(net): Add originalRequest to shaka.extern.Response
  externs/shaka/net.js
  lib/net/data_uri_plugin.js
  lib/net/http_fetch_plugin.js
  lib/net/http_plugin_utils.js
  lib/net/http_xhr_plugin.js
  lib/offline/offline_scheme.js
  test/media/streaming_engine_unit.js
  test/net/networking_engine_unit.js
  test/test/util/fake_networking_engine.js
  test/test/util/test_scheme.js
Labels: type: enhancement, priority: P3, component: networking

#7860 ci: Update release-please-action
  .github/workflows/release-please.yaml
Labels: type: CI

#7864 fix(HLS): Assign EXT-X-TILES to segment tags
  lib/hls/manifest_text_parser.js
Labels: type: bug, component: HLS, priority: P2

#7865 fix(Offline): Fix download HLG tracks when using AUTO hdr level
  lib/util/player_configuration.js
Labels: type: bug, priority: P2, component: offline

#7866 fix: Fix isEnded for live streams
  lib/player.js
Labels: type: bug, priority: P2

#7867 fix: Use getSegmentAvailabilityStart instead of getSeekRangeStart to evict segments
  lib/dash/dash_parser.js
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#7868 feat: Create segmentIndex when there is only one variant
  lib/hls/hls_parser.js
  lib/media/preload_manager.js
  lib/player.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, priority: P3

#7869 chore: Remove old TODO about IE 11
  ui/range_element.js
Labels: type: code health

#7879 fix(UI): Fix handle of seek on MediaSession
  ui/controls.js
Labels: type: bug, priority: P2

#7881 fix: Silence uncaught rejection errors when closing EME sessions
  lib/drm/drm_engine.js
Labels: type: bug, component: EME, priority: P2, component: offline

#7880 feat(ABR): Use PiP window size when using documentPictureInPicture
  lib/abr/simple_abr_manager.js
Labels: type: enhancement, priority: P3

#7882 feat(ABR): Use PiP window size when using requestPictureInPicture
  externs/pictureinpicture.js
  lib/abr/simple_abr_manager.js
Labels: type: enhancement, priority: P3

#7883 fix: Fix isEnded when is not fullyLoaded
  lib/player.js
Labels: type: bug, priority: P2

#7884 fix: Detect mov extension as video/quicktime
  lib/net/networking_utils.js
Labels: type: bug, priority: P3

#7886 feat: Add adaptation set criteria factory configuration
  externs/shaka/player.js
  lib/media/adaptation_set.js
  lib/media/adaptation_set_criteria.js
  lib/media/example_based_criteria.js
  lib/media/preference_based_criteria.js
  lib/media/preload_manager.js
  lib/player.js
  lib/util/player_configuration.js
  test/media/adaptation_set_criteria_unit.js
  test/player_unit.js
Labels: type: enhancement, priority: P3

#7877 feat: Add Watermark Support to Shaka Player UI
  CONTRIBUTORS
  build/types/ui
  demo/config.js
  demo/main.js
  test/test/util/fake_demo_main.js
  ui/externs/watermark.js
  ui/ui.js
  ui/watermark.js
Labels: type: enhancement, component: UI

#7889 perf: Improve times of probeSupport
  lib/drm/drm_engine.js
  lib/drm/drm_utils.js
  test/drm/drm_utils_unit.js
Labels: type: performance, priority: P2

#7895 feat: Add watermark to uncompiled mode
  shaka-player.uncompiled.js
Labels: type: enhancement, priority: P3

#7894 chore: Remove "Override Cast Receiver App ID" in the nightly workflow
  .github/workflows/nightly-demo.yaml
Labels: component: demo page

#7891 docs: Cleanup of docs/design directory
  docs/design/current/architecture.md
  docs/design/current/cast.gv
  docs/design/current/cast.gv.png
  docs/design/current/chromecast.md
  docs/design/current/codec_preferences.md
  docs/design/current/dash-audio-channels.md
  docs/design/current/dash-manifests.md
  docs/design/current/dash-timeline.svg
  docs/design/current/dataflow.gv
  docs/design/current/dataflow.gv.png
  docs/design/current/export.md
  docs/design/current/fuzzy-locale-matching.md
  docs/design/current/gap-jumping.md
  docs/design/current/lcevc-architecture.png
  docs/design/current/lcevc-demo.png
  docs/design/current/lcevc-integration.md
  docs/design/current/locale_compatibility.svg
  docs/design/current/locales_tree.svg
  docs/design/current/localization-design-principles.md
  docs/design/current/newdemo.gv
  docs/design/current/newdemo.gv.png
  docs/design/current/offline.gv
  docs/design/current/offline.gv.png
  docs/design/current/offline.md
  docs/design/current/ownership.gv
  docs/design/current/ownership.gv.png
  docs/design/current/talking-about-languages.md
  docs/design/current/timeline.svg
  docs/design/current/ui.md
  docs/design/current/ui_player_relationships.svg
  docs/design/future_work/bg-fetch-after.gv
  docs/design/future_work/bg-fetch-after.gv.png
  docs/design/future_work/bg-fetch-before.gv
  docs/design/future_work/bg-fetch-before.gv.png
  docs/design/future_work/bg-fetch.md
  docs/design/outdated/REDESIGN.md
Labels: type: docs, priority: P3

#7887 build: Upgrade ESLint to v9 and migrate config
  .eslintignore
  .eslintrc.js
  .gitattributes
  build/check.py
  build/eslint-plugin-shaka-rules/arg-comment-spacing.js
  build/eslint-plugin-shaka-rules/array-no-instanceof.js
  build/eslint-plugin-shaka-rules/buffersource-no-instanceof.js
  build/eslint-plugin-shaka-rules/index.js
  build/eslint-plugin-shaka-rules/package.json
  build/eslint-plugin-shaka-rules/private.js
  eslint.config.mjs
  lib/offline/storage.js
  lib/player.js
  lib/polyfill/video_play_promise.js
  lib/util/config_utils.js
  lib/util/platform.js
  lib/util/string_utils.js
  lib/util/tXml.js
  package-lock.json
  package.json
  test/cast/cast_receiver_integration.js
  test/mss/mss_player_integration.js
  test/net/http_plugin_unit.js
  test/test/boot.js
  test/transmuxer/transmuxer_integration.js
Labels: type: code health, component: build system

#7892 ci: Fix demo index workflow runs too early when a release is made
  .github/workflows/demo-version-index.yaml
  .github/workflows/release-please.yaml
Labels: type: bug, priority: P3, type: CI

#7896 fix(tXml): Fix findChildrenNS when the namespace is in the element
  lib/util/tXml.js
Labels: type: bug, priority: P2

#7898 feat(DASH): Extract PlayReady licenseServerUri from PSSH
  lib/dash/content_protection.js
  lib/drm/playready.js
  lib/util/pssh.js
  test/dash/dash_parser_content_protection_unit.js
Labels: type: enhancement, priority: P3, component: DASH, component: PlayReady

#7901 fix: Use infiniteLiveStreamDuration equal to true in Safari 17 or above
  externs/shaka/player.js
  lib/util/player_configuration.js
Labels: type: bug, priority: P2, browser: Safari

#7902 chore(Demo): Add test asset with Annex I
  demo/common/assets.js
Labels: component: demo page

#7910 fix(DASH): Ignore early segments in a period
  lib/dash/segment_template.js
Labels: type: bug, priority: P1, component: DASH

#7905 feat: Use MSE clearLiveSeekableRange and setLiveSeekableRange when available
  demo/config.js
  externs/shaka/player.js
  lib/media/media_source_capabilities.js
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/util/player_configuration.js
  test/test/util/fake_media_source_engine.js
Labels: type: enhancement, priority: P3

#7913 fix: Only create TextTrack of SimpleTextDisplayer when necessary
  externs/shaka/text.js
  lib/player.js
  lib/text/simple_text_displayer.js
  lib/text/stub_text_displayer.js
  lib/text/ui_text_displayer.js
  test/test/util/fake_text_displayer.js
  test/text/simple_text_displayer_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7916 fix: Fix setLiveSeekableRange when the seekable range is too short
  lib/media/streaming_engine.js
Labels: type: bug, priority: P2

#7909 feat: Save CEA708 caption cues on all windows when deleting/clearing windows
  lib/cea/cea708_service.js
  lib/cea/cea_decoder.js
  test/cea/cea708_service_unit.js
Labels: type: enhancement, component: captions/subtitles, priority: P1

#7921 perf: Improve GapJumpingController times
  lib/media/gap_jumping_controller.js
Labels: type: performance, priority: P2

#7922 feat(Ads): Populate getAdId and getMediaUrl for interstitials
  lib/ads/interstitial_ad.js
  lib/ads/interstitial_ad_manager.js
  lib/ads/interstitial_static_ad.js
Labels: type: enhancement, component: ads, priority: P3

#7923 fix: Avoid setAppendWindow when the window is Infinity
  lib/media/media_source_engine.js
Labels: type: bug, priority: P2

#7929 fix(CEA): Fix multi byte language support in CEA-708
  lib/cea/cea708_service.js
  test/cea/cea708_service_unit.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7914 docs: Update docs for v4.13 release
  maintained-branches.md
  roadmap.md
Labels: type: docs

#7930 chore: Stop using "Object" in HLS parser annotations
  lib/hls/hls_parser.js
Labels: type: code health

#7931 chore: Stop using "Object" in MultiMap annotations
  lib/util/multi_map.js
Labels: type: code health

#7932 chore: Stop using "Object" in Demo annotations
  demo/config.js
  demo/input.js
  demo/main.js
  demo/search.js
Labels: type: code health

#7933 chore: Stop using "Object" in plugins annotations
  lib/media/closed_caption_parser.js
  lib/media/manifest_parser.js
  lib/net/networking_engine.js
  lib/text/text_engine.js
  lib/transmuxer/transmuxer_engine.js
Labels: type: code health

#7935 chore: Stop using "Object" in some utils annotations
  lib/util/manifest_parser_utils.js
  lib/util/mp4_generator.js
  lib/util/mp4_parser.js
Labels: type: code health

#7937 chore: Stop using "Object" in networking annotations
  lib/net/networking_utils.js
Labels: type: code health

#7939 chore: Stop using "Object" in StreamBandwidthEstimator annotations
  lib/offline/stream_bandwidth_estimator.js
Labels: type: code health

#7936 chore: Stop using "Object" in UI annotations
  ui/ad_statistics_button.js
  ui/statistics_button.js
Labels: type: code health

#7938 chore: Stop using "Object" in cache annotations
  lib/polyfill/media_capabilities.js
  lib/util/stream_utils.js
Labels: type: code health

#7940 chore: Stop using "Object" in MSS annotations
  lib/mss/mss_parser.js
Labels: type: code health

#7941 chore: Stop using "Object" in Storage integration annotations
  test/offline/storage_integration.js
Labels: type: code health

#7943 chore: Stop using "Object" in Player annotations
  lib/player.js
Labels: type: code health

#7945 chore: Stop using "Object" in UI annotations
  ui/ad_statistics_button.js
  ui/statistics_button.js
Labels: type: code health

#7947 chore: Stop using "Object" in DASH
  lib/dash/dash_parser.js
  lib/dash/mpd_utils.js
  lib/dash/segment_list.js
  lib/dash/segment_template.js
Labels: type: code health

#7946 chore: Stop using "Object" in DV codecs mapping
  lib/util/stream_utils.js
Labels: type: code health

#7950 chore: Stop using "Object" in TTML annotations
  lib/text/ttml_text_parser.js
Labels: type: code health

#7951 chore: Stop using "Object" in MP4-CEA annotations
  lib/cea/mp4_cea_parser.js
Labels: type: code health

#7942 chore: Stop using "Object" in Cast functions
  lib/cast/cast_proxy.js
  lib/cast/cast_receiver.js
  lib/cast/cast_sender.js
  lib/cast/cast_utils.js
  test/cast/cast_receiver_unit.js
  test/cast/cast_utils_unit.js
Labels: type: code health

#7952 chore: Fix Demo reload
  demo/main.js
Labels: component: demo page

#7953 chore: Stop using "Object" in goog.Uri annotations
  third_party/closure-uri/uri.js
Labels: type: code health

#7944 fix(HLS): Fix redirect management at media playlist level
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#7958 fix: Fix playback with Apple Media Keys polyfill detection
  lib/dash/content_protection.js
  lib/hls/hls_parser.js
  lib/util/platform.js
  lib/util/player_configuration.js
  test/util/platform_unit.js
Labels: type: bug, priority: P2, component: FairPlay

#7954 feat: Retain segment in memory on QuotaExceededError
  externs/shaka/player.js
  lib/util/player_configuration.js
  test/media/streaming_engine_unit.js
  test/ui/ui_unit.js
Labels: type: enhancement, priority: P3

#7963 fix(net): Add 304 as successful request
  lib/net/http_plugin_utils.js
Labels: type: bug, priority: P2, component: networking

#7966 fix(DASH): Fix Dolby Atmos detection
  lib/dash/dash_parser.js
  test/dash/dash_parser_manifest_unit.js
Labels: type: bug, priority: P2, component: DASH

#7969 fix: Fix AC-3 playback on Tizen 3.0 devices
  lib/media/content_workarounds.js
  lib/media/media_source_engine.js
  lib/util/platform.js
  lib/util/stream_utils.js
  test/media/media_source_engine_unit.js
Labels: type: bug, priority: P3, platform: Tizen

#7971 fix: Use audio label on ExampleBasedCriteria
  lib/media/example_based_criteria.js
  lib/player.js
Labels: type: bug, priority: P2

#7967 feat: Simplify ignoreSupplementalCodecs config
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/player.js
  lib/util/player_configuration.js
  test/dash/dash_parser_manifest_unit.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, priority: P4

#7974 feat: Make the filters provided for FairPlay more error-resistant
  lib/util/fairplay_utils.js
Labels: type: enhancement, priority: P4, component: FairPlay

#7972 fix: Fix AC-3 playback on Tizen 3.0 devices when transmuxing
  karma.conf.js
  lib/transmuxer/ac3_transmuxer.js
  lib/util/mp4_generator.js
  test/media/content_workarounds_integration.js
  test/test/assets/dash-audio-ac3/audio_und_2c_192k_ac3_1.mp4
  test/test/assets/dash-audio-ac3/audio_und_2c_192k_ac3_2.mp4
  test/test/assets/dash-audio-ac3/audio_und_2c_192k_ac3_init.mp4
  test/test/assets/dash-audio-ac3/dash.mpd
  test/test/util/util.js
  test/transmuxer/transmuxer_integration.js
Labels: type: bug, priority: P2, platform: Tizen

#7975 chore: Update eme-encryption-scheme-polyfill to v2.2.1
  package-lock.json
  package.json
Labels: dependencies

#7979 feat(HLS): Add allowRangeRequestsToGuessMimeType config
  demo/config.js
  externs/shaka/player.js
  lib/hls/hls_parser.js
  lib/util/player_configuration.js
Labels: type: enhancement, component: HLS, priority: P3

#7980 feat: Simplify updatePeriod config
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/player.js
  lib/util/player_configuration.js
Labels: type: enhancement, priority: P4

#7983 test: Test Dolby Vision boxes in ContentWorkarounds
  test/media/content_workarounds_unit.js
Labels: component: tests

#7982 test: Add unit test for ContentWorkarounds.fakeEC3
  lib/media/content_workarounds.js
  test/media/content_workarounds_unit.js
Labels: component: tests

#7986 feat(HLS): Add an option to ignore DRM info
  demo/config.js
  externs/shaka/player.js
  lib/dash/dash_parser.js
  lib/hls/hls_parser.js
  lib/player.js
  lib/util/player_configuration.js
  test/dash/dash_parser_content_protection_unit.js
  test/hls/hls_parser_unit.js
Labels: type: enhancement, component: HLS, priority: P3

#7990 fix(UI): Show GB unit in StatisticsButton
  ui/statistics_button.js
Labels: type: bug, component: UI, priority: P2

#7988 fix: Avoid rebuffering when using big trick play rates
  lib/media/streaming_engine.js
Labels: type: bug, priority: P1

#7992 fix(HLS): Fix support for SUPPLEMENTAL-CODECS on EXT-X-I-FRAME-STREAM-INF
  lib/hls/hls_parser.js
Labels: type: bug, component: HLS, priority: P2

#7989 fix(UI): Fix show AdStatisticsButton when it's not necessary
  ui/ad_statistics_button.js
Labels: type: bug, component: UI, priority: P2

#7991 fix: Fix displaying subtitles in UITextDisplayer at high playback rates
  lib/text/ui_text_displayer.js
Labels: type: bug, component: captions/subtitles, priority: P2

#7993 fix: Allow change the native playbackRate with the same functionality as trickPlay
  lib/player.js
Labels: type: bug, priority: P2

#7994 feat: Add new error code when the streaming is not allowed
  lib/media/media_source_engine.js
  lib/media/streaming_engine.js
  lib/util/error.js
Labels: type: enhancement, priority: P3

#7995 perf: Prevent CastSender initialization on CastProxy on unsupported browsers
  lib/cast/cast_proxy.js
  test/cast/cast_proxy_unit.js
Labels: type: performance, priority: P2

#7997 chore: Disable console logs in ESLint
  build/conformance.textproto
  eslint.config.mjs
Labels: type: code health, priority: P3

#7996 fix: Do not recognize MultiChoice & Ziggo as Apple
  lib/util/platform.js
  project-words.txt
Labels: type: bug, platform: TV/STB, priority: P2

#7998 chore: Stop using "Object" in MediaSourceEngine annotations
  lib/media/media_source_engine.js
Labels: type: code health
